import type { Metadata } from "next";

export const pageMetadata = {
  home: { title: "Online Shopping & Local Services in Bangladesh — HaatBazar", description: "Shop products from verified sellers and book trusted local services on HaatBazar — Bangladesh's dual marketplace." },
  about: { title: "About Us — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  becomeProvider: { title: "List Your Service — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  becomeSeller: { title: "Become a Seller — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  blogDetails: { title: "How to spot a genuine smartphone — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  blog: { title: "Blog — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  brands: { title: "Brands — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  careers: { title: "Careers — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  cart: { title: "Shopping Cart — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  categories: { title: "All Categories — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  checkout: { title: "Checkout — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  compare: { title: "Compare Products — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  contact: { title: "Contact Us — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  faq: { title: "FAQ — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  forgotPassword: { title: "Forgot Password — HaatBazar", description: "HaatBazar" },
  helpCenter: { title: "Help Centre — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  login: { title: "Sign In — HaatBazar", description: "HaatBazar" },
  offers: { title: "Offers & Deals — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  orderSuccess: { title: "Order Confirmed — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  otpVerify: { title: "Verify Your Number — HaatBazar", description: "HaatBazar" },
  privacyPolicy: { title: "Privacy Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  productDetails: { title: "Realme C100x 6/128GB — Product Details — HaatBazar", description: "Realme C100x 6/128GB with 8000mAh battery, 45W charging and 2 years official warranty." },
  products: { title: "Smartphones — Product List — HaatBazar", description: "Buy smartphones online in Bangladesh with warranty, EMI and cash on delivery." },
  providerRegister: { title: "Service Provider Registration — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  register: { title: "Create Account — HaatBazar", description: "HaatBazar" },
  resetPassword: { title: "Set a New Password — HaatBazar", description: "HaatBazar" },
  returnPolicy: { title: "Return & Refund Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  search: { title: "Search Results — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  sellerRegister: { title: "Seller Registration — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  serviceDetails: { title: "CoolCare AC Servicing & Repair, Uttara — Service Details — HaatBazar", description: "CoolCare AC Servicing & Repair in Uttara, Dhaka. Ratings, price list, photos, timings and online booking." },
  services: { title: "Home Services in Dhaka — Local Service Directory — HaatBazar", description: "Find verified electricians, plumbers, AC technicians, cleaners and more near you." },
  shippingPolicy: { title: "Shipping & Delivery Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  shopProfile: { title: "Realme Official Store — Shop Profile — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  shops: { title: "Shops & Sellers — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  sitemap: { title: "Sitemap — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  terms: { title: "Terms of Service — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  trackOrder: { title: "Track Order — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  notFound: { title: "Page Not Found — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  userDashboard: { title: "Dashboard — HaatBazar", description: "Your HaatBazar account overview, orders and bookings." },
  userOrders: { title: "My Orders — HaatBazar", description: "Track, return or buy again from your complete order history." },
  userOrderDetails: { title: "Order HB-884213 — HaatBazar", description: "Details and tracking for your HaatBazar order." },
  userReturns: { title: "Returns & Cancellations — HaatBazar", description: "Request a return, track refunds and review cancelled orders." },
  userBookings: { title: "Service Bookings — HaatBazar", description: "Manage appointments, quotes and enquiries with local service providers." },
  userWishlist: { title: "My Wishlist — HaatBazar", description: "Your saved products and price drops." },
  userReviews: { title: "My Reviews — HaatBazar", description: "Reviews you have written and items still waiting for your feedback." },
  userWallet: { title: "Wallet & Payments — HaatBazar", description: "Your HaatBazar balance, saved payment methods and refund history." },
  userVouchers: { title: "Vouchers & Rewards — HaatBazar", description: "Collected vouchers, loyalty points, referrals and gift cards." },
  userAddresses: { title: "Address Book — HaatBazar", description: "Manage delivery and billing addresses for faster checkout." },
  userProfile: { title: "My Profile — HaatBazar", description: "Personal information, verification status and account preferences." },
  userNotifications: { title: "Notifications — HaatBazar", description: "Your HaatBazar notifications and updates." },
  userMessages: { title: "Messages — HaatBazar", description: "Chat with sellers, service providers and HaatBazar support." },
  userSupport: { title: "Support Tickets — HaatBazar", description: "Raise an issue and track responses from the HaatBazar care team." },
  userSettings: { title: "Settings — HaatBazar", description: "Security, privacy, sessions and app preferences." },
  vendorAcademy: { title: "Seller Academy — HaatBazar", description: "Free courses, guides and webinars to grow your business on HaatBazar." },
  vendorAddProduct: { title: "Add New Product — HaatBazar", description: "Complete all sections to publish. Products go live after a quick admin review." },
  vendorAddService: { title: "Add New Service — HaatBazar", description: "Service listings appear in the HaatBazar local directory and receive calls, chats and bookings." },
  vendorAds: { title: "Ads & Boost — HaatBazar", description: "Promote your products and services with sponsored placements." },
  vendorAnalytics: { title: "Analytics & Insights — HaatBazar", description: "Understand your traffic, conversion and customer behaviour across both businesses." },
  vendorBookings: { title: "Bookings & Appointments — HaatBazar", description: "Manage confirmed service jobs, schedules, technicians and site visits." },
  vendorBusinessProfile: { title: "Business Profile — HaatBazar", description: "This is what customers see on your public service listing page." },
  vendorCustomers: { title: "My Customers — HaatBazar", description: "Everyone who has ordered products or booked services from you." },
  vendorDashboard: { title: "Vendor Dashboard — HaatBazar", description: "A snapshot of your product and service business." },
  vendorDocuments: { title: "Verification & KYC — HaatBazar", description: "Upload and manage the documents that keep your seller account verified." },
  vendorInventory: { title: "Inventory & Stock — HaatBazar", description: "Track stock levels across warehouses, set alerts and log adjustments." },
  vendorInvoices: { title: "Invoices & Tax — HaatBazar", description: "Order invoices, service bills, VAT records and tax documents." },
  vendorLeads: { title: "Leads & Enquiries — HaatBazar", description: "Customer enquiries from your service listings — respond fast to win more jobs." },
  vendorMessages: { title: "Messages — HaatBazar", description: "Chat with customers about products, orders and service enquiries." },
  vendorNotifications: { title: "Notifications — HaatBazar", description: "Orders, leads, payouts, policy updates and platform announcements." },
  vendorOrderDetails: { title: "Order HB-884213 — HaatBazar", description: "Order details, fulfilment status, items and payment summary." },
  vendorOrders: { title: "Orders — HaatBazar", description: "Process, fulfil and track your customer orders." },
  vendorPayouts: { title: "Payouts & Balance — HaatBazar", description: "Your earnings, pending settlements and bank withdrawals." },
  vendorProducts: { title: "All Products — HaatBazar", description: "Manage your product listings, pricing, stock and visibility." },
  vendorPromotions: { title: "Promotions & Vouchers — HaatBazar", description: "Create discounts, seller vouchers, bundles and flash deals for your shop." },
  vendorQuestions: { title: "Product Q&A — HaatBazar", description: "Answer buyer questions on your product pages." },
  vendorReports: { title: "Reports & Statements — HaatBazar", description: "Download detailed business reports, statements and performance exports." },
  vendorReturns: { title: "Returns & Refunds — HaatBazar", description: "Approve or reject return requests within 48 hours to avoid auto-approval." },
  vendorReviews: { title: "Reviews & Ratings — HaatBazar", description: "Reply to customer feedback, request reviews and track your rating health." },
  vendorServices: { title: "Service Listings — HaatBazar", description: "Manage your service listings in the local directory." },
  vendorSettings: { title: "Settings — HaatBazar", description: "Account, shop, security, notification and integration preferences." },
  vendorShipping: { title: "Shipping & Couriers — HaatBazar", description: "Delivery zones, shipping rates, courier partners and pickup settings." },
  vendorShopProfile: { title: "Shop Profile — HaatBazar", description: "This is your product storefront — banners, story, policies and social links." },
  vendorStaff: { title: "Staff & Permissions — HaatBazar", description: "Invite team members and control exactly what each person can access." },
  vendorSubscription: { title: "Plan & Billing — HaatBazar", description: "Your seller plan, commission rate, invoices and add-ons." },
  vendorTransactions: { title: "Transactions — HaatBazar", description: "Every credit and debit on your seller account ledger." },

  // Admin panel (src/features/admin/pages) — one entry per /admin/* route.
  adminAbandonedCarts: { title: "Abandoned Carts — HaatBazar", description: "Recover lost revenue with reminders, vouchers and price-drop alerts." },
  adminActivity: { title: "Audit Log — HaatBazar", description: "Every action taken by admins, staff, vendors and the system — immutable and searchable." },
  adminAds: { title: "Ads Manager — HaatBazar", description: "Sponsored listings, banner inventory, vendor ad campaigns and ad revenue." },
  adminAnalytics: { title: "Traffic & Analytics — HaatBazar", description: "Visitors, conversion funnel, cohorts and marketplace performance." },
  adminAttributes: { title: "Attributes & Specifications — HaatBazar", description: "Variant options, filters and specification templates used by listings." },
  adminBlog: { title: "Blog & Guides — HaatBazar", description: "Buying guides, service tips, news posts, categories and author management." },
  adminBookings: { title: "Service Bookings — HaatBazar", description: "All appointments and service bookings made through the platform." },
  adminBrands: { title: "Brands — HaatBazar", description: "Brand directory, authorisation control and brand store pages." },
  adminCampaigns: { title: "Campaigns & Flash Sales — HaatBazar", description: "Plan festival campaigns, flash sales, vendor participation and campaign budgets." },
  adminCategories: { title: "Categories — HaatBazar", description: "Product category tree, commission rates and homepage placement." },
  adminChats: { title: "Live Chat Monitor — HaatBazar", description: "Monitor and join live conversations between customers, vendors and agents." },
  adminCms: { title: "Homepage & Banners — HaatBazar", description: "Control every block on the storefront home page, sliders, banners and placements." },
  adminCommissions: { title: "Commissions & Plans — HaatBazar", description: "Commission rules, subscription plans, lead pricing and vendor-specific overrides." },
  adminCustomers: { title: "Customers — HaatBazar", description: "All registered buyers with orders, wallet, loyalty tier and risk signals." },
  adminDashboard: { title: "Platform Dashboard — HaatBazar", description: "Live overview of marketplace performance, approvals and system health." },
  adminDisputes: { title: "Returns & Disputes — HaatBazar", description: "Return requests, refund claims and buyer–seller disputes needing resolution." },
  adminEmailTemplates: { title: "Email & SMS Templates — HaatBazar", description: "Every transactional message sent by the platform, with variables and previews." },
  adminFaq: { title: "Help Centre — HaatBazar", description: "FAQ articles, categories, ordering and helpfulness feedback." },
  adminGiftCards: { title: "Gift Cards & Wallets — HaatBazar", description: "Issue gift cards, manage customer wallet balances and loyalty points." },
  adminIntegrations: { title: "Integrations & API — HaatBazar", description: "Third-party services, couriers, SMS, analytics, webhooks and API keys." },
  adminInventory: { title: "Stock Overview — HaatBazar", description: "Marketplace-wide stock levels, low-stock risks and price change monitoring." },
  adminInvoices: { title: "Invoices — HaatBazar", description: "Customer invoices, vendor commission invoices and subscription bills." },
  adminKyc: { title: "KYC Verification — HaatBazar", description: "Identity, business and bank verification for vendors and high-value customers." },
  adminLeads: { title: "Leads & Enquiries — HaatBazar", description: "Customer enquiries sent to service providers, with quality and billing control." },
  adminLocations: { title: "Locations & Zones — HaatBazar", description: "Divisions, districts, cities, areas, delivery zones and service coverage." },
  adminLogs: { title: "System Logs — HaatBazar", description: "Application errors, background jobs, emails, SMS, webhooks and API traffic." },
  adminMedia: { title: "Media Library — HaatBazar", description: "All images, videos and documents uploaded by staff and vendors." },
  adminModeration: { title: "Reports & Abuse — HaatBazar", description: "User reports, counterfeit complaints, prohibited items and enforcement actions." },
  adminNotifications: { title: "Push & Broadcast — HaatBazar", description: "Send push, SMS, email and in-app messages to customers, vendors and staff." },
  adminOrders: { title: "Orders — HaatBazar", description: "All marketplace orders with payment, fulfilment and dispute status." },
  adminPages: { title: "Static Pages — HaatBazar", description: "All policy, informational and landing pages on the storefront." },
  adminPaymentMethods: { title: "Payment Methods — HaatBazar", description: "Gateways, mobile wallets, cards, COD, EMI and payout channels." },
  adminPayouts: { title: "Vendor Payouts — HaatBazar", description: "Settlement cycles, payout approvals and bank disbursement files." },
  adminProductApprovals: { title: "Product Approvals — HaatBazar", description: "Review new and edited listings before they go live." },
  adminProducts: { title: "Products — HaatBazar", description: "Every product listing across all vendors on the marketplace." },
  adminPromotions: { title: "Coupons & Vouchers — HaatBazar", description: "Platform-funded coupons, vendor coupons, free-delivery codes and referral rewards." },
  adminQuestions: { title: "Q&A Moderation — HaatBazar", description: "Customer questions on products and services, vendor answers and community replies." },
  adminReports: { title: "Reports Centre — HaatBazar", description: "Generate, schedule and download every platform report." },
  adminReviews: { title: "Reviews Moderation — HaatBazar", description: "Product and service reviews, ratings, photos, replies and fake-review detection." },
  adminRoles: { title: "Roles & Permissions — HaatBazar", description: "Granular access control for every admin module and action." },
  adminSeo: { title: "SEO Manager — HaatBazar", description: "Meta tags, URL slugs, sitemaps, redirects, schema markup and search performance." },
  adminServiceApprovals: { title: "Service Approvals & Claims — HaatBazar", description: "Approve new listings, verification documents and business ownership claims." },
  adminServiceCategories: { title: "Service Categories — HaatBazar", description: "Directory category tree, lead pricing and city-wise availability." },
  adminServices: { title: "Service Listings — HaatBazar", description: "All directory listings from service providers across Bangladesh." },
  adminSettings: { title: "Platform Settings — HaatBazar", description: "Global configuration for the marketplace, storefront, orders, services and security." },
  adminShipping: { title: "Shipping & Logistics — HaatBazar", description: "Courier partners, delivery zones, rates and shipment performance." },
  adminStaff: { title: "Staff & Admins — HaatBazar", description: "Platform team members, their roles, departments and access activity." },
  adminSystemHealth: { title: "System Health — HaatBazar", description: "Uptime, performance, infrastructure, backups and incident status." },
  adminTaxes: { title: "Tax & VAT — HaatBazar", description: "VAT rates, tax classes, HS codes, TDS/VDS rules and NBR reporting." },
  adminTickets: { title: "Support Tickets — HaatBazar", description: "Customer and vendor tickets across orders, bookings, payments and accounts." },
  adminTransactions: { title: "Transactions — HaatBazar", description: "Every money movement — payments, refunds, payouts, fees and wallet activity." },
  adminVendorApprovals: { title: "Vendor Approvals — HaatBazar", description: "Review seller and service-provider applications before they go live." },
  adminVendors: { title: "Vendors — HaatBazar", description: "All product sellers and service providers with performance, plan and compliance data." },
} satisfies Record<string, Metadata>;
