import type { Metadata } from "next";

export const pageMetadata = {
  home: { title: "Online Shopping & Local Services in Bangladesh — HaatBazar", description: "Shop products from verified sellers and book trusted local services on HaatBazar — Bangladesh's dual marketplace." },
  about: { title: "About Us — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  becomeProvider: { title: "List Your Service — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  becomeSeller: { title: "Become a Seller — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  blogDetails: { title: "How to spot a genuine smartphone — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  blog: { title: "Blog — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  brands: { title: "Brands — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  careers: { title: "Careers — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  cart: { title: "Shopping Cart — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  categories: { title: "All Categories — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  checkout: { title: "Checkout — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  compare: { title: "Compare Products — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  contact: { title: "Contact Us — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  faq: { title: "FAQ — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  forgotPassword: { title: "Forgot Password — HaatBazar", description: "HaatBazar" },
  helpCenter: { title: "Help Centre — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  login: { title: "Sign In — HaatBazar", description: "HaatBazar" },
  offers: { title: "Offers & Deals — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  orderSuccess: { title: "Order Confirmed — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  otpVerify: { title: "Verify Your Number — HaatBazar", description: "HaatBazar" },
  privacyPolicy: { title: "Privacy Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  productDetails: { title: "Realme C100x 6/128GB — Product Details — HaatBazar", description: "Realme C100x 6/128GB with 8000mAh battery, 45W charging and 2 years official warranty." },
  products: { title: "Smartphones — Product List — HaatBazar", description: "Buy smartphones online in Bangladesh with warranty, EMI and cash on delivery." },
  providerRegister: { title: "Service Provider Registration — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  register: { title: "Create Account — HaatBazar", description: "HaatBazar" },
  resetPassword: { title: "Set a New Password — HaatBazar", description: "HaatBazar" },
  returnPolicy: { title: "Return & Refund Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  search: { title: "Search Results — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  sellerRegister: { title: "Seller Registration — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  serviceDetails: { title: "CoolCare AC Servicing & Repair, Uttara — Service Details — HaatBazar", description: "CoolCare AC Servicing & Repair in Uttara, Dhaka. Ratings, price list, photos, timings and online booking." },
  services: { title: "Home Services in Dhaka — Local Service Directory — HaatBazar", description: "Find verified electricians, plumbers, AC technicians, cleaners and more near you." },
  shippingPolicy: { title: "Shipping & Delivery Policy — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  shopProfile: { title: "Realme Official Store — Shop Profile — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  shops: { title: "Shops & Sellers — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  sitemap: { title: "Sitemap — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  terms: { title: "Terms of Service — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  trackOrder: { title: "Track Order — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
  notFound: { title: "Page Not Found — HaatBazar", description: "HaatBazar — products and local services in Bangladesh." },
} satisfies Record<string, Metadata>;
