export default function AddressesPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/user/dashboard">My Account</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Account</span><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Addresses</span></nav>
      <h1>Address Book</h1><p>Manage delivery and billing addresses for faster checkout.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-primary" data-modal-open="addr-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add new address</button></div></div>
      
      <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3.5"><div className="card p-4 ring-2 ring-brand-500/20 border-brand-200">
      <div className="flex items-center gap-2 mb-3"><span className="w-9 h-9 rounded-xl bg-brand-50 text-brand-600 grid place-items-center"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V9.5l8-6 8 6V20"/><path d="M9.5 20v-6h5v6"/></svg></span>
      <p className="text-[14px] font-extrabold">Home</p>
      <span className="badge badge-brand">Default shipping</span><span className="badge badge-gray">Billing</span>
      <div className="ml-auto"><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit address</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Set as billing</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></div></div>
      <p className="text-[13.5px] font-bold mb-0.5">Nusrat Jahan</p>
      <p className="text-[12.5px] text-ink-500 mb-2">+880 1712-345678</p>
      <p className="text-[13px] text-ink-600 leading-relaxed">House 42, Road 8, Block C<br />Banani, Dhaka 1213<br />Dhaka Division · Banani</p>
      <p className="text-[12px] text-ink-400 mt-2 p-2 rounded-lg bg-ink-50"><svg className="w-3.5 h-3.5 inline" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg> Please call before arriving. Green gate, 3rd floor.</p>
      <div className="flex gap-2 mt-3 pt-3 border-t border-[#f0f1f5]"><button className="btn btn-xs btn-outline flex-1" data-modal-open="addr-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</button>
      
      <button className="btn btn-xs btn-danger btn-icon"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></div><div className="card p-4 ">
      <div className="flex items-center gap-2 mb-3"><span className="w-9 h-9 rounded-xl bg-ink-50 text-ink-600 grid place-items-center"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h16v12H4z"/><path d="M9 8V4h6v4"/></svg></span>
      <p className="text-[14px] font-extrabold">Office</p>
      
      <div className="ml-auto"><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit address</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Set as billing</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></div></div>
      <p className="text-[13.5px] font-bold mb-0.5">Nusrat Jahan</p>
      <p className="text-[12.5px] text-ink-500 mb-2">+880 1712-345678</p>
      <p className="text-[13px] text-ink-600 leading-relaxed">Level 5, Rangs Babylonia, Plot 246<br />Gulshan 1, Dhaka 1212<br />Dhaka Division · Gulshan</p>
      <p className="text-[12px] text-ink-400 mt-2 p-2 rounded-lg bg-ink-50"><svg className="w-3.5 h-3.5 inline" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg> Reception will receive after 10 AM.</p>
      <div className="flex gap-2 mt-3 pt-3 border-t border-[#f0f1f5]"><button className="btn btn-xs btn-outline flex-1" data-modal-open="addr-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</button>
      <button className="btn btn-xs btn-outline flex-1">Set default</button>
      <button className="btn btn-xs btn-danger btn-icon"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></div><div className="card p-4 ">
      <div className="flex items-center gap-2 mb-3"><span className="w-9 h-9 rounded-xl bg-ink-50 text-ink-600 grid place-items-center"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 21s-7-5.5-7-11a7 7 0 1 1 14 0c0 5.5-7 11-7 11z"/><circle cx="12" cy="10" r="2.5"/></svg></span>
      <p className="text-[14px] font-extrabold">Parents' house</p>
      
      <div className="ml-auto"><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit address</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Set as billing</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></div></div>
      <p className="text-[13.5px] font-bold mb-0.5">Abdul Karim</p>
      <p className="text-[12.5px] text-ink-500 mb-2">+880 1811-223344</p>
      <p className="text-[13px] text-ink-600 leading-relaxed">Village: Char Kalibari, Post: Sadar<br />Jamalpur 2000<br />Jamalpur Division · Sadar</p>
      
      <div className="flex gap-2 mt-3 pt-3 border-t border-[#f0f1f5]"><button className="btn btn-xs btn-outline flex-1" data-modal-open="addr-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</button>
      <button className="btn btn-xs btn-outline flex-1">Set default</button>
      <button className="btn btn-xs btn-danger btn-icon"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></div><div className="card p-4 ">
      <div className="flex items-center gap-2 mb-3"><span className="w-9 h-9 rounded-xl bg-ink-50 text-ink-600 grid place-items-center"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 21s-7-5.5-7-11a7 7 0 1 1 14 0c0 5.5-7 11-7 11z"/><circle cx="12" cy="10" r="2.5"/></svg></span>
      <p className="text-[14px] font-extrabold">Sister's flat</p>
      
      <div className="ml-auto"><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit address</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Set as billing</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></div></div>
      <p className="text-[13.5px] font-bold mb-0.5">Farhana Jahan</p>
      <p className="text-[12.5px] text-ink-500 mb-2">+880 1911-556677</p>
      <p className="text-[13px] text-ink-600 leading-relaxed">Flat B4, House 12, Road 3<br />Dhanmondi, Dhaka 1205<br />Dhaka Division · Dhanmondi</p>
      
      <div className="flex gap-2 mt-3 pt-3 border-t border-[#f0f1f5]"><button className="btn btn-xs btn-outline flex-1" data-modal-open="addr-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</button>
      <button className="btn btn-xs btn-outline flex-1">Set default</button>
      <button className="btn btn-xs btn-danger btn-icon"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></div>
      <button className="card p-4 border-dashed border-2 grid place-items-center min-h-[220px] hover:border-brand-300 hover:bg-brand-50" data-modal-open="addr-modal">
      <span className="w-12 h-12 rounded-2xl bg-brand-50 text-brand-600 grid place-items-center mb-2"><svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg></span>
      <p className="text-[13.5px] font-extrabold">Add a new address</p><p className="text-[12px] text-ink-400">Save up to 10 addresses</p></button></div>
      
      <div className="card mt-4"><div className="card-head"><h3>Delivery preferences</h3><div className="flex items-center gap-2"></div></div><div className="p-5 space-y-3"><label className="flex items-center justify-between gap-3 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[13px] text-ink-700">Leave parcel with security or neighbour if I am not home</span>
      <span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[13px] text-ink-700">Send SMS before the rider arrives</span>
      <span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[13px] text-ink-700">Call me before delivery attempt</span>
      <span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[13px] text-ink-700">Allow contactless delivery</span>
      <span className="switch"><input type="checkbox"  /><span className="track"></span></span></label></div></div>
      
      <div className="modal" id="addr-modal"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel">
      <div className="card-head"><h3>Add / edit address</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="grid sm:grid-cols-2 gap-3 mb-3">
      <div><label className="label">Full name <span className="req">*</span></label><input className="input" defaultValue="Nusrat Jahan" /></div>
      <div><label className="label">Mobile number <span className="req">*</span></label><div className="input-affix"><span className="affix">+880</span><input className="input" defaultValue="1712-345678" /></div></div>
      <div><label className="label">Alternate phone</label><input className="input" placeholder="Optional backup number" /></div>
      <div><label className="label">Email (for updates)</label><input className="input" placeholder="you@example.com" /></div>
      <div><label className="label">Division <span className="req">*</span></label><select className="select"><option>Dhaka</option><option>Chattogram</option><option>Rajshahi</option><option>Khulna</option><option>Barishal</option><option>Sylhet</option><option>Rangpur</option><option>Mymensingh</option></select></div>
      <div><label className="label">District <span className="req">*</span></label><select className="select"><option>Dhaka</option><option>Gazipur</option><option>Narayanganj</option><option>Savar</option></select></div>
      <div><label className="label">Area / Thana <span className="req">*</span></label><select className="select"><option>Banani</option><option>Gulshan</option><option>Dhanmondi</option><option>Mirpur</option><option>Uttara</option><option>Mohakhali</option></select></div>
      <div><label className="label">Postal code</label><input className="input" defaultValue="1213" /></div></div>
      <label className="label">Street address <span className="req">*</span></label><input className="input mb-3" defaultValue="House 42, Road 8, Block C" />
      <label className="label">Landmark / delivery note</label><textarea className="textarea !min-h-[70px] mb-3" placeholder="e.g. Opposite Banani Kacha Bazar, green gate" defaultValue="Please call before arriving. Green gate, 3rd floor."></textarea>
      <label className="label">Pin location on map</label><div className="rounded-xl overflow-hidden border border-[#e7e9ef] mb-3 relative"><span className="ph ph-d h-[150px] w-full"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M12 21s-7-5.5-7-11a7 7 0 1 1 14 0c0 5.5-7 11-7 11z"/><circle cx="12" cy="10" r="2.5"/></svg></span><button className="btn btn-xs btn-outline absolute right-2 bottom-2 !bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 21s-7-5.5-7-11a7 7 0 1 1 14 0c0 5.5-7 11-7 11z"/><circle cx="12" cy="10" r="2.5"/></svg>Use my location</button></div>
      <label className="label">Address label</label><div className="flex gap-2 mb-3" data-chip-group><button className="chip is-active">Home</button><button className="chip ">Office</button><button className="chip ">Other</button></div>
      <div className="space-y-2 mb-4"><label className="check"><input type="checkbox" defaultChecked />Set as default shipping address</label>
      <label className="check"><input type="checkbox" />Set as default billing address</label></div>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Address saved successfully">Save address</button></div></div></div></div>
    </>
  );
}
