export default function OrderDetailsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/user/dashboard">My Account</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">My Orders</span><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">HB-884213</span></nav>
      <h1>Order HB-884213</h1><p>Placed on 14 August 2026, 10:24 AM · 2 items · Paid with bKash</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 8V3h10v5"/><rect x="4" y="8" width="16" height="8" rx="2"/><path d="M7 16h10v5H7z"/></svg>Print invoice</button><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download PDF</button><button className="btn btn-sm btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Contact seller</button></div></div>
      
      <div className="grid lg:grid-cols-[minmax(0,1fr)_360px] gap-4">
      <div className="space-y-4">
      <div className="card "><div className="p-5"><div className="flex flex-wrap items-center gap-3 mb-5"><span className="badge badge-blue"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7h11v8H3zM14 10h4l3 3v2h-7z"/><circle cx="6.5" cy="17.5" r="1.5"/><circle cx="17.5" cy="17.5" r="1.5"/></svg>In transit</span>
      <p className="text-[13px] text-ink-600">Estimated delivery <b className="text-ink-900">Tuesday, 18 August 2026</b></p>
      <span className="badge badge-gray ml-auto">Tracking: PTH-884213-BD</span></div>
      <div className="steps mb-6 overflow-x-auto pb-1"><div className="step is-done"><span className="num"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>Placed</div><span className="step-line"></span><div className="step is-done"><span className="num"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>Confirmed</div><span className="step-line"></span><div className="step is-done"><span className="num"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>Packed</div><span className="step-line"></span><div className="step is-current"><span className="num">4</span>Shipped</div><span className="step-line"></span><div className="step "><span className="num">5</span>Out for delivery</div><span className="step-line"></span><div className="step "><span className="num">6</span>Delivered</div></div>
      <div className="timeline"><div className="tl-item is-active"><p className="text-[13px] font-bold">Parcel arrived at Tejgaon sorting hub</p><p className="text-[12px] text-ink-400">Dhaka · 16 Aug 2026, 7:45 PM</p></div><div className="tl-item is-done"><p className="text-[13px] font-bold">Parcel picked up by Pathao Courier</p><p className="text-[12px] text-ink-400">Mirpur · 15 Aug 2026, 4:20 PM</p></div><div className="tl-item is-done"><p className="text-[13px] font-bold">Seller packed your order</p><p className="text-[12px] text-ink-400">Rahim Electronics · 15 Aug 2026, 9:10 AM</p></div><div className="tl-item is-done"><p className="text-[13px] font-bold">Payment confirmed via bKash</p><p className="text-[12px] text-ink-400">14 Aug 2026, 10:26 AM</p></div><div className="tl-item is-done"><p className="text-[13px] font-bold">Order placed</p><p className="text-[12px] text-ink-400">14 Aug 2026, 10:24 AM</p></div></div></div></div>
      
      <div className="card "><div className="card-head"><h3>Items in this order (2)</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-3"><div className="flex flex-wrap gap-3 p-3 rounded-xl border border-[#e7e9ef]"><span className="ph ph-a w-16 h-16 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><rect x="7" y="2" width="10" height="20" rx="2.5"/><path d="M11 19h2"/></svg></span>
      <div className="flex-1 min-w-[180px]"><a href="/product-details" className="text-[13.5px] font-bold hover:text-brand-600">Realme C100X 6/128GB — Green</a>
      <p className="text-[12px] text-ink-500 mt-0.5">Sold by <a href="/shop-profile" className="link">Rahim Electronics</a></p>
      <p className="text-[12px] text-ink-400">Colour: Green · Warranty: 1 year official</p></div>
      <div className="text-right"><p className="text-[14px] font-extrabold">৳11,290</p><p className="text-[12px] text-ink-500">Qty: 1</p></div>
      <div className="flex gap-2 w-full sm:w-auto"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Review</button><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 14 4 9l5-5"/><path d="M4 9h9a7 7 0 0 1 0 14H8"/></svg>Return</button><button className="btn btn-xs btn-primary" data-cart-add>Buy again</button></div></div><div className="flex flex-wrap gap-3 p-3 rounded-xl border border-[#e7e9ef]"><span className="ph ph-b w-16 h-16 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="flex-1 min-w-[180px]"><a href="/product-details" className="text-[13.5px] font-bold hover:text-brand-600">Tempered Glass Protector</a>
      <p className="text-[12px] text-ink-500 mt-0.5">Sold by <a href="/shop-profile" className="link">Rahim Electronics</a></p>
      <p className="text-[12px] text-ink-400">Colour: Green · Warranty: 1 year official</p></div>
      <div className="text-right"><p className="text-[14px] font-extrabold">৳200</p><p className="text-[12px] text-ink-500">Qty: 2</p></div>
      <div className="flex gap-2 w-full sm:w-auto"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Review</button><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 14 4 9l5-5"/><path d="M4 9h9a7 7 0 0 1 0 14H8"/></svg>Return</button><button className="btn btn-xs btn-primary" data-cart-add>Buy again</button></div></div></div></div>
      
      <div className="card "><div className="card-head"><h3>Delivery &amp; payment</h3><div className="flex items-center gap-2"></div></div><div className="p-5 grid sm:grid-cols-2 gap-5">
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Shipping address</p>
      <p className="text-[13.5px] font-bold">Nusrat Jahan</p><p className="text-[13px] text-ink-600 leading-relaxed">House 42, Road 8, Block C<br />Banani, Dhaka 1213<br />+880 1712-345678</p>
      <span className="badge badge-gray mt-2">Home</span></div>
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Billing address</p>
      <p className="text-[13.5px] font-bold">Nusrat Jahan</p><p className="text-[13px] text-ink-600 leading-relaxed">Same as shipping address<br />&nbsp;<br />&nbsp;</p></div>
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Payment method</p>
      <div className="flex items-center gap-2.5"><span className="w-10 h-10 rounded-lg bg-brand-50 text-brand-600 grid place-items-center"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M16 12h2"/></svg></span>
      <div><p className="text-[13px] font-bold">bKash — 01712xxxx78</p><p className="text-[12px] text-ink-500">Transaction ID: BKS8842137X</p></div></div>
      <span className="badge badge-green mt-2"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Payment successful</span></div>
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Shipping method</p>
      <p className="text-[13px] font-bold">Standard delivery</p><p className="text-[12.5px] text-ink-500">Pathao Courier · 2–3 working days</p>
      <p className="text-[12.5px] text-ink-500 mt-1">Delivery note: Please call before arriving.</p></div></div></div>
      </div>
      
      <aside className="space-y-4">
      <div className="card "><div className="card-head"><h3>Order summary</h3><div className="flex items-center gap-2"></div></div><div className="p-5 space-y-2.5 text-[13px]">
      <div className="flex justify-between"><span className="text-ink-500">Subtotal (2 items)</span><span className="font-semibold ">৳11,690</span></div><div className="flex justify-between"><span className="text-ink-500">Delivery fee</span><span className="font-semibold ">৳80</span></div><div className="flex justify-between"><span className="text-ink-500">Voucher — NEW20</span><span className="font-semibold text-green-600">-৳400</span></div><div className="flex justify-between"><span className="text-ink-500">Wallet credit used</span><span className="font-semibold text-green-600">-৳80</span></div><div className="flex justify-between"><span className="text-ink-500">VAT (included)</span><span className="font-semibold ">৳0</span></div>
      <div className="dotted-sep !my-3"></div>
      <div className="flex justify-between items-center"><span className="text-[14px] font-extrabold">Total paid</span><span className="text-[20px] font-extrabold text-brand-600">৳11,290</span></div>
      <p className="text-[11.5px] text-ink-400">You saved ৳480 on this order</p></div></div>
      <div className="card "><div className="card-head"><h3>Need help with this order?</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-2"><a  className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Message the seller<svg className="w-4 h-4 ml-auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a><a href="/user/support" className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Open a support ticket<svg className="w-4 h-4 ml-auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a><a href="/user/returns" className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 14 4 9l5-5"/><path d="M4 9h9a7 7 0 0 1 0 14H8"/></svg>Return or exchange<svg className="w-4 h-4 ml-auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a><a  className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Report a problem<svg className="w-4 h-4 ml-auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a><a  className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Request invoice copy<svg className="w-4 h-4 ml-auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div>
      <div className="card "><div className="card-head"><h3>Seller information</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="flex items-center gap-3 mb-3"><span className="ph ph-c w-12 h-12 rounded-xl"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h16v12H4z"/><path d="M9 8V4h6v4"/></svg></span>
      <div className="min-w-0"><p className="text-[13.5px] font-bold">Rahim Electronics</p><div className="flex items-center gap-1.5"><span className="stars "><svg viewBox="0 0 24 24" ><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg><svg viewBox="0 0 24 24" ><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg><svg viewBox="0 0 24 24" ><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg><svg viewBox="0 0 24 24" ><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg><svg viewBox="0 0 24 24" ><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg></span><span className="text-[11.5px] text-ink-500">4.8 (2,340)</span></div></div></div>
      <div className="grid grid-cols-3 gap-2 text-center mb-3"><div className="p-2 rounded-lg bg-ink-50"><p className="text-[13px] font-extrabold">98%</p><p className="text-[10.5px] text-ink-500">Ship on time</p></div><div className="p-2 rounded-lg bg-ink-50"><p className="text-[13px] font-extrabold">4.8</p><p className="text-[10.5px] text-ink-500">Rating</p></div><div className="p-2 rounded-lg bg-ink-50"><p className="text-[13px] font-extrabold">1hr</p><p className="text-[10.5px] text-ink-500">Response</p></div></div>
      <a href="/shop-profile" className="btn btn-sm btn-outline btn-block">Visit store</a></div></div>
      <div className="card "><div className="card-head"><h3>Buyer protection</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-2.5"><p className="flex items-center gap-2 text-[12.5px] text-ink-600"><svg className="w-4 h-4 text-service-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>7-day easy return</p><p className="flex items-center gap-2 text-[12.5px] text-ink-600"><svg className="w-4 h-4 text-service-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Genuine product guarantee</p><p className="flex items-center gap-2 text-[12.5px] text-ink-600"><svg className="w-4 h-4 text-service-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Money-back guarantee</p><p className="flex items-center gap-2 text-[12.5px] text-ink-600"><svg className="w-4 h-4 text-service-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>24/7 customer support</p></div></div>
      </aside></div>
    </>
  );
}
