export default function ReturnsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/user/dashboard">My Account</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Shopping</span><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Returns</span></nav>
      <h1>Returns &amp; Cancellations</h1><p>Request a return, track refunds and review cancelled orders.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-primary" data-modal-open="return-modal"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>New return request</button></div></div>
      
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 14 4 9l5-5"/><path d="M4 9h9a7 7 0 0 1 0 14H8"/></svg></span>
      </div>
      <p className="val">4</p><p className="lbl">Total returns</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">1</p><p className="lbl">In progress</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      </div>
      <p className="val">2</p><p className="lbl">Refunded</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M16 12h2"/></svg></span>
      </div>
      <p className="val">৳4,150</p><p className="lbl">Total refunded</p></div></div>
      <div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All requests<span className="count">4</span></button><button className="tab " data-tab="t1">Pending approval<span className="count">1</span></button><button className="tab " data-tab="t2">Approved<span className="count">1</span></button><button className="tab " data-tab="t3">In transit<span className="count">0</span></button><button className="tab " data-tab="t4">Refunded<span className="count">2</span></button><button className="tab " data-tab="t5">Rejected<span className="count">0</span></button><button className="tab " data-tab="t6">Cancellations<span className="count">2</span></button></div>
      <div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All time</option><option>Last 30 days</option><option>Last 3 months</option></select><select className="select input-sm !w-auto"><option>All types</option><option>Return</option><option>Exchange</option><option>Cancellation</option></select><select className="select input-sm !w-auto"><option>All statuses</option><option>Pending</option><option>Approved</option><option>Refunded</option><option>Rejected</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div>
      <div className="space-y-3.5"><div className="card overflow-hidden">
      <div className="flex flex-wrap items-center gap-3 px-4 py-3 bg-ink-50 border-b border-[#e7e9ef]">
      <span className="text-[12.5px] font-extrabold">RTN-4821</span><span className="st st-hold">Refunded</span><span className="text-[12px] text-ink-500">Requested 24 Jul 2026</span>
      <div className="ml-auto flex items-center gap-2"><span className="text-[12px] text-ink-500">Refund amount</span><b className="text-[15px] text-brand-600">৳2,300</b></div></div>
      <div className="p-4 flex flex-wrap gap-4">
      <div className="flex gap-3 flex-1 min-w-[240px]"><span className="ph ph-a w-16 h-16 rounded-xl shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13.5px] font-bold clamp-1">Smart Watch — Fitness Pro</p><p className="text-[12px] text-ink-500">Sold by Gadget Hub BD</p>
      <p className="text-[12px] text-ink-600 mt-1"><b>Reason:</b> Item defective — screen not responding</p><p className="text-[12px] text-ink-400 mt-0.5">Refunded to bKash on 29 Jul</p></div></div>
      <div className="flex flex-wrap gap-2 items-start"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</button>
      
      
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Contact support</button></div></div>
      <div className="px-4 pb-4"><div className="flex flex-wrap gap-6 p-3 rounded-xl bg-ink-50"><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Requested</p><p className="text-[12.5px] font-bold">24 Jul 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Approved</p><p className="text-[12.5px] font-bold">17 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Picked up</p><p className="text-[12.5px] font-bold">19 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Refunded</p><p className="text-[12.5px] font-bold">22 Aug 2026</p></div></div></div></div><div className="card overflow-hidden">
      <div className="flex flex-wrap items-center gap-3 px-4 py-3 bg-ink-50 border-b border-[#e7e9ef]">
      <span className="text-[12.5px] font-extrabold">RTN-4790</span><span className="st st-pending">Pending</span><span className="text-[12px] text-ink-500">Requested 12 Aug 2026</span>
      <div className="ml-auto flex items-center gap-2"><span className="text-[12px] text-ink-500">Refund amount</span><b className="text-[15px] text-brand-600">৳2,950</b></div></div>
      <div className="p-4 flex flex-wrap gap-4">
      <div className="flex gap-3 flex-1 min-w-[240px]"><span className="ph ph-b w-16 h-16 rounded-xl shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13.5px] font-bold clamp-1">Wooden Bookshelf — 3 Tier</p><p className="text-[12px] text-ink-500">Sold by Kaner Furniture</p>
      <p className="text-[12px] text-ink-600 mt-1"><b>Reason:</b> Wrong item delivered — received 2 tier</p><p className="text-[12px] text-ink-400 mt-0.5">Awaiting seller approval (within 48 hours)</p></div></div>
      <div className="flex flex-wrap gap-2 items-start"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</button>
      <button className="btn btn-sm btn-danger"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Withdraw</button>
      
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Contact support</button></div></div>
      <div className="px-4 pb-4"><div className="flex flex-wrap gap-6 p-3 rounded-xl bg-ink-50"><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Requested</p><p className="text-[12.5px] font-bold">12 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Approved</p><p className="text-[12.5px] font-bold">—</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Picked up</p><p className="text-[12.5px] font-bold">—</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Refunded</p><p className="text-[12.5px] font-bold">Expected 26 Aug</p></div></div></div></div><div className="card overflow-hidden">
      <div className="flex flex-wrap items-center gap-3 px-4 py-3 bg-ink-50 border-b border-[#e7e9ef]">
      <span className="text-[12.5px] font-extrabold">RTN-4655</span><span className="st st-hold">Refunded</span><span className="text-[12px] text-ink-500">Requested 2 Jul 2026</span>
      <div className="ml-auto flex items-center gap-2"><span className="text-[12px] text-ink-500">Refund amount</span><b className="text-[15px] text-brand-600">৳850</b></div></div>
      <div className="p-4 flex flex-wrap gap-4">
      <div className="flex gap-3 flex-1 min-w-[240px]"><span className="ph ph-c w-16 h-16 rounded-xl shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13.5px] font-bold clamp-1">Leather Wallet — Black</p><p className="text-[12px] text-ink-500">Sold by Dhaka Leather Co.</p>
      <p className="text-[12px] text-ink-600 mt-1"><b>Reason:</b> Changed my mind</p><p className="text-[12px] text-ink-400 mt-0.5">Refunded to wallet on 6 Jul</p></div></div>
      <div className="flex flex-wrap gap-2 items-start"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</button>
      
      
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Contact support</button></div></div>
      <div className="px-4 pb-4"><div className="flex flex-wrap gap-6 p-3 rounded-xl bg-ink-50"><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Requested</p><p className="text-[12.5px] font-bold">2 Jul 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Approved</p><p className="text-[12.5px] font-bold">17 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Picked up</p><p className="text-[12.5px] font-bold">19 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Refunded</p><p className="text-[12.5px] font-bold">22 Aug 2026</p></div></div></div></div><div className="card overflow-hidden">
      <div className="flex flex-wrap items-center gap-3 px-4 py-3 bg-ink-50 border-b border-[#e7e9ef]">
      <span className="text-[12.5px] font-extrabold">RTN-4520</span><span className="st st-done">Approved</span><span className="text-[12px] text-ink-500">Requested 15 Aug 2026</span>
      <div className="ml-auto flex items-center gap-2"><span className="text-[12px] text-ink-500">Refund amount</span><b className="text-[15px] text-brand-600">৳450</b></div></div>
      <div className="p-4 flex flex-wrap gap-4">
      <div className="flex gap-3 flex-1 min-w-[240px]"><span className="ph ph-d w-16 h-16 rounded-xl shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13.5px] font-bold clamp-1">Cotton T-Shirt — Blue (M)</p><p className="text-[12px] text-ink-500">Sold by Aarong Style</p>
      <p className="text-[12px] text-ink-600 mt-1"><b>Reason:</b> Size too small — need exchange for L</p><p className="text-[12px] text-ink-400 mt-0.5">Pickup scheduled for 18 Aug, 11 AM – 5 PM</p></div></div>
      <div className="flex flex-wrap gap-2 items-start"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</button>
      
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>Reschedule pickup</button>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Contact support</button></div></div>
      <div className="px-4 pb-4"><div className="flex flex-wrap gap-6 p-3 rounded-xl bg-ink-50"><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Requested</p><p className="text-[12.5px] font-bold">15 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Approved</p><p className="text-[12.5px] font-bold">17 Aug 2026</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Picked up</p><p className="text-[12.5px] font-bold">—</p></div><div><p className="text-[10.5px] font-extrabold uppercase tracking-wider text-ink-400">Refunded</p><p className="text-[12.5px] font-bold">Expected 26 Aug</p></div></div></div></div></div>
      
      <h2 className="text-[16px] font-extrabold mt-6 mb-3">Cancelled orders</h2>
      <div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Order</th><th>Product</th><th>Amount</th><th>Cancelled by</th><th>Reason</th><th>Refund status</th><th></th></tr></thead>
      <tbody><tr><td><b>HB-883620</b><p className="text-[11.5px] text-ink-400">2 Aug 2026</p></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Power Bank 50,000mAh</p><p className="text-[11.5px] text-ink-400">Gadget Hub BD</p></div></div></td><td>৳1,100</td><td>You</td><td>Ordered by mistake</td><td><span className="st st-hold">Refunded</span></td><td><button className="btn btn-xs btn-outline">Details</button></td></tr><tr><td><b>HB-883180</b><p className="text-[11.5px] text-ink-400">18 Jul 2026</p></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-f w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V9.5l8-6 8 6V20"/><path d="M9.5 20v-6h5v6"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Ceramic Vase Set</p><p className="text-[11.5px] text-ink-400">Home Decor BD</p></div></div></td><td>৳780</td><td>Seller</td><td>Out of stock</td><td><span className="st st-hold">Refunded</span></td><td><button className="btn btn-xs btn-outline">Details</button></td></tr></tbody></table></div></div>
      
      <div className="card mt-4"><div className="card-head"><h3>Return policy at a glance</h3><div className="flex items-center gap-2"></div></div><div className="p-5 grid sm:grid-cols-3 gap-4"><div className="flex gap-3"><span className="w-10 h-10 rounded-xl bg-service-50 text-service-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      <div><p className="text-[13px] font-extrabold mb-0.5">7-day window</p><p className="text-[12px] text-ink-500">Request a return within 7 days of delivery for most categories.</p></div></div><div className="flex gap-3"><span className="w-10 h-10 rounded-xl bg-service-50 text-service-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7h11v8H3zM14 10h4l3 3v2h-7z"/><circle cx="6.5" cy="17.5" r="1.5"/><circle cx="17.5" cy="17.5" r="1.5"/></svg></span>
      <div><p className="text-[13px] font-extrabold mb-0.5">Free pickup</p><p className="text-[12px] text-ink-500">We collect the parcel from your address within 48 hours.</p></div></div><div className="flex gap-3"><span className="w-10 h-10 rounded-xl bg-service-50 text-service-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <div><p className="text-[13px] font-extrabold mb-0.5">Fast refunds</p><p className="text-[12px] text-ink-500">Money back in 3–7 working days, or instantly to your wallet.</p></div></div>
      <a href="/return-policy" className="link text-[12.5px] sm:col-span-3">Read the full return &amp; refund policy →</a></div></div>
      
      <div className="modal" id="return-modal"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel">
      <div className="card-head"><h3>Request a return or exchange</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5">
      <label className="label">Select order <span className="req">*</span></label>
      <select className="select mb-3"><option>HB-884109 — Cotton Panjabi (Delivered 11 Aug)</option><option>HB-883942 — Organic Honey 500g (Delivered 8 Aug)</option><option>HB-883311 — 24 inch LED Monitor (Delivered 19 Jul)</option></select>
      <label className="label">Select item(s) <span className="req">*</span></label>
      <div className="space-y-2 mb-3"><label className="flex items-center gap-3 p-3 rounded-xl border border-[#e7e9ef] cursor-pointer"><input type="checkbox" defaultChecked className="w-[18px] h-[18px]" style={{accentColor: "#ff2525"}} /><span className="ph ph-a w-11 h-11 rounded-lg"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="M8 3 4 6l2 3 1-1v13h10V8l1 1 2-3-4-3-4 2z"/></svg></span>
      <span className="flex-1 min-w-0"><span className="block text-[13px] font-bold">Cotton Panjabi — Navy Blue (L)</span><span className="block text-[12px] text-ink-500">৳1,850 · Qty 1</span></span>
      <select className="select input-sm !w-[74px]"><option>Qty 1</option></select></label></div>
      <div className="grid sm:grid-cols-2 gap-3 mb-3">
      <div><label className="label">Request type <span className="req">*</span></label><select className="select"><option>Return &amp; refund</option><option>Exchange for another size</option><option>Exchange for another colour</option><option>Repair under warranty</option></select></div>
      <div><label className="label">Reason <span className="req">*</span></label><select className="select"><option>Item damaged or broken</option><option>Wrong item received</option><option>Item defective / not working</option><option>Different from description</option><option>Size or fit issue</option><option>Missing parts or accessories</option><option>Changed my mind</option></select></div></div>
      <label className="label">Describe the issue <span className="req">*</span></label><textarea className="textarea !min-h-[90px] mb-3" placeholder="Tell us what went wrong so we can resolve it faster…"></textarea>
      <label className="label">Upload photos <span className="req">*</span></label><div className="upload-box mb-3"><svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h3l2-2h6l2 2h3v12H4z"/><circle cx="12" cy="14" r="3.2"/></svg><span>Add clear photos of the item and packaging (up to 5 files)</span></div>
      <div className="grid sm:grid-cols-2 gap-3 mb-3">
      <div><label className="label">Preferred pickup date</label><input type="date" className="input" /></div>
      <div><label className="label">Refund destination</label><select className="select"><option>Original payment method (bKash)</option><option>HaatBazar wallet (instant)</option><option>Bank account transfer</option></select></div></div>
      <label className="label">Pickup address</label><select className="select mb-3"><option>Home — House 42, Road 8, Banani, Dhaka 1213</option><option>Office — Level 5, Gulshan 1, Dhaka 1212</option></select>
      <label className="check mb-4"><input type="checkbox" defaultChecked />I confirm the item is unused, in original packaging with all accessories.</label>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Return request submitted — RTN-4835">Submit request</button></div></div></div></div>
    </>
  );
}
