export default function SupportPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/user/dashboard">My Account</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Account</span><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Support</span></nav>
      <h1>Support Tickets</h1><p>Raise an issue and track responses from the HaatBazar care team.</p></div>
      <div className="flex flex-wrap items-center gap-2"><a href="/help-center" className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Help centre</a><button className="btn btn-sm btn-primary" data-modal-open="ticket"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>New ticket</button></div></div>
      
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 8a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2 2 2 0 0 0 0 4v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4a2 2 0 0 0 0-4z"/><path d="M12 7v10"/></svg></span>
      </div>
      <p className="val">9</p><p className="lbl">Total tickets</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">2</p><p className="lbl">Open</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>
      </div>
      <p className="val">7</p><p className="lbl">Resolved</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg></span>
      </div>
      <p className="val">38 min</p><p className="lbl">Avg first response</p></div></div>
      <div className="grid lg:grid-cols-[minmax(0,1fr)_320px] gap-4">
      <div>
      <div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All tickets<span className="count">9</span></button><button className="tab " data-tab="t1">Open<span className="count">2</span></button><button className="tab " data-tab="t2">Awaiting my reply<span className="count">1</span></button><button className="tab " data-tab="t3">Resolved<span className="count">7</span></button><button className="tab " data-tab="t4">Closed<span className="count">0</span></button></div>
      <div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Order issue</option><option>Payment</option><option>Refund</option><option>Delivery</option><option>Product quality</option><option>Service booking</option><option>Account</option></select><select className="select input-sm !w-auto"><option>All priorities</option><option>Urgent</option><option>High</option><option>Normal</option><option>Low</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div>
      <div className="space-y-3"><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9921</span><span className="st st-new">Open</span>
      <span className="badge badge-amber">High priority</span>
      <span className="badge badge-gray">Refund</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated 2 hours ago</span></div>
      <p className="text-[14px] font-extrabold mb-1">Refund not received for cancelled order</p>
      <p className="text-[12.5px] text-ink-500 mb-3">Related to <b>HB-883620</b> · 3 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Reply</button><button className="btn btn-xs btn-outline">Escalate</button><button className="btn btn-xs btn-ghost">Close ticket</button></div></div><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9902</span><span className="st st-new">Open</span>
      <span className="badge badge-red">Urgent priority</span>
      <span className="badge badge-gray">Order issue</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated Yesterday</span></div>
      <p className="text-[14px] font-extrabold mb-1">Wrong item delivered — need replacement</p>
      <p className="text-[12.5px] text-ink-500 mb-3">Related to <b>HB-883771</b> · 5 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Reply</button><button className="btn btn-xs btn-outline">Escalate</button><button className="btn btn-xs btn-ghost">Close ticket</button></div></div><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9871</span><span className="st st-done">Resolved</span>
      <span className="badge badge-gray">Normal priority</span>
      <span className="badge badge-gray">Service booking</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated 6 Aug 2026</span></div>
      <p className="text-[14px] font-extrabold mb-1">Service provider did not arrive on time</p>
      <p className="text-[12.5px] text-ink-500 mb-3">Related to <b>BKG-2612</b> · 4 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reopen</button><button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Rate support</button></div></div><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9840</span><span className="st st-done">Resolved</span>
      <span className="badge badge-gray">Normal priority</span>
      <span className="badge badge-gray">Payment</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated 28 Jul 2026</span></div>
      <p className="text-[14px] font-extrabold mb-1">Unable to apply voucher at checkout</p>
      <p className="text-[12.5px] text-ink-500 mb-3">2 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reopen</button><button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Rate support</button></div></div><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9812</span><span className="st st-done">Resolved</span>
      <span className="badge badge-gray">Low priority</span>
      <span className="badge badge-gray">Product quality</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated 19 Jul 2026</span></div>
      <p className="text-[14px] font-extrabold mb-1">Product quality below expectation</p>
      <p className="text-[12.5px] text-ink-500 mb-3">Related to <b>HB-883402</b> · 6 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reopen</button><button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Rate support</button></div></div><div className="card p-4">
      <div className="flex flex-wrap items-center gap-2 mb-2"><span className="text-[12.5px] font-extrabold">TKT-9788</span><span className="st st-done">Resolved</span>
      <span className="badge badge-gray">Normal priority</span>
      <span className="badge badge-gray">Account</span><span className="text-[11.5px] text-ink-400 ml-auto">Updated 2 Jul 2026</span></div>
      <p className="text-[14px] font-extrabold mb-1">Change registered mobile number</p>
      <p className="text-[12.5px] text-ink-500 mb-3">3 replies · Assigned to Care Team</p>
      <div className="flex flex-wrap gap-2"><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View conversation</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reopen</button><button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 2 2.9 6.3 6.8.7-5 4.6 1.4 6.7L12 17l-6.1 3.3L7.3 13.6l-5-4.6 6.8-.7z"/></svg>Rate support</button></div></div></div>
      <div className="card mt-3"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–6</b> of <b>9</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>1</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div>
      </div>
      <aside className="space-y-4">
      <div className="card "><div className="card-head"><h3>Contact us directly</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-2.5"><div className="flex gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] hover:border-brand-200">
      <span className="w-9 h-9 rounded-lg bg-brand-50 text-brand-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg></span>
      <div><p className="text-[12.5px] font-bold">Call 16247</p><p className="text-[11.5px] text-ink-400">24/7 hotline · toll free</p></div></div><div className="flex gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] hover:border-brand-200">
      <span className="w-9 h-9 rounded-lg bg-brand-50 text-brand-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg></span>
      <div><p className="text-[12.5px] font-bold">Live chat</p><p className="text-[11.5px] text-ink-400">Avg wait 2 minutes</p></div></div><div className="flex gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] hover:border-brand-200">
      <span className="w-9 h-9 rounded-lg bg-brand-50 text-brand-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg></span>
      <div><p className="text-[12.5px] font-bold">support@haatbazar.com.bd</p><p className="text-[11.5px] text-ink-400">Reply within 12 hours</p></div></div><div className="flex gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] hover:border-brand-200">
      <span className="w-9 h-9 rounded-lg bg-brand-50 text-brand-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg></span>
      <div><p className="text-[12.5px] font-bold">WhatsApp 01700-000000</p><p className="text-[11.5px] text-ink-400">9 AM – 11 PM daily</p></div></div></div></div>
      <div className="card "><div className="card-head"><h3>Popular help topics</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-1"><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>How do I track my order?</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>How long do refunds take?</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>How to return a product</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Change delivery address after ordering</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Cancel a service booking</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Voucher not working at checkout</a><a href="/help-center" className="dd-item !text-[12.5px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Report a fake or damaged product</a></div></div>
      <div className="card "><div className="card-head"><h3>Response time</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="space-y-3"><div><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">Urgent</span><span className="text-ink-400">15 min</span></div><div className="bar"><i style={{width: "95%", background: "#12a594"}}></i></div></div><div><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">High</span><span className="text-ink-400">30 min</span></div><div className="bar"><i style={{width: "88%", background: "#12a594"}}></i></div></div><div><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">Normal</span><span className="text-ink-400">2 hours</span></div><div className="bar"><i style={{width: "76%", background: "#12a594"}}></i></div></div><div><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">Low</span><span className="text-ink-400">12 hours</span></div><div className="bar"><i style={{width: "64%", background: "#12a594"}}></i></div></div></div></div></div>
      </aside></div>
      
      <div className="modal" id="ticket"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel">
      <div className="card-head"><h3>Create a support ticket</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="grid sm:grid-cols-2 gap-3 mb-3">
      <div><label className="label">Issue category <span className="req">*</span></label><select className="select"><option>Order issue</option><option>Delivery problem</option><option>Payment &amp; billing</option><option>Refund &amp; return</option><option>Product quality</option><option>Service booking</option><option>Seller / provider behaviour</option><option>Account &amp; login</option><option>Voucher &amp; rewards</option><option>Other</option></select></div>
      <div><label className="label">Priority</label><select className="select"><option>Normal</option><option>High</option><option>Urgent</option><option>Low</option></select></div>
      <div><label className="label">Related order / booking</label><select className="select"><option>None</option><option>HB-884213 — Realme C100X</option><option>HB-883771 — Wooden Bookshelf</option><option>BKG-2841 — AC Servicing</option></select></div>
      <div><label className="label">Preferred contact method</label><select className="select"><option>Email</option><option>Phone call</option><option>SMS</option><option>In-app chat</option></select></div></div>
      <label className="label">Subject <span className="req">*</span></label><input className="input mb-3" placeholder="Briefly describe the issue" />
      <label className="label">Description <span className="req">*</span></label><textarea className="textarea !min-h-[120px] mb-3" placeholder="Include order number, dates and what you have already tried…"></textarea>
      <label className="label">Attachments</label><div className="upload-box mb-4"><svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h3l2-2h6l2 2h3v12H4z"/><circle cx="12" cy="14" r="3.2"/></svg><span>Screenshots or photos help us resolve faster (max 5 files, 10 MB each)</span></div>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Ticket TKT-9945 created">Submit ticket</button></div></div></div></div>
    </>
  );
}
