export default function WalletPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/user/dashboard">My Account</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Payments</span><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Wallet</span></nav>
      <h1>Wallet &amp; Payments</h1><p>Your HaatBazar balance, saved payment methods and refund history.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Statement</button><button className="btn btn-sm btn-primary" data-modal-open="topup"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add money</button></div></div>
      
      <div className="grid lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)] gap-3.5 mb-4">
      <div className="card p-5 bg-gradient-to-br from-brand-600 to-brand-800 text-white relative overflow-hidden">
      <div className="absolute -right-8 -bottom-10 w-40 h-40 rounded-full bg-white/10"></div>
      <p className="text-[12.5px] text-white/70 mb-1">Available balance</p>
      <p className="text-[32px] font-extrabold tracking-tight mb-1">৳2,480.00</p>
      <p className="text-[12px] text-white/70 mb-4">Usable on any product or service payment</p>
      <div className="flex gap-2 relative z-10"><button className="btn btn-sm !bg-white !text-brand-700" data-modal-open="topup">Add money</button><button className="btn btn-sm !bg-white/15 !text-white" data-modal-open="withdraw">Withdraw</button></div></div>
      <div className="card p-5"><p className="text-[12.5px] text-ink-500 mb-1">HaatBazar points</p>
      <p className="text-[32px] font-extrabold tracking-tight text-gold-600 mb-1">2,480</p>
      <p className="text-[12px] text-ink-400 mb-3">100 points = ৳10 discount at checkout</p>
      <div className="bar mb-1"><i style={{width: "64%"}}></i></div><p className="text-[11.5px] text-ink-400 mb-3">3,520 more points for Platinum tier</p>
      <a href="/user/vouchers" className="btn btn-sm btn-outline btn-block">Redeem points</a></div>
      <div className="card p-5"><p className="text-[12.5px] text-ink-500 mb-1">Pending refunds</p>
      <p className="text-[32px] font-extrabold tracking-tight mb-1">৳2,950</p>
      <p className="text-[12px] text-ink-400 mb-3">1 refund is being processed</p>
      <div className="p-2.5 rounded-lg bg-ink-50 text-[12px] text-ink-600 mb-3">RTN-4790 · Expected by 26 Aug 2026</div>
      <a href="/user/returns" className="btn btn-sm btn-outline btn-block">Track refunds</a></div></div>
      
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+18%</span></div>
      <p className="val">৳1,84,320</p><p className="lbl">Total spent (12 mo)</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12 12 3h8v8l-9 9z"/><circle cx="16" cy="8" r="1.5"/></svg></span>
      </div>
      <p className="val">৳12,480</p><p className="lbl">Total saved</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M3 12h18M12 8v13"/><path d="M8 8a2.5 2.5 0 1 1 4-2 2.5 2.5 0 1 1 4 2"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+৳420</span></div>
      <p className="val">৳3,240</p><p className="lbl">Cashback earned</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg></span>
      </div>
      <p className="val">186</p><p className="lbl">Transactions</p></div></div>
      
      <div className="grid lg:grid-cols-[minmax(0,1fr)_360px] gap-4">
      <div className="space-y-4">
      <div className="card "><div className="card-head"><h3>Transaction history</h3><div className="flex items-center gap-2"><div className="flex gap-2"><input type="month" className="input input-sm !w-auto" /><button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>CSV</button></div></div></div><div className="tabs px-4 pt-1 mb-4" data-tabs><button className="tab is-active" data-tab="t0">All<span className="count">186</span></button><button className="tab " data-tab="t1">Payments<span className="count">142</span></button><button className="tab " data-tab="t2">Refunds<span className="count">18</span></button><button className="tab " data-tab="t3">Top-ups<span className="count">20</span></button><button className="tab " data-tab="t4">Cashback<span className="count">6</span></button></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Date</th><th>Description</th><th>Method</th><th>Type</th><th className="num">Amount</th><th>Status</th></tr></thead>
      <tbody><tr><td>15 Aug 2026<p className="text-[11px] text-ink-400">10:24 AM</p></td><td><b>Order HB-884213</b><p className="text-[11.5px] text-ink-400">Realme C100X + 1 item</p></td><td>bKash</td><td><span className="badge badge-gray">Payment</span></td><td><b className="text-brand-600">-৳11,290</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>12 Aug 2026<p className="text-[11px] text-ink-400">6:02 PM</p></td><td><b>Wallet top-up</b><p className="text-[11.5px] text-ink-400">Self top-up</p></td><td>Nagad</td><td><span className="badge badge-green">Top-up</span></td><td><b className="text-green-600">+৳2,000</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>11 Aug 2026<p className="text-[11px] text-ink-400">1:11 PM</p></td><td><b>Order HB-884109</b><p className="text-[11.5px] text-ink-400">Cotton Panjabi</p></td><td>Wallet</td><td><span className="badge badge-gray">Payment</span></td><td><b className="text-brand-600">-৳1,850</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>6 Aug 2026<p className="text-[11px] text-ink-400">9:40 AM</p></td><td><b>Refund RTN-4821</b><p className="text-[11.5px] text-ink-400">Smart Watch return</p></td><td>bKash</td><td><span className="badge badge-blue">Refund</span></td><td><b className="text-green-600">+৳2,300</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>2 Aug 2026<p className="text-[11px] text-ink-400">4:15 PM</p></td><td><b>Booking BKG-2790</b><p className="text-[11.5px] text-ink-400">Electrical wiring repair</p></td><td>Cash</td><td><span className="badge badge-teal">Service</span></td><td><b className="text-brand-600">-৳900</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>28 Jul 2026<p className="text-[11px] text-ink-400">11:02 AM</p></td><td><b>Cashback — Eid campaign</b><p className="text-[11.5px] text-ink-400">5% on electronics</p></td><td>Wallet</td><td><span className="badge badge-amber">Cashback</span></td><td><b className="text-green-600">+৳420</b></td><td><span className="st st-done">Completed</span></td></tr><tr><td>24 Jul 2026<p className="text-[11px] text-ink-400">8:33 PM</p></td><td><b>Order HB-883402</b><p className="text-[11.5px] text-ink-400">Smart Watch — Fitness Pro</p></td><td>Card ••4821</td><td><span className="badge badge-gray">Payment</span></td><td><b className="text-brand-600">-৳2,300</b></td><td><span className="st st-hold">Refunded</span></td></tr><tr><td>19 Jul 2026<p className="text-[11px] text-ink-400">3:20 PM</p></td><td><b>Order HB-883311</b><p className="text-[11.5px] text-ink-400">24 inch LED Monitor</p></td><td>bKash</td><td><span className="badge badge-gray">Payment</span></td><td><b className="text-brand-600">-৳9,900</b></td><td><span className="st st-done">Completed</span></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–8</b> of <b>186</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>19</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div>
      <div className="card "><div className="card-head"><h3>Monthly spending</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><svg viewBox="0 0 640 160" className="w-full" style={{height: "160px"}} preserveAspectRatio="none">
      <defs><linearGradient id="g12a594" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#12a594" stop-opacity=".24"/><stop offset="100%" stop-color="#12a594" stop-opacity="0"/></linearGradient></defs>
      <line x1="0" y1="8" x2="640" y2="8" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="48" x2="640" y2="48" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="88" x2="640" y2="88" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="128" x2="640" y2="128" stroke="#eceef2" strokeWidth="1"/>
      <polygon points="0,160 0,104.92307692307693 91.42857142857143,89.23076923076923 182.85714285714286,97.07692307692307 274.2857142857143,68.3076923076923 365.7142857142857,78.76923076923077 457.14285714285717,44.769230769230774 548.5714285714286,57.846153846153854 640,16 640,160" fill="url(#g12a594)"/>
      <polyline points="0,104.92307692307693 91.42857142857143,89.23076923076923 182.85714285714286,97.07692307692307 274.2857142857143,68.3076923076923 365.7142857142857,78.76923076923077 457.14285714285717,44.769230769230774 548.5714285714286,57.846153846153854 640,16" fill="none" stroke="#12a594" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>
      <circle cx="0" cy="104.92307692307693" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="91.42857142857143" cy="89.23076923076923" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="182.85714285714286" cy="97.07692307692307" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="274.2857142857143" cy="68.3076923076923" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="365.7142857142857" cy="78.76923076923077" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="457.14285714285717" cy="44.769230769230774" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="548.5714285714286" cy="57.846153846153854" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/><circle cx="640" cy="16" r="3" fill="#fff" stroke="#12a594" strokeWidth="2"/></svg>
      <div className="flex justify-between mt-2 text-[11px] text-ink-400"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></div></div>
      </div>
      <aside className="space-y-4">
      <div className="card "><div className="card-head"><h3>Saved payment methods</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-2.5"><div className="flex items-center gap-3 p-3 rounded-xl border border-[#e7e9ef]">
      <span className="w-10 h-10 rounded-lg bg-ink-50 text-ink-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M16 12h2"/></svg></span>
      <div className="min-w-0 flex-1"><p className="text-[13px] font-bold">bKash <span className="badge badge-brand ml-1">Default</span></p><p className="text-[11.5px] text-ink-400">01712xxxx78</p></div>
      <div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove</a></div></div></div><div className="flex items-center gap-3 p-3 rounded-xl border border-[#e7e9ef]">
      <span className="w-10 h-10 rounded-lg bg-ink-50 text-ink-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M16 12h2"/></svg></span>
      <div className="min-w-0 flex-1"><p className="text-[13px] font-bold">Nagad </p><p className="text-[11.5px] text-ink-400">01712xxxx78</p></div>
      <div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove</a></div></div></div><div className="flex items-center gap-3 p-3 rounded-xl border border-[#e7e9ef]">
      <span className="w-10 h-10 rounded-lg bg-ink-50 text-ink-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <div className="min-w-0 flex-1"><p className="text-[13px] font-bold">Visa Debit </p><p className="text-[11.5px] text-ink-400">•••• •••• •••• 4821</p></div>
      <div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove</a></div></div></div><div className="flex items-center gap-3 p-3 rounded-xl border border-[#e7e9ef]">
      <span className="w-10 h-10 rounded-lg bg-ink-50 text-ink-600 grid place-items-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <div className="min-w-0 flex-1"><p className="text-[13px] font-bold">City Bank Card </p><p className="text-[11.5px] text-ink-400">•••• •••• •••• 9032</p></div>
      <div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Set as default</a><a className="dd-item " ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item is-danger" ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove</a></div></div></div>
      <button className="btn btn-sm btn-outline btn-block" data-modal-open="addpay"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add payment method</button></div></div>
      <div className="card "><div className="card-head"><h3>Auto-pay &amp; preferences</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-3"><label className="flex items-center justify-between gap-3"><span className="text-[12.5px] text-ink-700 pr-2">Use wallet balance first at checkout</span><span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3"><span className="text-[12.5px] text-ink-700 pr-2">Auto-refund to wallet (instant)</span><span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3"><span className="text-[12.5px] text-ink-700 pr-2">Save cards for faster checkout</span><span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label><label className="flex items-center justify-between gap-3"><span className="text-[12.5px] text-ink-700 pr-2">Require OTP above ৳10,000</span><span className="switch"><input type="checkbox" defaultChecked /><span className="track"></span></span></label></div></div>
      <div className="card "><div className="card-head"><h3>Accepted payment partners</h3><div className="flex items-center gap-2"></div></div><div className="p-4 flex flex-wrap gap-2"><span className="badge badge-gray">bKash</span><span className="badge badge-gray">Nagad</span><span className="badge badge-gray">Rocket</span><span className="badge badge-gray">Upay</span><span className="badge badge-gray">Visa</span><span className="badge badge-gray">Mastercard</span><span className="badge badge-gray">AmEx</span><span className="badge badge-gray">SSLCommerz</span><span className="badge badge-gray">COD</span><span className="badge badge-gray">EMI</span></div></div>
      </aside></div>
      
      <div className="modal" id="topup"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel is-narrow">
      <div className="card-head"><h3>Add money to wallet</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><label className="label">Amount (৳) <span className="req">*</span></label><input className="input mb-2" placeholder="0.00" />
      <div className="flex flex-wrap gap-2 mb-3"><button className="chip">৳500</button><button className="chip">৳1,000</button><button className="chip">৳2,000</button><button className="chip">৳5,000</button></div>
      <label className="label">Pay with <span className="req">*</span></label>
      <div className="space-y-2 mb-4"><label className="check p-3 rounded-xl border border-[#e7e9ef]"><input type="radio" name="pm" defaultChecked />bKash — 01712xxxx78</label><label className="check p-3 rounded-xl border border-[#e7e9ef]"><input type="radio" name="pm"  />Nagad — 01712xxxx78</label><label className="check p-3 rounded-xl border border-[#e7e9ef]"><input type="radio" name="pm"  />Visa Debit •••• 4821</label><label className="check p-3 rounded-xl border border-[#e7e9ef]"><input type="radio" name="pm"  />Internet banking</label></div>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Wallet topped up successfully">Proceed to pay</button></div></div></div></div>
      
      <div className="modal" id="withdraw"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel is-narrow">
      <div className="card-head"><h3>Withdraw balance</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><p className="text-[12.5px] text-ink-500 mb-3">Available: <b className="text-ink-900">৳2,480.00</b> · Minimum withdrawal ৳200</p>
      <label className="label">Amount (৳) <span className="req">*</span></label><input className="input mb-3" placeholder="0.00" />
      <label className="label">Withdraw to <span className="req">*</span></label><select className="select mb-3"><option>bKash — 01712xxxx78</option><option>Nagad — 01712xxxx78</option><option>Bank account — City Bank ••9032</option></select>
      <div className="p-3 rounded-xl bg-ink-50 text-[12px] text-ink-600 mb-4">Withdrawals are processed within 1–3 working days. A ৳10 processing fee applies to mobile wallets.</div>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Withdrawal request submitted">Request withdrawal</button></div></div></div></div>
      
      <div className="modal" id="addpay"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel is-narrow">
      <div className="card-head"><h3>Add payment method</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="tabs mb-4" data-tabs><button className="tab is-active" data-tab="c">Card</button><button className="tab" data-tab="m">Mobile wallet</button><button className="tab" data-tab="b">Bank</button></div>
      <label className="label">Card number <span className="req">*</span></label><input className="input mb-3" placeholder="1234 5678 9012 3456" />
      <div className="grid grid-cols-2 gap-3 mb-3"><div><label className="label">Expiry <span className="req">*</span></label><input className="input" placeholder="MM / YY" /></div>
      <div><label className="label">CVV <span className="req">*</span></label><input className="input" placeholder="•••" /></div></div>
      <label className="label">Name on card <span className="req">*</span></label><input className="input mb-3" placeholder="NUSRAT JAHAN" />
      <label className="check mb-4"><input type="checkbox" defaultChecked />Save this card securely for future payments</label>
      <div className="flex gap-2"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Payment method added">Save method</button></div></div></div></div>
    </>
  );
}
