export default function ActivityPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Audit log</span></nav>
      <h1>Audit Log</h1><p>Every action taken by admins, staff, vendors and the system — immutable and searchable.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Retention policy</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export log</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Suspicious activity</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+8%</span></div>
      <p className="val">48,620</p><p className="lbl">Events today</p><p className="text-[11.5px] text-ink-400 mt-1.5">842 by staff</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="14" r="4"/><path d="m11 11 8-8 3 3-2 2 2 2-3 3-2-2-2 2"/></svg></span>
      </div>
      <p className="val">18,420</p><p className="lbl">Admin actions (30d)</p><p className="text-[11.5px] text-ink-400 mt-1.5">24 staff members</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      </div>
      <p className="val">186</p><p className="lbl">Critical actions</p><p className="text-[11.5px] text-ink-400 mt-1.5">Refunds, bans, settings</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg></span>
      </div>
      <p className="val">42</p><p className="lbl">Failed permission attempts</p><p className="text-[11.5px] text-ink-400 mt-1.5">Review needed</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All events<span className="count">48,620</span></button><button className="tab " data-tab="t1">Admin & staff<span className="count">18,420</span></button><button className="tab " data-tab="t2">Vendor actions<span className="count">24,800</span></button><button className="tab " data-tab="t3">Customer actions<span className="count">4,862</span></button><button className="tab " data-tab="t4">System / automated<span className="count">842</span></button><button className="tab " data-tab="t5">Critical<span className="count">186</span></button><button className="tab " data-tab="t6">Failed / denied<span className="count">42</span></button><button className="tab " data-tab="t7">Login history<span className="count">8,420</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>Actor: All</option><option>Admin</option><option>Staff</option><option>Vendor</option><option>Customer</option><option>System</option><option>API</option></select><select className="select input-sm !w-auto"><option>Action: All</option><option>Create</option><option>Update</option><option>Delete</option><option>Approve</option><option>Reject</option><option>Suspend</option><option>Refund</option><option>Payout</option><option>Login</option><option>Export</option><option>Settings change</option><option>Permission change</option></select><select className="select input-sm !w-auto"><option>Module: All</option><option>Products</option><option>Services</option><option>Orders</option><option>Bookings</option><option>Vendors</option><option>Customers</option><option>Finance</option><option>Marketing</option><option>Content</option><option>Settings</option><option>Staff</option></select><select className="select input-sm !w-auto"><option>Severity: All</option><option>Critical</option><option>High</option><option>Normal</option><option>Info</option></select><input type="date" className="input input-sm !w-auto" />
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Export selected</button><button className="btn btn-xs btn-outline">Flag for review</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Timestamp</th><th>Actor</th><th>Role</th><th>Action</th><th>Module</th><th>Target</th><th>Before → After</th><th>IP address</th><th>Device</th><th>Severity</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><b>23 Aug 2026, 4:02 PM</b><p className="text-[11px] text-ink-400">2 min ago</p></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Aminul Islam</p><p className="text-[11.5px] text-ink-400">admin@niko.com.bd</p></div></div></td><td><span className="badge badge-red">Super Admin</span></td><td><b>Refund issued</b></td><td>Orders</td><td><a className="link">#NK-84219</a></td><td>৳0 → ৳23,480</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-red">Critical</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</a><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 7h12l1 14H5z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg>View order</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Flag for review</a></div></div></td></tr><tr><td><b>23 Aug 2026, 3:48 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Nafisa Karim</p><p className="text-[11.5px] text-ink-400">nafisa@niko.com.bd</p></div></div></td><td><span className="badge badge-blue">Support L2</span></td><td><b>Vendor suspended</b></td><td>Vendors</td><td><a className="link">Fake Store BD #VND-1442</a></td><td>Active → Suspended</td><td>103.120.x.x</td><td>Chrome / macOS</td><td><span className="badge badge-red">Critical</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</a><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h16v12H4z"/><path d="M9 8V4h6v4"/></svg>View vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reverse action</a></div></div></td></tr><tr><td><b>23 Aug 2026, 3:12 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Rashed Kabir</p><p className="text-[11.5px] text-ink-400">rashed@niko.com.bd</p></div></div></td><td><span className="badge badge-amber">Catalog Manager</span></td><td><b>Commission plan updated</b></td><td>Finance</td><td>Electronics — standard plan</td><td>10% → 12%</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-amber">High</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m8 8-4 4 4 4M16 8l4 4-4 4M14 5l-4 14"/></svg>View diff</a><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 19 14-14"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/></svg>View plan</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Revert</a></div></div></td></tr><tr><td><b>23 Aug 2026, 2:40 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Tania Rahman</p><p className="text-[11.5px] text-ink-400">tania@niko.com.bd</p></div></div></td><td><span className="badge badge-gold">Finance</span></td><td><b>Payout batch approved</b></td><td>Finance</td><td>Batch #PB-2026-34 · 842 vendors</td><td>৳0 → ৳4,86,20,000</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-red">Critical</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 10 12 4l9 6"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>View batch</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download advice</a></div></div></td></tr><tr><td><b>23 Aug 2026, 1:24 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Rahim Electric</p><p className="text-[11.5px] text-ink-400">Vendor #VND-1042</p></div></div></td><td><span className="badge badge-green">Vendor</span></td><td><b>Product price changed</b></td><td>Products</td><td>Realme C100X 6/128GB</td><td>৳12,490 → ৳11,290</td><td>45.62.x.x</td><td>Android app</td><td><span className="badge badge-gray">Normal</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 2h12l1 5H5z"/><path d="M5 7v15h14V7"/><path d="M9 12h6"/></svg>View product</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Price history</a></div></div></td></tr><tr><td><b>23 Aug 2026, 12:08 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-f w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Mehedi Hasan</p><p className="text-[11.5px] text-ink-400">mehedi@niko.com.bd</p></div></div></td><td><span className="badge badge-blue">Services</span></td><td><b>Listing approved</b></td><td>Services</td><td>AC Repair — Dhaka AC Service</td><td>Pending → Live</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-gray">Normal</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.5 4.5 19 9l-9 9H5v-5z"/><path d="M13 6l5 5"/></svg>View listing</a><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</a></div></div></td></tr><tr><td><b>23 Aug 2026, 11:42 AM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-g w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">System</p><p className="text-[11.5px] text-ink-400">Automated job</p></div></div></td><td><span className="badge badge-gray">System</span></td><td><b>Auto-cancelled unpaid orders</b></td><td>Orders</td><td>42 orders</td><td>Pending → Cancelled</td><td>internal</td><td>Cron worker</td><td><span className="badge badge-gray">Info</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>View list</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Job log</a></div></div></td></tr><tr><td><b>23 Aug 2026, 10:18 AM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-h w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Sabbir Ahmed</p><p className="text-[11.5px] text-ink-400">sabbir@niko.com.bd</p></div></div></td><td><span className="badge badge-blue">Support L1</span></td><td><b>Permission denied — payout access</b></td><td>Finance</td><td>Payout batch #PB-2026-34</td><td>—</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-amber">High</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="14" r="4"/><path d="m11 11 8-8 3 3-2 2 2 2-3 3-2-2-2 2"/></svg>Grant permission</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Flag</a></div></div></td></tr><tr><td><b>23 Aug 2026, 9:04 AM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-i w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Aminul Islam</p><p className="text-[11.5px] text-ink-400">admin@niko.com.bd</p></div></div></td><td><span className="badge badge-red">Super Admin</span></td><td><b>Platform settings changed</b></td><td>Settings</td><td>COD limit — verified customer</td><td>৳15,000 → ৳20,000</td><td>103.120.x.x</td><td>Chrome / Windows</td><td><span className="badge badge-red">Critical</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m8 8-4 4 4 4M16 8l4 4-4 4M14 5l-4 14"/></svg>View diff</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Revert</a></div></div></td></tr><tr><td><b>22 Aug 2026, 11:52 PM</b></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Unknown</p><p className="text-[11.5px] text-ink-400">admin@niko.com.bd attempt</p></div></div></td><td><span className="badge badge-red">Failed login</span></td><td><b>5 failed login attempts — locked</b></td><td>Security</td><td>Admin panel</td><td>—</td><td>188.42.x.x (Russia)</td><td>Unknown browser</td><td><span className="badge badge-red">Critical</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-log"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View details</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block IP</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="14" r="4"/><path d="m11 11 8-8 3 3-2 2 2 2-3 3-2-2-2 2"/></svg>Force password reset</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Security report</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–10</b> of <b>48620</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>4862</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Event detail</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Event ID</span><b className="text-right">EVT-2026-08-23-48620</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Timestamp</span><b className="text-right">23 Aug 2026, 4:02:18 PM (GMT+6)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Actor</span><b className="text-right">Aminul Islam (Super Admin)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Action</span><b className="text-right">Refund issued</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Module</span><b className="text-right">Orders → Refunds</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Target</span><b className="text-right">Order #NK-84219</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Amount</span><b className="text-right">৳23,480</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Reason</span><b className="text-right">Courier lost the parcel</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Approved by</span><b className="text-right">Self (super admin)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">IP address</span><b className="text-right">103.120.x.x — Dhaka, BD</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">User agent</span><b className="text-right">Chrome 141 / Windows 11</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Session ID</span><b className="text-right">ses_8842190x</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Request ID</span><b className="text-right">req_4820x8842</b></div></div>
      <div className="mt-3"><div className="sb-note bg-blue-50 text-blue-700 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg><span>Audit entries cannot be edited or deleted. They are retained for 24 months and archived for 7 years.</span></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download JSON</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>View related events</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Flag for compliance</button></div></div></div><div className="card "><div className="card-head"><h3>Most active staff (30d)</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Nafisa Karim</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "92%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">4,862 actions</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Rashed Kabir</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "78%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">3,842 actions</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Mehedi Hasan</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "64%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">2,480 actions</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Tania Rahman</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "52%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">1,842 actions</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Sabbir Ahmed</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "46%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">1,240 actions</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Aminul Islam</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "28%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">842 actions</span></div></div>
      <div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Total staff accounts</span><b className="text-right">24</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Active in last 7 days</span><b className="text-right">21</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Never logged in</span><b className="text-right">2</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Critical actions this month</span><b className="text-right">186</b></div></div></div></div><div className="card "><div className="card-head"><h3>Retention & compliance</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Hot retention (searchable)</label><input type="text" className="input" placeholder="24 months" /></div><div className=""><label className="label">Archive retention</label><input type="text" className="input" placeholder="7 years" /></div><div className=""><label className="label">Export format</label><select className="select"><option>JSON</option><option>CSV</option><option>Both</option></select></div><div className=""><label className="label">Compliance contact</label><input type="text" className="input" placeholder="legal@niko.com.bd" /></div></div>
      <div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Log all admin actions</p><p className="fs">Cannot be disabled.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Log vendor panel actions</p><p className="fs">Product, price and order changes.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Log customer data access</p><p className="fs">Who viewed which customer profile.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Alert on critical actions</p><p className="fs">Email super admins immediately.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Require reason for refunds & bans</p><p className="fs">Force a note before the action completes.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Tamper-proof hashing</p><p className="fs">Chain each entry with a SHA-256 hash.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div></div>
      
      <div className="modal" id="m-log"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Log entry — ERR-88421</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Timestamp</span><span className="text-[12.5px] font-bold text-ink-800 text-right">22 Aug 2026, 11:04:22 +06</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Level</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-red">Error</span></span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Service</span><span className="text-[12.5px] font-bold text-ink-800 text-right">payment-worker (pod 4)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Event</span><span className="text-[12.5px] font-bold text-ink-800 text-right">bKash callback signature mismatch</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Order</span><span className="text-[12.5px] font-bold text-ink-800 text-right">#HB-884190</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Request ID</span><span className="text-[12.5px] font-bold text-ink-800 text-right">req_8842jhk21x</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Occurrences</span><span className="text-[12.5px] font-bold text-ink-800 text-right">4 in last hour</span></div></div>
      <div className="px-5 pb-4"><pre className="bg-ink-950 text-ink-100 text-[11.5px] p-3.5 rounded-xl overflow-auto thin-scroll">PaymentGatewayException: signature mismatch
        at BkashClient.verifyCallback (bkash.js:214)
        at PaymentWorker.handle (worker.js:88)
        payload: &#123; trxId: "8842JHK21", amount: 24540, sig: "a91f…" &#125;</pre></div>
      <div className="px-5 pb-3 flex flex-wrap gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Retry job</button><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Create incident</button><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download trace</button></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Marked resolved">Mark resolved</button></div></div></div>
    </>
  );
}
