export default function AttributesPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Attributes</span></nav>
      <h1>Attributes & Specifications</h1><p>Variant options, filters and specification templates used by listings.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Spec templates</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Import</button><button className="btn btn-sm btn-primary" data-modal-open="m-attr"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add attribute</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 6h10M18 6h2M4 12h4M12 12h8M4 18h10M18 18h2"/><circle cx="16" cy="6" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="16" cy="18" r="2"/></svg></span>
      </div>
      <p className="val">284</p><p className="lbl">Attributes</p><p className="text-[11.5px] text-ink-400 mt-1.5">Used across 482 categories</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/></svg></span>
      </div>
      <p className="val">48</p><p className="lbl">Variant attributes</p><p className="text-[11.5px] text-ink-400 mt-1.5">Colour, size, storage…</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg></span>
      </div>
      <p className="val">96</p><p className="lbl">Filterable</p><p className="text-[11.5px] text-ink-400 mt-1.5">Shown in listing sidebar</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg></span>
      </div>
      <p className="val">64</p><p className="lbl">Spec templates</p><p className="text-[11.5px] text-ink-400 mt-1.5">Per category</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All attributes<span className="count">284</span></button><button className="tab " data-tab="t1">Variant options<span className="count">48</span></button><button className="tab " data-tab="t2">Filters<span className="count">96</span></button><button className="tab " data-tab="t3">Specifications<span className="count">140</span></button><button className="tab " data-tab="t4">Unused<span className="count">12</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Electronics</option><option>Mobile</option><option>Fashion</option><option>Home</option></select><select className="select input-sm !w-auto"><option>All types</option><option>Dropdown</option><option>Multi-select</option><option>Colour swatch</option><option>Text</option><option>Number</option><option>Boolean</option></select><select className="select input-sm !w-auto"><option>Usage: All</option><option>Variant</option><option>Filter</option><option>Specification</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Make filterable</button><button className="btn btn-xs btn-outline">Make variant</button><button className="btn btn-xs btn-outline">Assign to category</button><button className="btn btn-xs btn-outline">Delete</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Attribute</th><th>Type</th><th>Values</th><th>Used in categories</th><th>Products using</th><th>Variant</th><th>Filterable</th><th>Required</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><b>Colour</b><p className="text-[11px] text-ink-400">colour</p></td><td>Colour swatch</td><td><span className="badge badge-gray">42 values</span></td><td>Fashion, Electronics, Mobile (+38)</td><td>2,84,600</td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/></svg>Assign categories</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></td></tr><tr><td><b>Size</b><p className="text-[11px] text-ink-400">size</p></td><td>Dropdown</td><td><span className="badge badge-gray">18 values</span></td><td>Fashion, Shoes, Kids (+12)</td><td>1,42,800</td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Size chart</a></div></div></td></tr><tr><td><b>Storage capacity</b><p className="text-[11px] text-ink-400">storage</p></td><td>Dropdown</td><td><span className="badge badge-gray">9 values</span></td><td>Mobile, Laptop, Tablet</td><td>18,420</td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a></div></div></td></tr><tr><td><b>RAM</b><p className="text-[11px] text-ink-400">ram</p></td><td>Dropdown</td><td><span className="badge badge-gray">8 values</span></td><td>Mobile, Laptop</td><td>16,240</td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-gray">No</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a></div></div></td></tr><tr><td><b>Warranty period</b><p className="text-[11px] text-ink-400">warranty</p></td><td>Dropdown</td><td><span className="badge badge-gray">7 values</span></td><td>All electronics</td><td>86,240</td><td><span className="badge badge-gray">No</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-green">Yes</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a></div></div></td></tr><tr><td><b>Energy rating</b><p className="text-[11px] text-ink-400">energy-rating</p></td><td>Dropdown</td><td><span className="badge badge-gray">5 values</span></td><td>AC, Refrigerator, Washing machine</td><td>4,860</td><td><span className="badge badge-gray">No</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-gray">No</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></td></tr><tr><td><b>Fabric type</b><p className="text-[11px] text-ink-400">fabric</p></td><td>Multi-select</td><td><span className="badge badge-gray">24 values</span></td><td>Fashion (all)</td><td>1,12,480</td><td><span className="badge badge-gray">No</span></td><td><span className="badge badge-green">Yes</span></td><td><span className="badge badge-gray">No</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Manage values</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–7</b> of <b>284</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>29</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Specification templates</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>New template</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Template</th><th>Category</th><th>Fields</th><th>Required fields</th><th>Products</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Smartphone spec sheet</b></td><td>Mobile › Smartphones</td><td>32</td><td>12</td><td>18,420</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit template</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Preview</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg>Duplicate</a></div></div></td></tr><tr><td><b>Air conditioner spec</b></td><td>Home › Air conditioner</td><td>24</td><td>9</td><td>4,860</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit template</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Preview</a></div></div></td></tr><tr><td><b>Apparel spec</b></td><td>Fashion › All</td><td>18</td><td>6</td><td>1,12,480</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit template</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Preview</a></div></div></td></tr><tr><td><b>Grocery & food spec</b></td><td>Grocery › All</td><td>14</td><td>8</td><td>32,640</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit template</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Preview</a></div></div></td></tr></tbody></table></div></div><div className="card "><div className="card-head"><h3>Attribute values — Colour</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="flex flex-wrap gap-2 mb-3">
      <span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#231f20"}}></i>Black<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#ffffff"}}></i>White<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#ff2525"}}></i>Red<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#2563eb"}}></i>Blue<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#00b894"}}></i>Green<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#ffb020"}}></i>Gold<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#c0c4cc"}}></i>Silver<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#1e3a8a"}}></i>Navy<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#7f1d1d"}}></i>Maroon<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span><span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-[#e7e9ef] text-[12px] font-semibold">
      <i className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background: "#ec4899"}}></i>Pink<button className="text-ink-300 hover:text-brand-600"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></span></div>
      <div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Add value</label><input type="text" className="input" placeholder="e.g. Sky blue" /></div><div className=""><label className="label">Colour hex</label><input type="text" className="input" placeholder="#000000" /></div></div>
      <div className="flex gap-2 mt-2.5"><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add value</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Bulk import</button></div></div></div></div><div className="modal" id="m-attr"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Add / edit attribute</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Attribute name *</label><input type="text" className="input" placeholder="e.g. Storage capacity" /></div><div className=""><label className="label">Code / slug *</label><input type="text" className="input" placeholder="e.g. storage" /></div><div className=""><label className="label">Input type *</label><select className="select"><option>Dropdown (single select)</option><option>Multi-select</option><option>Colour swatch</option><option>Text</option><option>Number</option><option>Boolean (yes/no)</option><option>Date</option></select></div><div className=""><label className="label">Unit</label><input type="text" className="input" placeholder="e.g. GB, kg, inch" /></div><div className="sm:col-span-2"><label className="label">Values</label><textarea className="textarea !min-h-[90px]" placeholder="One value per line, e.g.
64GB
128GB
256GB"></textarea></div><div className="sm:col-span-2"><label className="label">Apply to categories</label><input type="text" className="input" placeholder="Search categories…" /></div><div className=""><label className="label">Display order</label><input type="text" className="input" placeholder="e.g. 3" /></div><div className=""><label className="label">Filter display</label><select className="select"><option>Checkbox list</option><option>Dropdown</option><option>Colour swatches</option><option>Range slider</option></select></div><div className="sm:col-span-2 flex flex-wrap gap-4"><label className="check"><input type="checkbox" defaultChecked />Use for product variants</label><label className="check"><input type="checkbox" defaultChecked />Show as filter on listing page</label><label className="check"><input type="checkbox" defaultChecked />Required when listing</label><label className="check"><input type="checkbox" defaultChecked />Show in comparison table</label><label className="check"><input type="checkbox" defaultChecked />Show in specification tab</label></div></div><div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Attribute saved">Save attribute</button></div></div></div>
    </>
  );
}
