export default function ChatsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Live chat monitor</span></nav>
      <h1>Live Chat Monitor</h1><p>Monitor and join live conversations between customers, vendors and agents.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Chat settings</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="8" r="3.2"/><path d="M2 21a7 7 0 0 1 14 0"/><path d="M16 11a3 3 0 1 0 0-6M18 21a6 6 0 0 0-2-4.5"/></svg>Agent status</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Transcripts</button></div></div>
      <div className="grid xl:grid-cols-[1fr_330px] gap-4"><div className="space-y-4"><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+4</span></div>
      <p className="val">18</p><p className="lbl">Active chats</p><p className="text-[11.5px] text-ink-400 mt-1.5">9 agents online</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">4</p><p className="lbl">Waiting in queue</p><p className="text-[11.5px] text-ink-400 mt-1.5">Longest 2 min 40 s</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg></span>
      <span className="trend down"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v14M6 12l6 6 6-6"/></svg>6 s</span></div>
      <p className="val">32 sec</p><p className="lbl">Avg. response time</p><p className="text-[11.5px] text-ink-400 mt-1.5">Target 45 sec</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">thumb</svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+0.1</span></div>
      <p className="val">4.7 / 5</p><p className="lbl">Chat CSAT (today)</p><p className="text-[11.5px] text-ink-400 mt-1.5">486 ratings</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">Active chats<span className="count">18</span></button><button className="tab " data-tab="t1">Waiting<span className="count">4</span></button><button className="tab " data-tab="t2">Vendor chats<span className="count">6</span></button><button className="tab " data-tab="t3">Flagged / abusive<span className="count">2</span></button><button className="tab " data-tab="t4">Bot handled<span className="count">842</span></button><button className="tab " data-tab="t5">Transcripts<span className="count">48,620</span></button><button className="tab " data-tab="t6">Missed<span className="count">12</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>Agent: All</option><option>Nafisa Karim</option><option>Sabbir Ahmed</option><option>Mehedi Hasan</option><option>Bot</option></select><select className="select input-sm !w-auto"><option>Type: All</option><option>Customer</option><option>Vendor</option><option>Guest visitor</option></select><select className="select input-sm !w-auto"><option>Sentiment: All</option><option>Positive</option><option>Neutral</option><option>Negative</option></select><select className="select input-sm !w-auto"><option>Language: All</option><option>English</option><option>Bengali</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Join chat</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">ear</svg>Whisper to agent</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download transcript</button></div></div></div><div className="card overflow-hidden"><div className="chat-wrap">
      <div className="chat-list thin-scroll"><div className="p-3 border-b border-[#e7e9ef]"><div className="input-group"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[36px]" placeholder="Search conversations" /></div>
      <div className="flex gap-1.5 mt-2 overflow-x-auto no-scrollbar"><button className="chip !h-7 !text-[11.5px] is-active">All</button><button className="chip !h-7 !text-[11.5px] ">Unread</button><button className="chip !h-7 !text-[11.5px] ">Orders</button><button className="chip !h-7 !text-[11.5px] ">Leads</button><button className="chip !h-7 !text-[11.5px] ">Flagged</button></div></div>
      <div className="chat-item is-active"><span className="avatar avatar-md bg-brand-500">K</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Karim Uddin</p><span className="text-[10.5px] text-ink-400 shrink-0">2 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Order still not delivered, please help</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-red !text-[10px]">Urgent · #NK-84219</span><span className="badge badge-solid !text-[10px] ml-auto">3</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-service-500">N</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Nusrat Jahan</p><span className="text-[10.5px] text-ink-400 shrink-0">8 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Refund status please</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-amber !text-[10px]">Refund</span><span className="badge badge-solid !text-[10px] ml-auto">1</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-gold-500">R</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Rahim Electric (vendor)</p><span className="text-[10.5px] text-ink-400 shrink-0">14 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Payout query for August</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-blue !text-[10px]">Vendor</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-ink-500">F</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Farhana Akter</p><span className="text-[10.5px] text-ink-400 shrink-0">22 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Technician is late</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-amber !text-[10px]">Booking</span><span className="badge badge-solid !text-[10px] ml-auto">2</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-brand-500">G</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Guest visitor 8842</p><span className="text-[10.5px] text-ink-400 shrink-0">30 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Is COD available in Sylhet?</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-gray !text-[10px]">Pre-sales</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-service-500">I</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Imran Hossain</p><span className="text-[10.5px] text-ink-400 shrink-0">42 min</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Product looks fake</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-red !text-[10px]">Escalated</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-gold-500">S</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Style Hub (vendor)</p><span className="text-[10.5px] text-ink-400 shrink-0">1 hr</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">Listing rejected, why?</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-blue !text-[10px]">Vendor</span></div></div></div><div className="chat-item "><span className="avatar avatar-md bg-ink-500">S</span>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[13px] font-bold clamp-1">Sabbir Hossain</p><span className="text-[10.5px] text-ink-400 shrink-0">1 hr</span></div>
      <p className="text-[12px] text-ink-500 clamp-1">OTP not coming</p>
      <div className="flex items-center gap-1.5 mt-1"><span className="badge badge-gray !text-[10px]">Account</span></div></div></div></div>
      <div className="chat-body"><div className="flex items-center gap-3 p-3.5 border-b border-[#e7e9ef]">
      <span className="avatar avatar-md bg-brand-500">K</span>
      <div className="min-w-0"><p className="text-[13.5px] font-extrabold">Karim Uddin</p><p className="text-[11.5px] text-service-600 flex items-center gap-1"><svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Online · typically replies in 20 min</p></div>
      <div className="ml-auto flex gap-1"><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg></button><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 7h12l1 14H5z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg></button><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></button>
      <div data-dropdown><button data-dropdown-toggle className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button><div data-dropdown-menu className="right-0">
      <a className="dd-item" data-modal-open="m-chat"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>View profile</a><a className="dd-item" data-modal-open="m-chat"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 7h12l1 14H5z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg>View orders</a><a className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 8a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2 2 2 0 0 0 0 4v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4a2 2 0 0 0 0-4z"/><path d="M12 7v10"/></svg>Send voucher</a><a className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 8v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8M10 12h4"/></svg>Archive chat</a><a className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Report user</a><a className="dd-item"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block user</a></div></div></div></div>
      <div className="chat-scroll thin-scroll space-y-3">
      <p className="text-center text-[11px] text-ink-400">Today · 17 Aug 2026</p>
      <div><div className="bubble bubble-in">Hello, is the Realme C100X still available in green? I need it delivered by tomorrow to Banani.</div><p className="bubble-time">10:12 AM</p></div>
      <div><div className="bubble bubble-out">Yes, we have 12 units of the green 6/128GB variant in stock. Same-day dispatch if you order before 4 PM.</div><p className="bubble-time text-right">10:14 AM ✓✓</p></div>
      <div><div className="bubble bubble-in">Great. Does it come with the official warranty and free delivery?</div><p className="bubble-time">10:15 AM</p></div>
      <div><div className="bubble bubble-out">1 year official Realme warranty + free delivery inside Dhaka. Here is the product link.</div>
      <div className="bubble bubble-out mt-1.5 !bg-white !text-ink-900 border border-[#e7e9ef]"><div className="flex gap-2.5"><span className="ph ph-a w-12 h-12 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><rect x="7" y="2" width="10" height="20" rx="2.5"/><path d="M11 19h2"/></svg></span>
      <div className="min-w-0"><p className="text-[12.5px] font-bold clamp-1">Realme C100X 6/128GB</p><p className="text-[12px] font-extrabold text-brand-600">৳11,290</p></div></div></div>
      <p className="bubble-time text-right">10:16 AM ✓✓</p></div>
      <div><div className="bubble bubble-in">Perfect, ordering now. Thank you!</div><p className="bubble-time">10:22 AM</p></div></div>
      <div className="p-3 border-t border-[#e7e9ef]">
      <div className="flex flex-wrap gap-1.5 mb-2"><button className="chip !h-7 !text-[11.5px]">Thanks for reaching out!</button><button className="chip !h-7 !text-[11.5px]">Yes, in stock ✅</button><button className="chip !h-7 !text-[11.5px]">Sharing the price now</button><button className="chip !h-7 !text-[11.5px]">Delivery in 2–3 days</button></div>
      <div className="flex items-end gap-2"><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h3l2-2h6l2 2h3v12H4z"/><circle cx="12" cy="14" r="3.2"/></svg></button><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg></button><button className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 7h12l1 14H5z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg></button>
      <textarea className="textarea !min-h-[42px] !py-2.5" placeholder="Type your message… (never share phone numbers or outside payment links)"></textarea>
      <button className="btn btn-primary btn-icon shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 3 3 10.5l7 3 3 7z"/><path d="M21 3 10 14"/></svg></button></div></div></div>
      <aside className="hidden 2xl:block border-l border-[#e7e9ef] p-4 overflow-y-auto thin-scroll space-y-4">
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Customer</p>
      <div className="flex items-center gap-2.5 mb-2"><span className="avatar avatar-md bg-brand-500">K</span><div><p className="text-[13px] font-bold">Kamal Uddin</p><p className="text-[11.5px] text-ink-400">Member since 2023</p></div></div>
      <div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Total orders</span><b className="text-right">14</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Lifetime value</span><b className="text-right">৳1,84,200</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Return rate</span><b className="text-right">3%</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Location</span><b className="text-right">Banani, Dhaka</b></div></div></div>
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Recent orders</p>
      <div className="space-y-2"><div className="flex items-center justify-between text-[12px] p-2 rounded-lg bg-ink-50"><b>HB-884213</b><span>৳11,290</span><span className="st st-ship">Shipped</span></div><div className="flex items-center justify-between text-[12px] p-2 rounded-lg bg-ink-50"><b>HB-883120</b><span>৳2,450</span><span className="st st-done">Delivered</span></div><div className="flex items-center justify-between text-[12px] p-2 rounded-lg bg-ink-50"><b>HB-881044</b><span>৳750</span><span className="st st-done">Delivered</span></div></div></div>
      <div><p className="text-[11px] font-extrabold uppercase tracking-wider text-ink-400 mb-2">Internal note</p>
      <textarea className="textarea !min-h-[70px] !text-[12px]" placeholder="Only your team can see this"></textarea>
      <button className="btn btn-sm btn-outline btn-block mt-2">Save note</button></div></aside>
      </div></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Live chat settings</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Widget position</label><select className="select"><option>Bottom right</option><option>Bottom left</option></select></div><div className=""><label className="label">Office hours</label><input type="text" className="input" placeholder="9:00 AM – 11:00 PM" /></div><div className=""><label className="label">Max chats per agent</label><input type="text" className="input" placeholder="4" /></div><div className=""><label className="label">Auto-close idle chat after</label><input type="text" className="input" placeholder="10 minutes" /></div><div className=""><label className="label">Pre-chat form fields</label><select className="select"><option>Name + phone</option><option>Name + phone + order ID</option><option>None</option></select></div><div className=""><label className="label">Offline behaviour</label><select className="select"><option>Show ticket form</option><option>Show help centre</option><option>Hide widget</option></select></div></div>
      <div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Enable chatbot for first response</p><p className="fs">Bot answers FAQs and collects order details.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Show agent name & photo</p><p className="fs">Builds trust with customers.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Allow file sharing in chat</p><p className="fs">Customers can send screenshots.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Mask contact details from vendors</p><p className="fs">Prevents off-platform deals.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Record chat transcripts</p><p className="fs">Store for 24 months for dispute handling.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Ask for CSAT rating after chat</p><p className="fs">1–5 star rating with comment.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Enable Bengali auto-translate</p><p className="fs">Translate between EN and BN in real time.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div><div className="card "><div className="card-head"><h3>Chatbot flows & quick replies</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>New chatbot flow</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Flow / reply</th><th>Trigger</th><th>Resolved by bot</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Track my order</b></td><td>"where is my order"</td><td>86%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Test</a></div></div></td></tr><tr><td><b>Return a product</b></td><td>"return", "refund"</td><td>72%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Test</a></div></div></td></tr><tr><td><b>Delivery charge & COD</b></td><td>"delivery charge", "cod"</td><td>94%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a></div></div></td></tr><tr><td><b>Book a service</b></td><td>"book", "technician"</td><td>68%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a></div></div></td></tr><tr><td><b>Become a seller</b></td><td>"sell", "vendor"</td><td>90%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a></div></div></td></tr><tr><td><b>Escalate to human</b></td><td>"agent", "human"</td><td>—</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit flow</a></div></div></td></tr></tbody></table></div></div></div></div><div className="space-y-4"><div className="card "><div className="card-head"><h3>Conversation context</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Visitor</span><b className="text-right">Karim Uddin · logged in</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Customer since</span><b className="text-right">Mar 2024</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Lifetime value</span><b className="text-right">৳1,84,200</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Open tickets</span><b className="text-right">1 (#TKT-98421)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Current page</span><b className="text-right">/track-order.html</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Device</span><b className="text-right">Android app 4.2.1</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Location</span><b className="text-right">Banani, Dhaka</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Wait time</span><b className="text-right">18 seconds</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Agent</span><b className="text-right">Nafisa Karim</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Sentiment</span><b className="text-right">Negative — angry</b></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 7h12l1 14H5z"/><path d="M9 7a3 3 0 0 1 6 0"/></svg>Open order</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.7M12 17h.01"/></svg>Create ticket</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 8a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2 2 2 0 0 0 0 4v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4a2 2 0 0 0 0-4z"/><path d="M12 7v10"/></svg>Send voucher</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Transfer chat</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="8" r="3.2"/><path d="M2 21a7 7 0 0 1 14 0"/><path d="M16 11a3 3 0 1 0 0-6M18 21a6 6 0 0 0-2-4.5"/></svg>Invite supervisor</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>End chat</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block visitor</button></div>
      <div className="mt-3"><div className="sb-note bg-brand-50 text-brand-700 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg><span>This visitor has 2 previous chats about the same order. Consider an immediate refund or compensation voucher.</span></div></div></div></div><div className="card "><div className="card-head"><h3>Live queue</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Chats waiting</span><b className="text-right">4</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Longest wait</span><b className="text-right">2 min 40 sec</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Active chats</span><b className="text-right">18</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Agents online</span><b className="text-right">9 of 14</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Avg. handling time</span><b className="text-right">6 min 20 sec</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Missed chats today</span><b className="text-right">12</b></div></div>
      <div className="flex gap-2 mt-3"><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Pick next chat</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Queue settings</button></div></div></div></div></div>
      
      <div className="modal" id="m-chat"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Live chat — session #CH-2044</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Customer</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Kamal Uddin · Gold member</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Agent</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Nafisa K. (Support tier 1)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Started</span><span className="text-[12.5px] font-bold text-ink-800 text-right">22 Aug 2026, 10:52 AM</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Duration</span><span className="text-[12.5px] font-bold text-ink-800 text-right">12 min 40 s</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Topic</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Order delay — #HB-884101</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Sentiment</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-amber">Frustrated</span></span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">First response</span><span className="text-[12.5px] font-bold text-ink-800 text-right">18 seconds</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Rating</span><span className="text-[12.5px] font-bold text-ink-800 text-right">3 ★</span></div></div>
      <div className="px-5 pb-4 space-y-2 max-h-[220px] overflow-auto thin-scroll">
      <div className="bg-ink-50 rounded-xl p-2.5 text-[12.5px]"><b>Kamal:</b> My order still shows processing after 3 days.</div>
      <div className="bg-brand-50 rounded-xl p-2.5 text-[12.5px]"><b>Nafisa:</b> Sorry about that! Let me check with the seller right away.</div>
      <div className="bg-ink-50 rounded-xl p-2.5 text-[12.5px]"><b>Kamal:</b> Please, I need it before Friday.</div>
      <div className="bg-brand-50 rounded-xl p-2.5 text-[12.5px]"><b>Nafisa:</b> Seller confirmed dispatch today — I've added a ৳100 voucher for the delay.</div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Escalate to</label><select className="select"><option>No escalation</option><option>Tier 2 support</option><option>Vendor manager</option><option>Dispute team</option></select></div><div className=""><label className="label">Tag session</label><select className="select"><option>Delivery delay</option><option>Payment issue</option><option>Product query</option><option>Complaint</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Supervisor note</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Session saved">Save &amp; close</button></div></div></div>
    </>
  );
}
