export default function DisputesPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Disputes</span></nav>
      <h1>Returns & Disputes</h1><p>Return requests, refund claims and buyer–seller disputes needing resolution.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  data-modal-open="m-res"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Dispute policy</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Bulk resolve</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+8%</span></div>
      <p className="val">386</p><p className="lbl">Open disputes</p><p className="text-[11.5px] text-ink-400 mt-1.5">42 escalated to admin</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+6%</span></div>
      <p className="val">1,842</p><p className="lbl">Return requests</p><p className="text-[11.5px] text-ink-400 mt-1.5">৳28,40,000 value</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+11%</span></div>
      <p className="val">৳18,60,000</p><p className="lbl">Refunds processed</p><p className="text-[11.5px] text-ink-400 mt-1.5">3,420 refunds (30d)</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      <span className="trend down"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v14M6 12l6 6 6-6"/></svg>0.6</span></div>
      <p className="val">2.4 days</p><p className="lbl">Avg. resolution</p><p className="text-[11.5px] text-ink-400 mt-1.5">Target: 48 hours</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All cases<span className="count">2,228</span></button><button className="tab " data-tab="t1">New<span className="count">386</span></button><button className="tab " data-tab="t2">Awaiting vendor<span className="count">242</span></button><button className="tab " data-tab="t3">Awaiting customer<span className="count">164</span></button><button className="tab " data-tab="t4">Escalated to admin<span className="count">42</span></button><button className="tab " data-tab="t5">Refund approved<span className="count">1,240</span></button><button className="tab " data-tab="t6">Rejected<span className="count">128</span></button><button className="tab " data-tab="t7">Closed<span className="count">18,420</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All types</option><option>Return request</option><option>Refund only</option><option>Not delivered</option><option>Wrong item</option><option>Damaged</option><option>Fake product</option><option>Service dispute</option></select><select className="select input-sm !w-auto"><option>All vendors</option><option>High dispute vendors</option></select><select className="select input-sm !w-auto"><option>Priority: All</option><option>High value</option><option>Escalated</option><option>SLA breach</option></select><select className="select input-sm !w-auto"><option>Assigned: Anyone</option><option>Assigned to me</option><option>Unassigned</option></select><input type="date" className="input input-sm !w-auto" />
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Approve refund</button><button className="btn btn-xs btn-outline">Reject</button><button className="btn btn-xs btn-outline">Escalate</button><button className="btn btn-xs btn-outline">Assign to agent</button><button className="btn btn-xs btn-outline">Export</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Case</th><th>Order</th><th>Customer</th><th>Vendor</th><th>Type</th><th>Reason</th><th>Amount</th><th>Evidence</th><th>Age</th><th>Assigned</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><b>#DSP-8842</b></td><td><a href="/admin/orders" className="link">#ORD-283960</a></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Sadia Islam</p><p className="text-[11.5px] text-ink-400">Mirpur, Dhaka</p></div></div></td><td>Mobile Zone</td><td><span className="badge badge-red">Fake product</span></td><td>Received counterfeit charger</td><td><b>৳11,290</b></td><td>4 photos · 1 video</td><td><b className="text-brand-600">3 days</b></td><td>Nafisa K.</td><td><span className="st st-cancel">Escalated</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 19 5.5-5.5 4 4L17 14l3 3"/></svg>View evidence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Refund customer</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject claim</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Penalise vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block product</a></div></div></td></tr><tr><td><b>#DSP-8840</b></td><td><a href="/admin/orders" className="link">#ORD-284140</a></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Farhana Akter</p><p className="text-[11.5px] text-ink-400">Dhanmondi, Dhaka</p></div></div></td><td>Style Hub</td><td><span className="badge badge-amber">Size mismatch</span></td><td>Saree size not as described</td><td>৳8,450</td><td>3 photos</td><td>1 day</td><td>Unassigned</td><td><span className="st st-hold">Awaiting vendor</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Nudge vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve return</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><b>#DSP-8836</b></td><td><a href="/admin/orders" className="link">#ORD-283842</a></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Kamal Hossain</p><p className="text-[11.5px] text-ink-400">Sylhet</p></div></div></td><td>Walton Plaza</td><td><span className="badge badge-amber">Damaged in transit</span></td><td>Fridge door dented</td><td>৳54,900</td><td>6 photos · courier report</td><td>2 days</td><td>Sabbir A.</td><td><span className="st st-progress">Processing</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7h11v8H3zM14 10h4l3 3v2h-7z"/><circle cx="6.5" cy="17.5" r="1.5"/><circle cx="17.5" cy="17.5" r="1.5"/></svg>Claim from courier</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Replace item</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Refund</a></div></div></td></tr><tr><td><b>#DSP-8830</b></td><td><a href="/admin/orders" className="link">#ORD-283740</a></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Imran Khan</p><p className="text-[11.5px] text-ink-400">Uttara, Dhaka</p></div></div></td><td>Fresh Mart</td><td><span className="badge badge-red">Not delivered</span></td><td>Marked delivered but not received</td><td>৳4,280</td><td>Chat log · GPS data</td><td><b className="text-brand-600">5 days</b></td><td>Nafisa K.</td><td><span className="st st-cancel">Escalated</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7h11v8H3zM14 10h4l3 3v2h-7z"/><circle cx="6.5" cy="17.5" r="1.5"/><circle cx="17.5" cy="17.5" r="1.5"/></svg>Courier investigation</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Refund customer</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Recover from courier</a></div></div></td></tr><tr><td><b>#DSP-8824</b></td><td>Booking <a href="/admin/bookings" className="link">#BKG-48096</a></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Nusrat Jahan</p><p className="text-[11.5px] text-ink-400">Gulshan, Dhaka</p></div></div></td><td>Rapid Car Rental</td><td><span className="badge badge-red">Service dispute</span></td><td>Provider did not show up</td><td>৳1,600</td><td>Call recordings</td><td>4 days</td><td>Sabbir A.</td><td><span className="st st-hold">Refund approved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Process refund</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Penalise provider</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Close case</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–5</b> of <b>2228</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>223</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Dispute reasons</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Not as described</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "92%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">842</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Damaged / defective</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "74%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">648</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Not delivered</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "52%", background: "#b42318"}}></i></span>
      <span className="num text-right font-bold text-ink-800">442</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Wrong item sent</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "44%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">386</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Counterfeit</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "28%", background: "#8b5cf6"}}></i></span>
      <span className="num text-right font-bold text-ink-800">242</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Service not provided</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "22%", background: "#6c7a91"}}></i></span>
      <span className="num text-right font-bold text-ink-800">186</span></div></div></div></div><div className="card "><div className="card-head"><h3>Resolution outcomes</h3><div className="flex items-center gap-2"></div></div><div className="p-4 flex items-center gap-4"><div className="relative w-[168px] h-[168px] mx-auto"><svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
      <circle cx="50" cy="50" r="42" fill="none" stroke="#eceef2" strokeWidth="13"/>
      <circle cx="50" cy="50" r="42" fill="none" stroke="#ff2525" strokeWidth="13" strokeDasharray="126.66901579274047 137.22476710880215" strokeDashoffset="0" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#2563eb" strokeWidth="13" strokeDasharray="58.05663223833938 205.83715066320326" strokeDashoffset="-126.66901579274047" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#ffb020" strokeWidth="13" strokeDasharray="36.94512960621597 226.94865329532666" strokeDashoffset="-184.72564803107986" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#6c7a91" strokeWidth="13" strokeDasharray="29.02831611916969 234.86546678237295" strokeDashoffset="-221.67077763729583" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#00b894" strokeWidth="13" strokeDasharray="13.194689145077133 250.69909375646552" strokeDashoffset="-250.69909375646552" strokeLinecap="butt"/></svg>
      <div className="absolute inset-0 grid place-items-center text-center"><div><p className="donut-center">84%</p><p className="text-[11.5px] text-ink-400">Buyer favour</p></div></div></div>
      <div className="chart-legend justify-center mt-4"><span><i style={{background: "#ff2525"}}></i>Refund to customer · 48%</span><span><i style={{background: "#2563eb"}}></i>Replacement · 22%</span><span><i style={{background: "#ffb020"}}></i>Partial refund · 14%</span><span><i style={{background: "#6c7a91"}}></i>Rejected · 11%</span><span><i style={{background: "#00b894"}}></i>Vendor goodwill · 5%</span></div>
      <div className="flex-1"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Refund from vendor</span><b className="text-right">৳14,20,000</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Platform absorbed</span><b className="text-right">৳1,84,000</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Recovered from courier</span><b className="text-right">৳2,56,000</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Vendor penalties</span><b className="text-right">৳86,000</b></div></div></div></div></div><div className="card "><div className="card-head"><h3>Vendors with most disputes</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Vendor health report</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Vendor</th><th>Rate</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Mobile Zone</b></td><td><span className="badge badge-red">8.4%</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn</a></div></div></td></tr><tr><td><b>Quick Deals BD</b></td><td><span className="badge badge-red">6.2%</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn</a></div></div></td></tr><tr><td><b>Fresh Mart</b></td><td><span className="badge badge-amber">3.8%</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review vendor</a></div></div></td></tr><tr><td><b>Style Hub</b></td><td><span className="badge badge-amber">2.1%</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review vendor</a></div></div></td></tr><tr><td><b>Rahim Electric</b></td><td><span className="badge badge-green">0.8%</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review vendor</a></div></div></td></tr></tbody></table></div></div></div><div className="modal" id="m-res"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Resolve dispute #DSP-8842</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Resolution *</label><select className="select"><option>Full refund to customer</option><option>Partial refund</option><option>Replacement shipment</option><option>Return & refund</option><option>Reject claim</option><option>Goodwill voucher</option></select></div><div className=""><label className="label">Refund amount</label><input type="text" className="input" placeholder="৳11,290" /></div><div className=""><label className="label">Refund from</label><select className="select"><option>Vendor balance</option><option>Platform (goodwill)</option><option>Courier claim</option><option>Split 50/50</option></select></div><div className=""><label className="label">Refund method</label><select className="select"><option>Original payment method</option><option>Wallet credit</option><option>Bank transfer</option><option>Voucher</option></select></div><div className=""><label className="label">Vendor action</label><select className="select"><option>No action</option><option>Warning</option><option>Penalty ৳1,000</option><option>Block product</option><option>Suspend vendor</option></select></div><div className=""><label className="label">Customer compensation</label><select className="select"><option>None</option><option>Free shipping voucher</option><option>৳200 voucher</option><option>Loyalty points</option></select></div><div className="sm:col-span-2"><label className="label">Resolution note to customer</label><textarea className="textarea !min-h-[90px]" placeholder="This message is shown to the customer"></textarea></div><div className="sm:col-span-2"><label className="label">Internal note</label><textarea className="textarea !min-h-[90px]" placeholder="Admin-only notes and evidence summary"></textarea></div><div className="sm:col-span-2 flex flex-wrap gap-4"><label className="check"><input type="checkbox" defaultChecked />Notify customer</label><label className="check"><input type="checkbox" defaultChecked />Notify vendor</label><label className="check"><input type="checkbox" defaultChecked />Add to vendor violation log</label><label className="check"><input type="checkbox" defaultChecked />Close case after resolution</label></div></div><div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Dispute resolved">Resolve case</button></div></div></div>
    </>
  );
}
