export default function InventoryPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Stock overview</span></nav>
      <h1>Stock Overview</h1><p>Marketplace-wide stock levels, low-stock risks and price change monitoring.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Low stock alerts</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Price change log</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export stock</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+6%</span></div>
      <p className="val">48.6L</p><p className="lbl">Total stock units</p><p className="text-[11.5px] text-ink-400 mt-1.5">Across 3.9L listings</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+9%</span></div>
      <p className="val">৳84,20,00,000</p><p className="lbl">Stock value</p><p className="text-[11.5px] text-ink-400 mt-1.5">At selling price</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+12%</span></div>
      <p className="val">18,420</p><p className="lbl">Low stock listings</p><p className="text-[11.5px] text-ink-400 mt-1.5">Below vendor threshold</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+4%</span></div>
      <p className="val">32,420</p><p className="lbl">Out of stock</p><p className="text-[11.5px] text-ink-400 mt-1.5">8.3% of catalog</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All<span className="count">3,90,000</span></button><button className="tab " data-tab="t1">In stock<span className="count">3,42,180</span></button><button className="tab " data-tab="t2">Low stock<span className="count">18,420</span></button><button className="tab " data-tab="t3">Out of stock<span className="count">32,420</span></button><button className="tab " data-tab="t4">Overstock<span className="count">4,860</span></button><button className="tab " data-tab="t5">Price changes<span className="count">2,842</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Electronics</option><option>Fashion</option><option>Grocery</option><option>Home</option></select><select className="select input-sm !w-auto"><option>All vendors</option><option>Top 100 vendors</option><option>New vendors</option></select><select className="select input-sm !w-auto"><option>Stock: All</option><option>Zero</option><option>1–5 units</option><option>6–20 units</option><option>20+ units</option></select><input type="date" className="input input-sm !w-auto" /><select className="select input-sm !w-auto"><option>Sort: Lowest stock</option><option>Highest value</option><option>Fastest moving</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Notify vendor</button><button className="btn btn-xs btn-outline">Hide from search</button><button className="btn btn-xs btn-outline">Request restock</button><button className="btn btn-xs btn-outline">Export</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Product</th><th>Vendor</th><th>Category</th><th>Price</th><th>Stock</th><th>Reserved</th><th>Available</th><th>Sold (30d)</th><th>Days of cover</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Gree 1.5 Ton Inverter AC</p><p className="text-[11.5px] text-ink-400">SKU GREE-18XPUV</p></div></div></td><td>Rahim Electric</td><td>Home › AC</td><td>৳68,900</td><td><b className="text-brand-600">2</b></td><td>1</td><td>1</td><td>184</td><td><b className="text-brand-600">0.3 days</b></td><td><span className="st st-pending">Low stock</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify vendor</a><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Hide from search</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Suggest restock qty</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Realme C100X 6/128GB</p><p className="text-[11.5px] text-ink-400">SKU RC100X-BLK</p></div></div></td><td>Rahim Electric</td><td>Mobile › Smartphones</td><td>৳11,290</td><td><b>124</b></td><td>8</td><td>116</td><td>842</td><td>4.4 days</td><td><span className="st st-pending">Low stock</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify vendor</a><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View listing</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Premium Jamdani Saree</p><p className="text-[11.5px] text-ink-400">SKU JAM-SR-042</p></div></div></td><td>Style Hub</td><td>Fashion › Sarees</td><td>৳8,450</td><td><b>36</b></td><td>2</td><td>34</td><td>284</td><td>3.8 days</td><td><span className="st st-done">In stock</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View listing</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Anchor LED Bulb 9W (Pack of 4)</p><p className="text-[11.5px] text-ink-400">SKU LED-9W-4P</p></div></div></td><td>Rahim Electric</td><td>Home › Lighting</td><td>৳420</td><td><b>0</b></td><td>0</td><td>0</td><td>1,842</td><td><b className="text-brand-600">0 days</b></td><td><span className="st st-cancel">Out of stock</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Auto-hide</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>Find alternatives</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Winter Jacket — Unisex</p><p className="text-[11.5px] text-ink-400">SKU WJ-UNI-XL</p></div></div></td><td>Style Hub</td><td>Fashion › Jackets</td><td>৳2,890</td><td><b>1,842</b></td><td>4</td><td>1,838</td><td>12</td><td><b>153 days</b></td><td><span className="st st-hold">Overstock</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 19 14-14"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/></svg>Suggest discount</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify vendor</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–5</b> of <b>390000</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>39000</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Stock health by category</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Grocery</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "42%", background: "#b42318"}}></i></span>
      <span className="num text-right font-bold text-ink-800">12% OOS</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Fashion</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "22%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">6% OOS</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Electronics</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "18%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">4% OOS</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Mobile</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "14%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">3% OOS</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Home & Kitchen</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "26%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">7% OOS</span></div></div>
      <div className="sb-note bg-gold-50 text-gold-800 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg><span>Grocery has the highest out-of-stock rate. Consider enabling auto-reorder reminders for perishable vendors.</span></div></div></div><div className="card "><div className="card-head"><h3>Recent price changes</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Full price log</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Product</th><th>Old → New</th><th>Change</th><th>By</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Realme C100X</b></td><td>৳12,490 → ৳11,290</td><td><span className="badge badge-green">-9.6%</span></td><td>Vendor</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>View log</a></div></div></td></tr><tr><td><b>Gree 1.5 Ton AC</b></td><td>৳64,900 → ৳68,900</td><td><span className="badge badge-amber">+6.2%</span></td><td>Vendor</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>View log</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Flag</a></div></div></td></tr><tr><td><b>Baby Formula 900g</b></td><td>৳2,900 → ৳3,200</td><td><span className="badge badge-red">+10.3%</span></td><td>Vendor</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>Investigate</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn vendor</a></div></div></td></tr><tr><td><b>LED Bulb 9W</b></td><td>৳480 → ৳420</td><td><span className="badge badge-green">-12.5%</span></td><td>Campaign</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>View log</a></div></div></td></tr></tbody></table></div></div><div className="card "><div className="card-head"><h3>Automation & alerts</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Auto-hide out-of-stock listings</p><p className="fs">Remove from search until restocked.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Low stock email to vendor</p><p className="fs">Sent when stock ≤ 5 units.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Price gouging detection</p><p className="fs">Flag increases above 20% within 7 days.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Overstock discount suggestion</p><p className="fs">Suggest promotions for slow-moving stock.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Daily stock digest to category managers</p><p className="fs">Summary of OOS and low-stock items.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div></div>
      
      <div className="modal" id="m-stock"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Adjust stock — Realme C100X 6/128GB</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Current on hand</span><span className="text-[12.5px] font-bold text-ink-800 text-right">124 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reserved (unshipped)</span><span className="text-[12.5px] font-bold text-ink-800 text-right">18 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Available to sell</span><span className="text-[12.5px] font-bold text-ink-800 text-right">106 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Warehouse</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Dhaka — Tejgaon (primary)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reorder level</span><span className="text-[12.5px] font-bold text-ink-800 text-right">25 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Last count</span><span className="text-[12.5px] font-bold text-ink-800 text-right">18 Aug 2026 by Sabbir A.</span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Adjustment type</label><select className="select"><option>Add stock (received)</option><option>Remove (damaged)</option><option>Remove (lost)</option><option>Set absolute count</option><option>Transfer warehouse</option></select></div><div className=""><label className="label">Quantity</label><input type="number" className="input" /></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Warehouse</label><select className="select"><option>Dhaka — Tejgaon</option><option>Chattogram — Agrabad</option><option>Sylhet hub</option></select></div><div className=""><label className="label">Reference</label><input type="text" className="input" placeholder="GRN / invoice no." /></div></div>
      <div className="px-5"><div className=""><label className="label">Reason / note</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Stock updated">Apply adjustment</button></div></div></div>
    </>
  );
}
