export default function KycPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">KYC verification</span></nav>
      <h1>KYC Verification</h1><p>Identity, business and bank verification for vendors and high-value customers.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>KYC policy</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Bulk verify</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request documents</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2.5" y="5" width="19" height="14" rx="2"/><circle cx="8.5" cy="11" r="2.2"/><path d="M5.5 16.5a3.5 3.5 0 0 1 6 0M14 10h4M14 13.5h4"/></svg></span>
      </div>
      <p className="val">184</p><p className="lbl">Pending KYC</p><p className="text-[11.5px] text-ink-400 mt-1.5">48 above 72 hours</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+8%</span></div>
      <p className="val">7,842</p><p className="lbl">Verified vendors</p><p className="text-[11.5px] text-ink-400 mt-1.5">90.7% of vendors</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></span>
      </div>
      <p className="val">286</p><p className="lbl">Rejected</p><p className="text-[11.5px] text-ink-400 mt-1.5">Fake / mismatched documents</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg></span>
      </div>
      <p className="val">482</p><p className="lbl">Re-verification due</p><p className="text-[11.5px] text-ink-400 mt-1.5">Licence expiring soon</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">Pending<span className="count">184</span></button><button className="tab " data-tab="t1">NID / identity<span className="count">86</span></button><button className="tab " data-tab="t2">Business documents<span className="count">62</span></button><button className="tab " data-tab="t3">Bank verification<span className="count">36</span></button><button className="tab " data-tab="t4">Verified<span className="count">7,842</span></button><button className="tab " data-tab="t5">Rejected<span className="count">286</span></button><button className="tab " data-tab="t6">Expiring soon<span className="count">482</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>Entity: All</option><option>Vendor</option><option>Customer</option><option>Staff</option></select><select className="select input-sm !w-auto"><option>Document: All</option><option>NID</option><option>Passport</option><option>Driving licence</option><option>Trade licence</option><option>TIN</option><option>BIN</option><option>Bank statement</option><option>Cheque book</option></select><select className="select input-sm !w-auto"><option>Status: All</option><option>Pending</option><option>Verified</option><option>Rejected</option><option>Expired</option></select><select className="select input-sm !w-auto"><option>Age: All</option><option>Above 72 hours</option><option>Above 7 days</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Entity</th><th>Type</th><th>Document</th><th>Document no.</th><th>Name match</th><th>Face match</th><th>Expiry</th><th>Submitted</th><th>Reviewer</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Nabila Fashion House</p><p className="text-[11.5px] text-ink-400">Vendor #VND-1442</p></div></div></td><td><span className="badge badge-blue">Vendor</span></td><td>National ID (front + back)</td><td>1994823847562</td><td><span className="badge badge-green">Matched</span></td><td><span className="badge badge-green">98% match</span></td><td>No expiry</td><td>2 hrs ago</td><td>Unassigned</td><td><span className="st st-pending">Pending</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-kyc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>View documents</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Verify with NID API</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request re-upload</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">TechnoMart BD Ltd.</p><p className="text-[11.5px] text-ink-400">Vendor #VND-1448</p></div></div></td><td><span className="badge badge-blue">Vendor</span></td><td>Incorporation + BIN + TIN</td><td>C-184926/2022</td><td><span className="badge badge-green">Matched</span></td><td>—</td><td>31 Dec 2026</td><td>5 hrs ago</td><td>Nafisa K.</td><td><span className="st st-hold">Under review</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-kyc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>View documents</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Verify BIN with NBR</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Sundori Beauty Lounge</p><p className="text-[11.5px] text-ink-400">Vendor #VND-1452</p></div></div></td><td><span className="badge badge-blue">Vendor</span></td><td>Trade licence</td><td>TRAD/DNCC/0048219</td><td><span className="badge badge-amber">Partial mismatch</span></td><td>—</td><td><b className="text-brand-600">30 Jun 2026 (expired)</b></td><td>1 day ago</td><td>Sabbir A.</td><td><span className="st st-cancel">Rejected</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-kyc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>View documents</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request renewed licence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve with condition</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Rahim Electric</p><p className="text-[11.5px] text-ink-400">Vendor #VND-1042</p></div></div></td><td><span className="badge badge-blue">Vendor</span></td><td>Bank account verification</td><td>DBBL ****4521</td><td><span className="badge badge-green">Matched</span></td><td>—</td><td>—</td><td>2 days ago</td><td>Nafisa K.</td><td><span className="st st-done">Verified</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-kyc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>View documents</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Verification report</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Nusrat Jahan</p><p className="text-[11.5px] text-ink-400">Customer #CUS-48219 · High-value</p></div></div></td><td><span className="badge badge-gray">Customer</span></td><td>NID for wallet withdrawal</td><td>1992384756201</td><td><span className="badge badge-green">Matched</span></td><td><span className="badge badge-green">96% match</span></td><td>No expiry</td><td>3 days ago</td><td>Unassigned</td><td><span className="st st-pending">Pending</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-kyc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>View documents</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–5</b> of <b>184</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>19</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Verification checks</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">NID API verification (Election Commission)</p><p className="fs">Auto-validate NID number, name and date of birth.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Face match with selfie</p><p className="fs">AI comparison of NID photo and live selfie.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Trade licence validation</p><p className="fs">Check licence number against city corporation records.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">BIN / TIN validation (NBR)</p><p className="fs">Verify VAT and tax registration numbers.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Bank account name match</p><p className="fs">Match account title with owner or business name.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Sanctions & blacklist screening</p><p className="fs">Screen against internal and external blacklists.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Annual re-verification</p><p className="fs">Ask vendors to re-confirm documents every 12 months.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div>
      <div className="p-4 pt-0"><div className="sb-note bg-gold-50 text-gold-800 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg><span>4 documents failed the automated face-match check today and need manual review.</span></div></div></div></div><div className="card "><div className="card-head"><h3>Document viewer</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="grid grid-cols-2 gap-3">
      <div className="rounded-xl border border-[#e7e9ef] overflow-hidden"><div className="ph aspect-[4/3]"></div><p className="text-[11.5px] font-semibold p-2">NID — front</p></div><div className="rounded-xl border border-[#e7e9ef] overflow-hidden"><div className="ph aspect-[4/3]"></div><p className="text-[11.5px] font-semibold p-2">NID — back</p></div><div className="rounded-xl border border-[#e7e9ef] overflow-hidden"><div className="ph aspect-[4/3]"></div><p className="text-[11.5px] font-semibold p-2">Selfie</p></div><div className="rounded-xl border border-[#e7e9ef] overflow-hidden"><div className="ph aspect-[4/3]"></div><p className="text-[11.5px] font-semibold p-2">Trade licence</p></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Extracted name (OCR)</label><input type="text" className="input" placeholder="Nabila Sultana" /></div><div className=""><label className="label">Extracted NID</label><input type="text" className="input" placeholder="1994823847562" /></div><div className=""><label className="label">Date of birth</label><input type="text" className="input" placeholder="12 Apr 1994" /></div><div className=""><label className="label">Address on document</label><input type="text" className="input" placeholder="Bashundhara R/A, Dhaka" /></div><div className=""><label className="label">Verification level</label><select className="select"><option>Basic</option><option>Standard</option><option>Enhanced</option></select></div><div className=""><label className="label">Decision note</label><textarea className="textarea !min-h-[90px]" placeholder="Reason for approval or rejection"></textarea></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-primary" data-toast="KYC approved"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve KYC</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request re-upload</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download all</button></div></div></div></div>
      
      <div className="modal" id="m-kyc"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>KYC verification — Gadget World BD</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Application</span><span className="text-[12.5px] font-bold text-ink-800 text-right">#KYC-4412 · submitted 16 Aug 2026</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Business type</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Private limited company</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Trade licence</span><span className="text-[12.5px] font-bold text-ink-800 text-right">TRAD/DNCC/882144 · exp 31 Dec 2027</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">TIN / BIN</span><span className="text-[12.5px] font-bold text-ink-800 text-right">482991002144 / 0031882144</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">NID (owner)</span><span className="text-[12.5px] font-bold text-ink-800 text-right">1990XXXXXXXXX · matched</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Bank account</span><span className="text-[12.5px] font-bold text-ink-800 text-right">City Bank · ****8842 · name matched</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Address proof</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Utility bill (Jul 2026)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Auto OCR match</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-green">Name 98%</span> <span className="badge badge-green">Address 92%</span></span></div></div>
      <div className="px-5 grid grid-cols-2 sm:grid-cols-4 gap-2.5 pb-2"><div className="text-center"><span className="ph ph-a w-full h-[86px] rounded-lg mb-1.5 block"></span><p className="text-[11px] font-bold">Trade licence</p><button className="text-[11px] text-brand-600 font-bold">View full</button></div><div className="text-center"><span className="ph ph-b w-full h-[86px] rounded-lg mb-1.5 block"></span><p className="text-[11px] font-bold">NID front</p><button className="text-[11px] text-brand-600 font-bold">View full</button></div><div className="text-center"><span className="ph ph-c w-full h-[86px] rounded-lg mb-1.5 block"></span><p className="text-[11px] font-bold">NID back</p><button className="text-[11px] text-brand-600 font-bold">View full</button></div><div className="text-center"><span className="ph ph-d w-full h-[86px] rounded-lg mb-1.5 block"></span><p className="text-[11px] font-bold">Bank statement</p><button className="text-[11px] text-brand-600 font-bold">View full</button></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Decision</label><select className="select"><option>Approve — full verification</option><option>Approve — limited (₹ cap)</option><option>Request more documents</option><option>Reject</option></select></div><div className=""><label className="label">Verified badge</label><select className="select"><option>Verified Pro</option><option>Verified</option><option>None</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Reviewer note</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="KYC decision saved">Submit decision</button></div></div></div>
    </>
  );
}
