export default function MediaPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Media library</span></nav>
      <h1>Media Library</h1><p>All images, videos and documents uploaded by staff and vendors.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Storage settings</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Optimise all</button><button className="btn btn-sm btn-primary" data-modal-open="m-up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Upload files</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 19 5.5-5.5 4 4L17 14l3 3"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+8,420</span></div>
      <p className="val">4,86,200</p><p className="lbl">Total files</p><p className="text-[11.5px] text-ink-400 mt-1.5">18,420 this month</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg></span>
      </div>
      <p className="val">842 GB</p><p className="lbl">Storage used</p><p className="text-[11.5px] text-ink-400 mt-1.5">of 2 TB (42%)</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6.5 18a4.5 4.5 0 0 1 .3-9 6 6 0 0 1 11.4 1.6A3.9 3.9 0 0 1 17.5 18z"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+12%</span></div>
      <p className="val">18.4 TB</p><p className="lbl">CDN bandwidth (30d)</p><p className="text-[11.5px] text-ink-400 mt-1.5">৳48,200 cost</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      </div>
      <p className="val">4,862</p><p className="lbl">Unoptimised images</p><p className="text-[11.5px] text-ink-400 mt-1.5">Can save 128 GB</p></div></div><div className="card "><div className="card-head"><h3>Files</h3><div className="flex items-center gap-2"></div></div><div className="p-4">
      <div className="flex flex-wrap items-center gap-2 mb-4"><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>All folders</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Banners (842)</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Products (3,86,000)</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Services (48,200)</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Blog (4,862)</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Brand logos (486)</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>KYC documents (18,420)</button><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>New folder</button></div>
      <div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-6 gap-3">
      <label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">eid-hero-banner.webp</p><p className="text-[10.5px] text-ink-400">WebP · 186 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">smartphone-realme-c100x-1.jpg</p><p className="text-[10.5px] text-ink-400">JPG · 248 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">ac-repair-service.jpg</p><p className="text-[10.5px] text-ink-400">JPG · 312 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">brand-samsung-logo.svg</p><p className="text-[10.5px] text-ink-400">SVG · 8 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">blog-ac-guide-cover.webp</p><p className="text-[10.5px] text-ink-400">WebP · 142 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">product-video-demo.mp4</p><p className="text-[10.5px] text-ink-400">MP4 · 4.2 MB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">saree-collection-01.jpg</p><p className="text-[10.5px] text-ink-400">JPG · 486 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">grocery-banner-mobile.webp</p><p className="text-[10.5px] text-ink-400">WebP · 96 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">trade-licence-vnd1442.pdf</p><p className="text-[10.5px] text-ink-400">PDF · 1.2 MB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">category-icon-electronics.svg</p><p className="text-[10.5px] text-ink-400">SVG · 4 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">flash-sale-strip.png</p><p className="text-[10.5px] text-ink-400">PNG · 842 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label><label className="relative rounded-xl border border-[#e7e9ef] overflow-hidden group cursor-pointer">
      <input type="checkbox" className="absolute top-2 left-2 z-10 w-4 h-4 accent-brand-600" />
      <div className="ph aspect-square"></div>
      <div className="p-2"><p className="text-[11.5px] font-semibold truncate">provider-profile-cover.jpg</p><p className="text-[10.5px] text-ink-400">JPG · 386 KB</p></div>
      <div className="absolute inset-0 bg-ink-900/60 opacity-0 group-hover:opacity-100 transition flex items-center justify-center gap-1">
      <button className="btn btn-xs btn-primary"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg></button><button className="btn btn-xs btn-outline bg-white"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg></button></div></label>
      </div>
      <div className="flex items-center justify-between mt-4 pt-4 border-t border-[#eef0f4]"><p className="text-[12px] text-ink-500">Showing 12 of 4,86,200 files</p><div className="flex gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v14M6 12l6 6 6-6"/></svg>Load more</button><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Select all on page</button></div></div></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All files<span className="count">4,86,200</span></button><button className="tab " data-tab="t1">Images<span className="count">4,62,000</span></button><button className="tab " data-tab="t2">Videos<span className="count">8,420</span></button><button className="tab " data-tab="t3">Documents<span className="count">15,780</span></button><button className="tab " data-tab="t4">Banners<span className="count">842</span></button><button className="tab " data-tab="t5">Vendor uploads<span className="count">3,86,000</span></button><button className="tab " data-tab="t6">Unused<span className="count">18,420</span></button><button className="tab " data-tab="t7">Trash<span className="count">2,480</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>Type: All</option><option>JPG / JPEG</option><option>PNG</option><option>WebP</option><option>SVG</option><option>MP4</option><option>PDF</option></select><select className="select input-sm !w-auto"><option>Uploaded by: All</option><option>Staff</option><option>Vendors</option><option>System</option></select><select className="select input-sm !w-auto"><option>Folder: All</option><option>Banners</option><option>Products</option><option>Services</option><option>Blog</option><option>Brand logos</option><option>KYC documents</option></select><select className="select input-sm !w-auto"><option>Size: All</option><option>Above 2 MB</option><option>500 KB–2 MB</option><option>Below 500 KB</option></select><input type="date" className="input input-sm !w-auto" />
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Move to folder</button><button className="btn btn-xs btn-outline">Optimise</button><button className="btn btn-xs btn-outline">Add alt text</button><button className="btn btn-xs btn-outline">Download</button><button className="btn btn-xs btn-outline">Delete</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>File details</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="ph aspect-video rounded-xl mb-3"></div>
      <div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">File name</span><b className="text-right">eid-hero-banner.webp</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Dimensions</span><b className="text-right">1920 × 640 px</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">File size</span><b className="text-right">186 KB (was 842 KB)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Format</span><b className="text-right">WebP · optimised</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Uploaded by</span><b className="text-right">Marketing team</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Uploaded on</span><b className="text-right">18 Aug 2026, 11:24 AM</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Folder</span><b className="text-right">Banners</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Used in</span><b className="text-right">3 places</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">CDN URL</span><b className="text-right">cdn.niko.com.bd/b/eid-hero.webp</b></div></div>
      <div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Alt text</label><input type="text" className="input" placeholder="Eid Mega Sale — up to 70% off" /></div><div className=""><label className="label">Caption</label><input type="text" className="input" placeholder="Optional caption" /></div><div className=""><label className="label">Tags</label><input type="text" className="input" placeholder="eid, sale, banner" /></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg>Copy URL</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Replace file</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</button></div></div></div><div className="card "><div className="card-head"><h3>Storage breakdown</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Folder</th><th>Files</th><th>Size</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Products</b></td><td>3,86,000</td><td>486 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr><tr><td><b>Services</b></td><td>48,200</td><td>142 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr><tr><td><b>KYC documents</b></td><td>18,420</td><td>86 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr><tr><td><b>Blog</b></td><td>4,862</td><td>48 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr><tr><td><b>Banners</b></td><td>842</td><td>18 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr><tr><td><b>Videos</b></td><td>8,420</td><td>62 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Open</a></div></div></td></tr></tbody></table></div>
      <div className="p-3"><div className="sb-note bg-gold-50 text-gold-800 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg><span>18,420 files are not used anywhere. Cleaning them up would free 128 GB.</span></div>
      <div className="flex gap-2 mt-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>Find unused files</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Empty trash</button></div></div></div></div><div className="card "><div className="card-head"><h3>Upload rules</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Max image size</label><input type="text" className="input" placeholder="5 MB" /></div><div className=""><label className="label">Max video size</label><input type="text" className="input" placeholder="50 MB" /></div><div className=""><label className="label">Allowed image types</label><input type="text" className="input" placeholder="JPG, PNG, WebP, SVG" /></div><div className=""><label className="label">Allowed doc types</label><input type="text" className="input" placeholder="PDF, JPG, PNG" /></div><div className=""><label className="label">Min product image size</label><input type="text" className="input" placeholder="800 × 800 px" /></div><div className=""><label className="label">Auto-convert to</label><select className="select"><option>WebP</option><option>AVIF</option><option>Keep original</option></select></div></div>
      <div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Auto-optimise on upload</p><p className="fs">Compress and convert images automatically.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Generate thumbnails</p><p className="fs">Create 5 responsive sizes for every image.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Strip EXIF data</p><p className="fs">Remove camera and location metadata.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Watermark vendor images</p><p className="fs">Add a subtle Niko watermark.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox"   /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Scan for inappropriate content</p><p className="fs">AI moderation of uploaded images.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Serve via CDN</p><p className="fs">Deliver all media through the CDN.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div></div><div className="modal" id="m-up"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Upload files</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="rounded-xl border-2 border-dashed border-[#d7dae2] p-8 text-center">
      <div className="w-12 h-12 rounded-full bg-brand-50 text-brand-600 grid place-items-center mx-auto mb-3"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg></div>
      <p className="text-[13.5px] font-bold">Drag & drop files here</p><p className="text-[12px] text-ink-500 mt-1">JPG, PNG, WebP, SVG, MP4, PDF — up to 50 MB each</p>
      <div className="mt-3"><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7a2 2 0 0 1 2-2h4l2 2.5h6a2 2 0 0 1 2 2V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></svg>Browse files</button></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Destination folder</label><select className="select"><option>Banners</option><option>Products</option><option>Services</option><option>Blog</option><option>Brand logos</option><option>Documents</option></select></div><div className=""><label className="label">Alt text (applies to all)</label><input type="text" className="input" placeholder="Optional" /></div><div className=""><label className="label">Tags</label><input type="text" className="input" placeholder="Comma separated" /></div><div className=""><label className="label">Optimisation</label><select className="select"><option>Auto (recommended)</option><option>Lossless</option><option>None</option></select></div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Files uploaded">Upload</button></div></div></div>
    </>
  );
}
