export default function ModerationPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Reports & abuse</span></nav>
      <h1>Reports & Abuse</h1><p>User reports, counterfeit complaints, prohibited items and enforcement actions.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 5a2 2 0 0 1 2-2h13v18H6a2 2 0 0 0-2 2z"/><path d="M8 7h7"/></svg>Policy library</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Banned word list</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Enforcement log</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></span>
      </div>
      <p className="val">12</p><p className="lbl">Open reports</p><p className="text-[11.5px] text-ink-400 mt-1.5">4 high priority</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+12%</span></div>
      <p className="val">842</p><p className="lbl">Resolved (30d)</p><p className="text-[11.5px] text-ink-400 mt-1.5">Avg. 6 hrs</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg></span>
      </div>
      <p className="val">486</p><p className="lbl">Enforcement actions</p><p className="text-[11.5px] text-ink-400 mt-1.5">86 suspensions</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      </div>
      <p className="val">48</p><p className="lbl">Repeat offenders</p><p className="text-[11.5px] text-ink-400 mt-1.5">Vendors with 3+ strikes</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">Open<span className="count">12</span></button><button className="tab " data-tab="t1">High priority<span className="count">4</span></button><button className="tab " data-tab="t2">Counterfeit claims<span className="count">18</span></button><button className="tab " data-tab="t3">Prohibited items<span className="count">24</span></button><button className="tab " data-tab="t4">Fake reviews<span className="count">842</span></button><button className="tab " data-tab="t5">Abusive users<span className="count">86</span></button><button className="tab " data-tab="t6">Vendor misconduct<span className="count">42</span></button><button className="tab " data-tab="t7">Resolved<span className="count">842</span></button><button className="tab " data-tab="t8">Appeals<span className="count">18</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>Report type: All</option><option>Counterfeit / fake product</option><option>Prohibited item</option><option>Misleading listing</option><option>Wrong category</option><option>Copyright / trademark</option><option>Abusive review</option><option>Fraud / scam</option><option>Off-platform selling</option><option>Harassment</option><option>Unsafe service</option></select><select className="select input-sm !w-auto"><option>Reported by: All</option><option>Customer</option><option>Vendor</option><option>Brand owner</option><option>Staff</option><option>AI system</option></select><select className="select input-sm !w-auto"><option>Priority: All</option><option>High</option><option>Medium</option><option>Low</option></select><select className="select input-sm !w-auto"><option>Status: All</option><option>Open</option><option>Investigating</option><option>Resolved</option><option>Dismissed</option></select><input type="date" className="input input-sm !w-auto" />
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Assign to me</button><button className="btn btn-xs btn-outline">Change priority</button><button className="btn btn-xs btn-outline">Resolve</button><button className="btn btn-xs btn-outline">Dismiss</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Report ID</th><th>Subject</th><th>Type</th><th>Reported item / user</th><th>Reported by</th><th>Evidence</th><th>Priority</th><th>Assigned to</th><th>Age</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><b>#RPT-8842</b></td><td>Counterfeit Samsung charger being sold</td><td><span className="badge badge-red">Counterfeit</span></td><td><b>Fast Charger 25W</b><p className="text-[11px] text-ink-400">Quick Deals BD · #VND-1388</p></td><td>Samsung BD (brand owner)</td><td>3 photos + invoice</td><td><span className="badge badge-red">High</span></td><td>Nafisa Karim</td><td>2 hrs</td><td><span className="st st-hold">Investigating</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  data-modal-open="m-abuse"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 19 5.5-5.5 4 4L17 14l3 3"/></svg>View evidence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Suspend vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>Notify brand owner</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Resolve</a></div></div></td></tr><tr><td><b>#RPT-8841</b></td><td>Prohibited item — e-cigarette listed as gadget</td><td><span className="badge badge-red">Prohibited item</span></td><td><b>Vape Kit 5000 puffs</b><p className="text-[11px] text-ink-400">Gadget World BD</p></td><td>AI system</td><td>Auto-detected keywords</td><td><span className="badge badge-red">High</span></td><td>Unassigned</td><td>4 hrs</td><td><span className="st st-new">Open</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Remove listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>Assign to me</a></div></div></td></tr><tr><td><b>#RPT-8840</b></td><td>Seller asking to pay outside the platform</td><td><span className="badge badge-amber">Off-platform selling</span></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Style Hub</p><p className="text-[11.5px] text-ink-400">#VND-1240</p></div></div></td><td>Customer — Nusrat J.</td><td>Chat screenshot</td><td><span className="badge badge-red">High</span></td><td>Sabbir Ahmed</td><td>6 hrs</td><td><span className="st st-hold">Investigating</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  data-modal-open="m-abuse"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>View chat log</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Add strike</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Suspend vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Resolve</a></div></div></td></tr><tr><td><b>#RPT-8839</b></td><td>Misleading discount — price inflated before sale</td><td><span className="badge badge-amber">Misleading listing</span></td><td><b>Smart LED TV 43"</b><p className="text-[11px] text-ink-400">Mobile Zone</p></td><td>Staff — Rashed K.</td><td>Price history chart</td><td><span className="badge badge-amber">Medium</span></td><td>Nafisa Karim</td><td>1 day</td><td><span className="st st-new">Open</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Price history</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Force price correction</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn vendor</a></div></div></td></tr><tr><td><b>#RPT-8838</b></td><td>Technician behaved rudely at customer home</td><td><span className="badge badge-red">Unsafe service</span></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Quick Fix BD</p><p className="text-[11.5px] text-ink-400">#VND-2240</p></div></div></td><td>Customer — Farhana A.</td><td>Call recording + note</td><td><span className="badge badge-red">High</span></td><td>Mehedi Hasan</td><td>1 day</td><td><span className="st st-hold">Investigating</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>Listen to recording</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Suspend provider</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Refund booking</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Resolve</a></div></div></td></tr><tr><td><b>#RPT-8837</b></td><td>Abusive language in review</td><td><span className="badge badge-amber">Abusive review</span></td><td><b>Review #RV-48620</b></td><td>Vendor — Rahim Electric</td><td>Review text</td><td><span className="badge badge-gray">Low</span></td><td>Auto</td><td>2 days</td><td><span className="st st-done">Resolved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-abuse"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View resolution</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reopen</a></div></div></td></tr><tr><td><b>#RPT-8836</b></td><td>Copyright claim on product photos</td><td><span className="badge badge-amber">Copyright</span></td><td><b>18 listings</b><p className="text-[11px] text-ink-400">Multiple vendors</p></td><td>Walton BD (brand owner)</td><td>DMCA notice PDF</td><td><span className="badge badge-amber">Medium</span></td><td>Legal team</td><td>3 days</td><td><span className="st st-done">Resolved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-abuse"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>View resolution</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download notice</a></div></div></td></tr><tr><td><b>#RPT-8835</b></td><td>Appeal against suspension</td><td><span className="badge badge-blue">Appeal</span></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Fake Store BD</p><p className="text-[11.5px] text-ink-400">#VND-1442</p></div></div></td><td>Vendor</td><td>Explanation + documents</td><td><span className="badge badge-amber">Medium</span></td><td>Aminul Islam</td><td>4 days</td><td><span className="st st-new">Open</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review appeal</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Reinstate vendor</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Uphold suspension</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request documents</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–8</b> of <b>12</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>2</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Enforcement policy — strike system</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Strike</th><th>Action</th><th>Duration</th></tr></thead>
      <tbody><tr><td><b>1st strike</b></td><td>Warning email + listing removed</td><td>—</td></tr><tr><td><b>2nd strike</b></td><td>Search visibility reduced 50%</td><td>7 days</td></tr><tr><td><b>3rd strike</b></td><td>New listings blocked</td><td>14 days</td></tr><tr><td><b>4th strike</b></td><td>Shop suspended, payouts held</td><td>30 days</td></tr><tr><td><b>5th strike</b></td><td>Permanent ban + payout forfeit review</td><td>Permanent</td></tr></tbody></table></div>
      <div className="p-3"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Strike expiry</span><b className="text-right">After 180 days of good behaviour</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Appeal window</span><b className="text-right">14 days</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Payout hold on suspension</span><b className="text-right">Yes — until case closes</b></div></div></div></div></div><div className="card "><div className="card-head"><h3>Prohibited items list</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Weapons & ammunition</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "100%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Tobacco & vape</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "92%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Medicines (Rx)</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "84%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Restricted</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Adult products</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "78%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Counterfeit goods</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "100%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Live animals</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "68%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Currency / crypto</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "62%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Hazardous chemicals</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "74%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Blocked</span></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit prohibited list</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Keyword blocklist</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>AI detection settings</button></div></div></div><div className="card "><div className="card-head"><h3>Case handling</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Default SLA — high priority</label><input type="text" className="input" placeholder="4 hours" /></div><div className=""><label className="label">Default SLA — medium</label><input type="text" className="input" placeholder="24 hours" /></div><div className=""><label className="label">Auto-assign</label><select className="select"><option>Round robin</option><option>By category expertise</option><option>Manual</option></select></div><div className=""><label className="label">Escalation manager</label><select className="select"><option>Aminul Islam</option><option>Rashed Kabir</option></select></div></div>
      <div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Auto-remove AI-confirmed counterfeits</p><p className="fs">Confidence above 95% removes the listing immediately.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Hold payouts during investigation</p><p className="fs">Freeze vendor payouts on high-priority cases.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Notify reporter of outcome</p><p className="fs">Send a resolution email to the reporter.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Allow vendor appeals</p><p className="fs">Vendors can appeal within 14 days.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Log all enforcement actions</p><p className="fs">Immutable audit trail.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div></div>
      
      <div className="modal" id="m-abuse"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Report #RPT-9042 — counterfeit claim</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reported item</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Fake "Samsung" Charger 25W · #PRD-882104</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Vendor</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Mobile Zone · #VND-3311</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reported by</span><span className="text-[12.5px] font-bold text-ink-800 text-right">3 users + 1 brand owner</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Category</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Counterfeit / IP infringement</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Evidence</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Brand authorisation letter, 6 photos</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Item status</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="st st-hold">Blocked</span></span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Vendor strikes</span><span className="text-[12.5px] font-bold text-ink-800 text-right">2 previous</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Exposure</span><span className="text-[12.5px] font-bold text-ink-800 text-right">42 orders · ৳37,380 GMV</span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Action on listing</label><select className="select"><option>Keep blocked</option><option>Delete permanently</option><option>Unblock (claim invalid)</option><option>Require documents</option></select></div><div className=""><label className="label">Action on vendor</label><select className="select"><option>Warning (strike 3)</option><option>Suspend 30 days</option><option>Suspend indefinitely</option><option>Terminate account</option><option>No action</option></select></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Refund affected orders</label><select className="select"><option>Yes — all 42 orders</option><option>Yes — last 30 days only</option><option>No</option></select></div><div className=""><label className="label">Notify brand owner</label><select className="select"><option>Yes, with outcome</option><option>No</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Case note</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Report resolved">Apply decision</button></div></div></div>
    </>
  );
}
