export default function ProductApprovalsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Product approvals</span></nav>
      <h1>Product Approvals</h1><p>Review new and edited listings before they go live.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Approval rules</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>Assign to me</button><button className="btn btn-sm btn-primary"  data-modal-open="m-rej"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Bulk approve safe listings</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">86</p><p className="lbl">Pending review</p><p className="text-[11.5px] text-ink-400 mt-1.5">Oldest: 6 hours ago</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></span>
      </div>
      <p className="val">24</p><p className="lbl">Auto-flagged</p><p className="text-[11.5px] text-ink-400 mt-1.5">Restricted keywords / price</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+12%</span></div>
      <p className="val">184</p><p className="lbl">Approved today</p><p className="text-[11.5px] text-ink-400 mt-1.5">By 6 reviewers</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></span>
      </div>
      <p className="val">18</p><p className="lbl">Rejected today</p><p className="text-[11.5px] text-ink-400 mt-1.5">Top reason: poor images</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">Queue<span className="count">86</span></button><button className="tab " data-tab="t1">Auto-flagged<span className="count">24</span></button><button className="tab " data-tab="t2">Edited listings<span className="count">18</span></button><button className="tab " data-tab="t3">Escalated<span className="count">4</span></button><button className="tab " data-tab="t4">Approved<span className="count">184</span></button><button className="tab " data-tab="t5">Rejected<span className="count">18</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Electronics</option><option>Fashion</option><option>Grocery</option><option>Health</option></select><select className="select input-sm !w-auto"><option>All vendors</option><option>New vendors only</option><option>Verified vendors</option></select><select className="select input-sm !w-auto"><option>Priority: All</option><option>High value</option><option>Flagged</option><option>Oldest first</option></select><select className="select input-sm !w-auto"><option>Assigned: Anyone</option><option>Assigned to me</option><option>Unassigned</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg>Grid view</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Table view</button></div></div></div><div className="grid lg:grid-cols-2 gap-4 mb-4">
      <div className="card p-4">
      <div className="flex gap-3.5">
      <div className="w-[92px] shrink-0"><span className="ph ph-a "><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">Product</svg></span><p className="text-[11px] text-ink-400 text-center mt-1">9 images</p></div>
      <div className="min-w-0 flex-1"><div className="flex items-start gap-2"><p className="text-[13.5px] font-extrabold clamp-2 flex-1">Xiaomi Redmi Note 13 Pro 8/256GB — Global Version</p><span className="text-[11px] text-ink-400 shrink-0">2 hours ago</span></div>
      <p className="text-[12px] text-ink-500 mt-0.5">Gadget World BD (Verified) · Mobile › Smartphones</p>
      <div className="flex flex-wrap gap-1.5 mt-2"><span className="badge badge-blue">New listing</span><span className="badge badge-green">Price within range</span><span className="badge badge-green">Brand authorised</span></div>
      <div className="flex flex-wrap items-center gap-2 mt-2.5"><b className="text-[14px] text-brand-600">৳32,990</b>
      <span className="text-[11.5px] text-ink-400">Commission 8% · MRP verified</span></div>
      <div className="flex flex-wrap gap-1.5 mt-3">
      <button className="btn btn-xs btn-primary" data-toast="Product approved"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Approve with edits</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request info</button>
      <button className="btn btn-xs btn-outline text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button>
      <button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Full preview</button></div></div></div></div>
      <div className="card p-4">
      <div className="flex gap-3.5">
      <div className="w-[92px] shrink-0"><span className="ph ph-b "><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">Product</svg></span><p className="text-[11px] text-ink-400 text-center mt-1">5 images</p></div>
      <div className="min-w-0 flex-1"><div className="flex items-start gap-2"><p className="text-[13.5px] font-extrabold clamp-2 flex-1">Apple iPhone 15 Pro Max 256GB (Refurbished)</p><span className="text-[11px] text-ink-400 shrink-0">4 hours ago</span></div>
      <p className="text-[12px] text-ink-500 mt-0.5">Mobile Zone (New vendor) · Mobile › Smartphones</p>
      <div className="flex flex-wrap gap-1.5 mt-2"><span className="badge badge-amber">Auto-flagged: high value</span><span className="badge badge-amber">Refurbished claim</span><span className="badge badge-red">Brand authorisation missing</span></div>
      <div className="flex flex-wrap items-center gap-2 mt-2.5"><b className="text-[14px] text-brand-600">৳1,42,000</b>
      <span className="text-[11.5px] text-ink-400">Commission 8% · MRP verified</span></div>
      <div className="flex flex-wrap gap-1.5 mt-3">
      <button className="btn btn-xs btn-primary" data-toast="Product approved"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Approve with edits</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request info</button>
      <button className="btn btn-xs btn-outline text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button>
      <button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Full preview</button></div></div></div></div>
      <div className="card p-4">
      <div className="flex gap-3.5">
      <div className="w-[92px] shrink-0"><span className="ph ph-c "><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">Product</svg></span><p className="text-[11px] text-ink-400 text-center mt-1">4 images</p></div>
      <div className="min-w-0 flex-1"><div className="flex items-start gap-2"><p className="text-[13.5px] font-extrabold clamp-2 flex-1">Herbal Slimming Tea — Fast Weight Loss 15 Days</p><span className="text-[11px] text-ink-400 shrink-0">5 hours ago</span></div>
      <p className="text-[12px] text-ink-500 mt-0.5">Natural Care BD · Health › Supplements</p>
      <div className="flex flex-wrap gap-1.5 mt-2"><span className="badge badge-red">Restricted keyword: "weight loss"</span><span className="badge badge-amber">Health claim needs approval</span><span className="badge badge-amber">BSTI certificate pending</span></div>
      <div className="flex flex-wrap items-center gap-2 mt-2.5"><b className="text-[14px] text-brand-600">৳890</b>
      <span className="text-[11.5px] text-ink-400">Commission 8% · MRP verified</span></div>
      <div className="flex flex-wrap gap-1.5 mt-3">
      <button className="btn btn-xs btn-primary" data-toast="Product approved"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Approve with edits</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request info</button>
      <button className="btn btn-xs btn-outline text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button>
      <button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Full preview</button></div></div></div></div>
      <div className="card p-4">
      <div className="flex gap-3.5">
      <div className="w-[92px] shrink-0"><span className="ph ph-d "><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">Product</svg></span><p className="text-[11px] text-ink-400 text-center mt-1">12 images</p></div>
      <div className="min-w-0 flex-1"><div className="flex items-start gap-2"><p className="text-[13.5px] font-extrabold clamp-2 flex-1">Premium Cotton Panjabi — Eid Collection 2026</p><span className="text-[11px] text-ink-400 shrink-0">6 hours ago</span></div>
      <p className="text-[12px] text-ink-500 mt-0.5">Style Hub (Verified) · Fashion › Men › Panjabi</p>
      <div className="flex flex-wrap gap-1.5 mt-2"><span className="badge badge-blue">New listing</span><span className="badge badge-green">Images verified</span><span className="badge badge-green">Size chart provided</span></div>
      <div className="flex flex-wrap items-center gap-2 mt-2.5"><b className="text-[14px] text-brand-600">৳2,450</b>
      <span className="text-[11.5px] text-ink-400">Commission 8% · MRP verified</span></div>
      <div className="flex flex-wrap gap-1.5 mt-3">
      <button className="btn btn-xs btn-primary" data-toast="Product approved"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Approve with edits</button>
      <button className="btn btn-xs btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request info</button>
      <button className="btn btn-xs btn-outline text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button>
      <button className="btn btn-xs btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Full preview</button></div></div></div></div></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Approval queue (table view)</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg>Bulk actions</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th className="w-8"></th><th>Product</th><th>Vendor</th><th>Category</th><th>Price</th><th>Flags</th><th>Submitted</th><th>Assigned</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><label className="chk"><input type="checkbox" /><span></span></label></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Samsung 43" Smart TV UA43T5400</p><p className="text-[11.5px] text-ink-400">9 images · 3 variants</p></div></div></td><td>Gadget World BD</td><td>Electronics › TV</td><td>৳42,900</td><td><span className="badge badge-green">Clean</span></td><td>1 hour ago</td><td>Unassigned</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><label className="chk"><input type="checkbox" /><span></span></label></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Imported Baby Formula 900g</p><p className="text-[11.5px] text-ink-400">5 images</p></div></div></td><td>Fresh Mart</td><td>Grocery › Baby food</td><td>৳3,200</td><td><span className="badge badge-red">Import doc missing</span></td><td>3 hours ago</td><td>Nafisa K.</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request doc</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><label className="chk"><input type="checkbox" /><span></span></label></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Gaming Chair RGB Pro Max</p><p className="text-[11.5px] text-ink-400">11 images</p></div></div></td><td>Furniture Hub</td><td>Home › Furniture</td><td>৳18,900</td><td><span className="badge badge-amber">Duplicate suspected</span></td><td>4 hours ago</td><td>Sabbir A.</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg>Compare duplicate</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><label className="chk"><input type="checkbox" /><span></span></label></td><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Handmade Nakshi Kantha Bedcover</p><p className="text-[11.5px] text-ink-400">7 images</p></div></div></td><td>Craft Bangladesh</td><td>Home › Bedding</td><td>৳4,600</td><td><span className="badge badge-green">Clean</span></td><td>6 hours ago</td><td>Unassigned</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a></div></div></td></tr></tbody></table></div></div><div className="card "><div className="card-head"><h3>Rejection reasons & rules</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><p className="text-[12px] font-extrabold uppercase tracking-wide text-ink-400 mb-2">Top rejection reasons (30 days)</p>
      <div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Poor image quality</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "84%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">142</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Incomplete specifications</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "68%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">116</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Prohibited / restricted item</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "52%", background: "#b42318"}}></i></span>
      <span className="num text-right font-bold text-ink-800">88</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Wrong category</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "44%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">74</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Counterfeit suspicion</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "38%", background: "#8b5cf6"}}></i></span>
      <span className="num text-right font-bold text-ink-800">64</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Misleading title/claims</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "32%", background: "#6c7a91"}}></i></span>
      <span className="num text-right font-bold text-ink-800">54</span></div></div>
      <p className="text-[12px] font-extrabold uppercase tracking-wide text-ink-400 mt-4 mb-2">Automation rules</p>
      <div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Auto-approve trusted vendors</p><p className="fs">Vendors with 4.5+ rating & 100+ clean listings.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Auto-flag restricted keywords</p><p className="fs">Weight loss, medicine, weapons, tobacco, crypto.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Auto-flag price anomalies</p><p className="fs">Price 60% below or 200% above category median.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Require brand authorisation</p><p className="fs">For 42 protected brands.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Image AI check</p><p className="fs">Detect watermark, collage and stock photos.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div></div></div></div><div className="modal" id="m-rej"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Reject listing</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Rejection reason *</label><select className="select"><option>Poor image quality</option><option>Incomplete information</option><option>Prohibited item</option><option>Wrong category</option><option>Counterfeit / unauthorised brand</option><option>Misleading title or claims</option><option>Price manipulation</option><option>Duplicate listing</option><option>Other</option></select></div><div className=""><label className="label">Severity</label><select className="select"><option>Soft — vendor can resubmit</option><option>Warning — counts against vendor score</option><option>Strict — vendor suspension review</option></select></div><div className="sm:col-span-2"><label className="label">Message to vendor *</label><textarea className="textarea !min-h-[90px]" placeholder="Explain clearly what must be fixed before resubmission"></textarea></div><div className="sm:col-span-2"><label className="label">Internal note</label><textarea className="textarea !min-h-[90px]" placeholder="Visible to admins only"></textarea></div><div className="sm:col-span-2 flex flex-wrap gap-4"><label className="check"><input type="checkbox" defaultChecked />Email vendor</label><label className="check"><input type="checkbox" defaultChecked />Add to vendor violation log</label><label className="check"><input type="checkbox"   />Block similar listings automatically</label></div></div><div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Listing rejected">Reject listing</button></div></div></div>
    </>
  );
}
