export default function ProductsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Products</span></nav>
      <h1>Products</h1><p>Every product listing across all vendors on the marketplace.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Import CSV</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add product</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 2h12l1 5H5z"/><path d="M5 7v15h14V7"/><path d="M9 12h6"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+11%</span></div>
      <p className="val">3,90,000</p><p className="lbl">Total products</p><p className="text-[11.5px] text-ink-400 mt-1.5">Across 8,642 vendors</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+9%</span></div>
      <p className="val">3,42,180</p><p className="lbl">Live & in stock</p><p className="text-[11.5px] text-ink-400 mt-1.5">87.7% of catalog</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+4%</span></div>
      <p className="val">32,420</p><p className="lbl">Out of stock</p><p className="text-[11.5px] text-ink-400 mt-1.5">Auto-hidden from search</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg></span>
      </div>
      <p className="val">2,860</p><p className="lbl">Blocked / removed</p><p className="text-[11.5px] text-ink-400 mt-1.5">Policy violations</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All<span className="count">3,90,000</span></button><button className="tab " data-tab="t1">Live<span className="count">3,42,180</span></button><button className="tab " data-tab="t2">Pending approval<span className="count">86</span></button><button className="tab " data-tab="t3">Draft<span className="count">12,480</span></button><button className="tab " data-tab="t4">Out of stock<span className="count">32,420</span></button><button className="tab " data-tab="t5">Rejected<span className="count">1,842</span></button><button className="tab " data-tab="t6">Blocked<span className="count">2,860</span></button><button className="tab " data-tab="t7">Reported<span className="count">124</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Electronics</option><option>Fashion</option><option>Home & Kitchen</option><option>Grocery</option><option>Health & Beauty</option><option>Mobile & Gadgets</option></select><select className="select input-sm !w-auto"><option>All vendors</option><option>Rahim Electric</option><option>Gadget World BD</option><option>Style Hub</option><option>Fresh Mart</option></select><select className="select input-sm !w-auto"><option>All brands</option><option>Samsung</option><option>Walton</option><option>Realme</option><option>Gree</option></select><select className="select input-sm !w-auto"><option>All statuses</option><option>Live</option><option>Pending</option><option>Rejected</option><option>Blocked</option></select><select className="select input-sm !w-auto"><option>Stock: All</option><option>In stock</option><option>Low stock</option><option>Out of stock</option></select><input type="date" className="input input-sm !w-auto" /><select className="select input-sm !w-auto"><option>Sort: Newest</option><option>Best selling</option><option>Most viewed</option><option>Price high–low</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">save</svg>Saved filters</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Approve</button><button className="btn btn-xs btn-outline">Reject</button><button className="btn btn-xs btn-outline">Block listing</button><button className="btn btn-xs btn-outline">Feature product</button><button className="btn btn-xs btn-outline">Change category</button><button className="btn btn-xs btn-outline">Recalculate commission</button><button className="btn btn-xs btn-outline">Reindex search</button><button className="btn btn-xs btn-outline">Export</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Product</th><th>SKU / ID</th><th>Vendor</th><th>Category</th><th>Brand</th><th>Price</th><th>Commission</th><th>Stock</th><th>Sold</th><th>Views</th><th>Rating</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Realme C100X 6/128GB 8000mAh</p><p className="text-[11.5px] text-ink-400">Added 12 Aug 2026 · 8 images · 2 variants</p></div></div></td><td><code className="text-[11px]">RC100X-BLK</code><p className="text-[11px] text-ink-400">#PRD-884213</p></td><td><a href="/admin/vendors" className="link">Rahim Electric</a></td><td>Mobile › Smartphones</td><td>Realme</td><td><b>৳11,290</b><p className="text-[11px] text-ink-400 line-through">৳13,990</p></td><td>8% · ৳903</td><td><b>124</b></td><td>842</td><td>48.2K</td><td>4.8 ★ (312)</td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/></svg>Change category</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 19 14-14"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/></svg>Set commission</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="9" r="5"/><path d="m8.5 13.5-1.5 7 5-3 5 3-1.5-7"/></svg>Feature product</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Boost in search</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block listing</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Gree 1.5 Ton Inverter AC GS-18XPUV</p><p className="text-[11.5px] text-ink-400">Added 02 Aug 2026 · 12 images</p></div></div></td><td><code className="text-[11px]">GREE-18XPUV</code><p className="text-[11px] text-ink-400">#PRD-884102</p></td><td><a href="/admin/vendors" className="link">Rahim Electric</a></td><td>Home › Air conditioner</td><td>Gree</td><td><b>৳68,900</b></td><td>6% · ৳4,134</td><td><b className="text-brand-600">2</b></td><td>184</td><td>32.4K</td><td>4.9 ★ (86)</td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  data-modal-open="m-stock"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Low stock alert</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Block listing</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Xiaomi Redmi Note 13 Pro 8/256GB</p><p className="text-[11.5px] text-ink-400">Submitted 17 Aug 2026 · awaiting review</p></div></div></td><td><code className="text-[11px]">RN13P-256</code><p className="text-[11px] text-ink-400">#PRD-884401</p></td><td><a href="/admin/vendors" className="link">Gadget World BD</a></td><td>Mobile › Smartphones</td><td>Xiaomi</td><td><b>৳32,990</b></td><td>8% · ৳2,639</td><td>48</td><td>—</td><td>—</td><td>—</td><td><span className="st st-pending">Pending</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Request changes</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Premium Jamdani Saree — Handloom</p><p className="text-[11.5px] text-ink-400">Added 28 Jul 2026 · 6 images</p></div></div></td><td><code className="text-[11px]">JAM-SR-042</code><p className="text-[11px] text-ink-400">#PRD-883210</p></td><td><a href="/admin/vendors" className="link">Style Hub</a></td><td>Fashion › Sarees</td><td>Local artisan</td><td><b>৳8,450</b></td><td>12% · ৳1,014</td><td><b>36</b></td><td>284</td><td>18.6K</td><td>4.7 ★ (142)</td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="9" r="5"/><path d="m8.5 13.5-1.5 7 5-3 5 3-1.5-7"/></svg>Feature product</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Fake "Samsung" Charger 25W</p><p className="text-[11.5px] text-ink-400">Reported 3 times · counterfeit claim</p></div></div></td><td><code className="text-[11px]">CHG-25W-X</code><p className="text-[11px] text-ink-400">#PRD-882104</p></td><td><a href="/admin/vendors" className="link">Mobile Zone</a></td><td>Mobile › Accessories</td><td>Samsung (claimed)</td><td>৳890</td><td>10%</td><td>0</td><td>42</td><td>8.2K</td><td>2.1 ★ (18)</td><td><span className="st st-hold">Blocked</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>View report</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Unblock</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg>Warn vendor</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14"/></svg>Delete permanently</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-f w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Walton Fridge WFC-3F5-GDXX 358L</p><p className="text-[11.5px] text-ink-400">Added 14 Jul 2026</p></div></div></td><td><code className="text-[11px]">WFC-3F5</code><p className="text-[11px] text-ink-400">#PRD-881420</p></td><td><a href="/admin/vendors" className="link">Walton Plaza</a></td><td>Home › Refrigerator</td><td>Walton</td><td><b>৳54,900</b></td><td>5% · ৳2,745</td><td><b>18</b></td><td>96</td><td>24.8K</td><td>4.6 ★ (64)</td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 19 14-14"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/></svg>Set commission</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-g w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Organic Honey 500g — Sundarban</p><p className="text-[11.5px] text-ink-400">Rejected 15 Aug · missing BSTI certificate</p></div></div></td><td><code className="text-[11px]">HNY-500</code><p className="text-[11px] text-ink-400">#PRD-884288</p></td><td><a href="/admin/vendors" className="link">Fresh Mart</a></td><td>Grocery › Honey</td><td>Local</td><td>৳680</td><td>15%</td><td>—</td><td>—</td><td>—</td><td>—</td><td><span className="st st-cancel">Rejected</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-product"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg>View reason</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Re-review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Message vendor</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–7</b> of <b>390000</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>39000</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Catalog quality</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">Complete listings (all fields)</span><b>78%</b></div><div className="pbar"><i style={{width: "78%"}}></i></div></div><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">With 5+ images</span><b>64%</b></div><div className="pbar"><i style={{width: "64%"}}></i></div></div><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">With video</span><b>18%</b></div><div className="pbar"><i style={{width: "18%"}}></i></div></div><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">With full specifications</span><b>71%</b></div><div className="pbar"><i style={{width: "71%"}}></i></div></div><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">With warranty info</span><b>58%</b></div><div className="pbar"><i style={{width: "58%"}}></i></div></div><div className="mb-2.5"><div className="flex justify-between text-[12px] mb-1"><span className="font-semibold">SEO-optimised title</span><b>82%</b></div><div className="pbar"><i style={{width: "82%"}}></i></div></div>
      <div className="flex gap-2 mt-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Quality report</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify vendors</button></div></div></div><div className="card "><div className="card-head"><h3>Listings by category</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Fashion & Lifestyle</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "92%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">1,12,480</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Electronics</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "78%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">86,240</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Home & Kitchen</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "64%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">68,420</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Health & Beauty</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "48%", background: "#8b5cf6"}}></i></span>
      <span className="num text-right font-bold text-ink-800">42,180</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Grocery</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "38%", background: "#6c7a91"}}></i></span>
      <span className="num text-right font-bold text-ink-800">32,640</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Others</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "44%", background: "#b42318"}}></i></span>
      <span className="num text-right font-bold text-ink-800">48,040</span></div></div></div></div><div className="card "><div className="card-head"><h3>Bulk tools</h3><div className="flex items-center gap-2"></div></div><div className="p-4 space-y-2"><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg><span className="text-[12.5px] font-semibold flex-1">Import products (CSV/Excel)</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg><span className="text-[12.5px] font-semibold flex-1">Bulk price update</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/></svg><span className="text-[12.5px] font-semibold flex-1">Bulk category re-map</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 19 14-14"/><circle cx="7.5" cy="7.5" r="2.5"/><circle cx="16.5" cy="16.5" r="2.5"/></svg><span className="text-[12.5px] font-semibold flex-1">Bulk commission override</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg><span className="text-[12.5px] font-semibold flex-1">Re-index search catalog</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg><span className="text-[12.5px] font-semibold flex-1">Detect duplicate listings</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg><span className="text-[12.5px] font-semibold flex-1">Find prohibited keywords</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button><button className="w-full flex items-center gap-2.5 p-2.5 rounded-xl border border-[#e7e9ef] text-left hover:border-brand-300">
      <svg className="w-4 h-4 text-ink-400 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 19 5.5-5.5 4 4L17 14l3 3"/></svg><span className="text-[12.5px] font-semibold flex-1">Image quality scan</span><svg className="w-3.5 h-3.5 text-ink-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></button></div></div></div>
      
      <div className="modal" id="m-product"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Listing review — Realme C100X 6/128GB</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5 flex gap-3.5"><span className="ph ph-a w-[92px] h-[92px] rounded-xl shrink-0"></span>
      <div className="min-w-0"><p className="text-[14px] font-extrabold">Realme C100X 6/128GB 8000mAh 45W</p>
      <p className="text-[12px] text-ink-400 mb-1.5">Mobile › Smartphones · Realme · SKU RC100X-BLK</p>
      <p className="text-[15px] font-extrabold text-brand-600">৳11,290 <span className="text-[12px] text-ink-400 line-through font-semibold">৳13,990</span></p></div></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Submitted by</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Rahim Electric · 12 Aug 2026</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Images / video</span><span className="text-[12.5px] font-bold text-ink-800 text-right">8 images · 1 video</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Variants</span><span className="text-[12.5px] font-bold text-ink-800 text-right">2 (Black, Blue)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Stock</span><span className="text-[12.5px] font-bold text-ink-800 text-right">124 units · Dhaka warehouse</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Warranty</span><span className="text-[12.5px] font-bold text-ink-800 text-right">1 year official</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Auto-checks</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-green">Title OK</span> <span className="badge badge-green">Images OK</span> <span className="badge badge-amber">Price outlier</span></span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Duplicate match</span><span className="text-[12.5px] font-bold text-ink-800 text-right">None found</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Restricted keywords</span><span className="text-[12.5px] font-bold text-ink-800 text-right">None</span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Decision</label><select className="select"><option>Approve &amp; publish</option><option>Approve with edits</option><option>Request changes</option><option>Reject</option></select></div><div className=""><label className="label">Assign reviewer</label><select className="select"><option>Me (Arif H.)</option><option>Nafisa K.</option><option>Sabbir A.</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Message to vendor</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Decision saved">Submit decision</button></div></div></div>
      <div className="modal" id="m-stock"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Adjust stock — Realme C100X 6/128GB</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Current on hand</span><span className="text-[12.5px] font-bold text-ink-800 text-right">124 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reserved (unshipped)</span><span className="text-[12.5px] font-bold text-ink-800 text-right">18 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Available to sell</span><span className="text-[12.5px] font-bold text-ink-800 text-right">106 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Warehouse</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Dhaka — Tejgaon (primary)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Reorder level</span><span className="text-[12.5px] font-bold text-ink-800 text-right">25 units</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Last count</span><span className="text-[12.5px] font-bold text-ink-800 text-right">18 Aug 2026 by Sabbir A.</span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Adjustment type</label><select className="select"><option>Add stock (received)</option><option>Remove (damaged)</option><option>Remove (lost)</option><option>Set absolute count</option><option>Transfer warehouse</option></select></div><div className=""><label className="label">Quantity</label><input type="number" className="input" /></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Warehouse</label><select className="select"><option>Dhaka — Tejgaon</option><option>Chattogram — Agrabad</option><option>Sylhet hub</option></select></div><div className=""><label className="label">Reference</label><input type="text" className="input" placeholder="GRN / invoice no." /></div></div>
      <div className="px-5"><div className=""><label className="label">Reason / note</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Stock updated">Apply adjustment</button></div></div></div>
    </>
  );
}
