export default function ServicesPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Service listings</span></nav>
      <h1>Service Listings</h1><p>All directory listings from service providers across Bangladesh.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Import listings</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Add listing</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">briefcase</svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+9%</span></div>
      <p className="val">1,24,000</p><p className="lbl">Total listings</p><p className="text-[11.5px] text-ink-400 mt-1.5">In 64 districts</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+12%</span></div>
      <p className="val">86,420</p><p className="lbl">Verified listings</p><p className="text-[11.5px] text-ink-400 mt-1.5">69.7% verified</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">142</p><p className="lbl">Pending approval</p><p className="text-[11.5px] text-ink-400 mt-1.5">Oldest: 2 days</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></span>
      </div>
      <p className="val">68</p><p className="lbl">Claim requests</p><p className="text-[11.5px] text-ink-400 mt-1.5">Business ownership claims</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">All<span className="count">1,24,000</span></button><button className="tab " data-tab="t1">Live<span className="count">1,18,240</span></button><button className="tab " data-tab="t2">Pending<span className="count">142</span></button><button className="tab " data-tab="t3">Unverified<span className="count">37,580</span></button><button className="tab " data-tab="t4">Claim requests<span className="count">68</span></button><button className="tab " data-tab="t5">Suspended<span className="count">842</span></button><button className="tab " data-tab="t6">Reported<span className="count">96</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Restaurants</option><option>Home services</option><option>Health</option><option>Education</option><option>Beauty & Spa</option><option>Automotive</option><option>Events</option></select><select className="select input-sm !w-auto"><option>All cities</option><option>Dhaka</option><option>Chittagong</option><option>Sylhet</option><option>Khulna</option><option>Rajshahi</option></select><select className="select input-sm !w-auto"><option>All areas</option><option>Gulshan</option><option>Dhanmondi</option><option>Uttara</option><option>Banani</option></select><select className="select input-sm !w-auto"><option>All plans</option><option>Free</option><option>Silver</option><option>Gold</option><option>Platinum</option></select><select className="select input-sm !w-auto"><option>All statuses</option><option>Live</option><option>Pending</option><option>Suspended</option></select><select className="select input-sm !w-auto"><option>Verification: All</option><option>Verified</option><option>Unverified</option></select><select className="select input-sm !w-auto"><option>Sort: Newest</option><option>Most leads</option><option>Highest rated</option><option>Most viewed</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">map</svg>Map view</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="bulkbar"><span className="text-[12.5px] font-bold"><b data-sel-count>3</b> selected</span>
      <button className="btn btn-xs btn-outline">Approve</button><button className="btn btn-xs btn-outline">Verify</button><button className="btn btn-xs btn-outline">Feature listing</button><button className="btn btn-xs btn-outline">Change category</button><button className="btn btn-xs btn-outline">Assign plan</button><button className="btn btn-xs btn-outline">Suspend</button><button className="btn btn-xs btn-outline">Export</button>
      <button className="btn btn-xs btn-ghost ml-auto">Clear</button></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Business</th><th>Category</th><th>Location</th><th>Plan</th><th>Contact</th><th>Leads (30d)</th><th>Bookings</th><th>Views</th><th>Rating</th><th>Verified</th><th>Status</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Shree Rath Pure Veg Restaurant</p><p className="text-[11.5px] text-ink-400">Listed 12 Mar 2025 · 24 photos · Menu uploaded</p></div></div></td><td>Restaurants › Pure Veg</td><td>Ambernath, Dhaka</td><td><span className="badge badge-amber">Platinum</span></td><td>01711-000111<p className="text-[11px] text-ink-400">Verified phone</p></td><td><b>284</b></td><td>86</td><td>48.2K</td><td>4.6 ★ (1,284)</td><td><span className="badge badge-green">Verified</span></td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Verification docs</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="9" r="5"/><path d="m8.5 13.5-1.5 7 5-3 5 3-1.5-7"/></svg>Change plan</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Boost visibility</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="8" r="3.2"/><path d="M2 21a7 7 0 0 1 14 0"/><path d="M16 11a3 3 0 1 0 0-6M18 21a6 6 0 0 0-2-4.5"/></svg>View leads</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Suspend</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Dhaka AC Service & Repair</p><p className="text-[11.5px] text-ink-400">Listed 08 Jan 2026 · 18 photos</p></div></div></td><td>Home services › AC repair</td><td>Mirpur, Dhaka</td><td><span className="badge badge-amber">Gold</span></td><td>01811-222333</td><td><b>412</b></td><td>184</td><td>62.4K</td><td>4.8 ★ (642)</td><td><span className="badge badge-green">Verified</span></td><td>A =&gt; A</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>View bookings</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Green Life Diagnostic Centre</p><p className="text-[11.5px] text-ink-400">Listed 22 Feb 2026 · 12 photos</p></div></div></td><td>Health › Diagnostics</td><td>Dhanmondi, Dhaka</td><td><span className="badge badge-amber">Gold</span></td><td>01911-444555</td><td><b>186</b></td><td>242</td><td>38.6K</td><td>4.5 ★ (386)</td><td><span className="badge badge-green">Verified</span></td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Licence documents</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Prime Coaching Centre</p><p className="text-[11.5px] text-ink-400">Submitted 20 Aug 2026 · awaiting review</p></div></div></td><td>Education › Coaching</td><td>Uttara, Dhaka</td><td><span className="badge badge-gray">Free</span></td><td>01611-666777<p className="text-[11px] text-brand-600">Unverified</p></td><td>—</td><td>—</td><td>—</td><td>—</td><td><span className="badge badge-amber">Pending</span></td><td><span className="st st-pending">Pending</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>Verify phone</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Glamour Beauty Parlour</p><p className="text-[11.5px] text-ink-400">Listed 05 Jul 2026 · 32 photos</p></div></div></td><td>Beauty & Spa › Parlour</td><td>Gulshan, Dhaka</td><td><span className="badge badge-gray">Silver</span></td><td>01511-888999</td><td><b>142</b></td><td>96</td><td>24.8K</td><td>4.4 ★ (218)</td><td><span className="badge badge-green">Verified</span></td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>View on site</a><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit listing</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="9" r="5"/><path d="m8.5 13.5-1.5 7 5-3 5 3-1.5-7"/></svg>Upsell plan</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-f w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Rapid Car Rental BD</p><p className="text-[11.5px] text-ink-400">Suspended 12 Aug · fake reviews detected</p></div></div></td><td>Automotive › Car rental</td><td>Banani, Dhaka</td><td><span className="badge badge-amber">Gold</span></td><td>01411-101010</td><td>0</td><td>0</td><td>18.2K</td><td>3.1 ★ (86)</td><td><span className="badge badge-red">Under review</span></td><td><span className="st st-cancel">Suspended</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>View case</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Review evidence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reinstate</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>Blacklist</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-g w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Elite Wedding Planners</p><p className="text-[11.5px] text-ink-400">Claim request from owner · 3 days ago</p></div></div></td><td>Events › Wedding planner</td><td>Bashundhara, Dhaka</td><td><span className="badge badge-gray">Free</span></td><td>01311-121212</td><td>68</td><td>12</td><td>14.6K</td><td>4.2 ★ (48)</td><td><span className="badge badge-amber">Claim pending</span></td><td><span className="st st-hold">Live</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Review claim</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>Contact claimant</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve claim</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject claim</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–7</b> of <b>124000</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>12400</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Listings by city</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Dhaka</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "96%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">52,480</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Chittagong</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "48%", background: "#00b894"}}></i></span>
      <span className="num text-right font-bold text-ink-800">18,240</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Sylhet</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "32%", background: "#ffb020"}}></i></span>
      <span className="num text-right font-bold text-ink-800">11,860</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Khulna</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "26%", background: "#8b5cf6"}}></i></span>
      <span className="num text-right font-bold text-ink-800">9,420</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Rajshahi</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "22%", background: "#6c7a91"}}></i></span>
      <span className="num text-right font-bold text-ink-800">8,120</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Other districts</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "38%", background: "#b42318"}}></i></span>
      <span className="num text-right font-bold text-ink-800">23,880</span></div></div>
      <div className="mt-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">map</svg>Manage locations</button></div></div></div><div className="card "><div className="card-head"><h3>Plan distribution</h3><div className="flex items-center gap-2"></div></div><div className="p-4 flex items-center gap-4"><div className="relative w-[168px] h-[168px] mx-auto"><svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
      <circle cx="50" cy="50" r="42" fill="none" stroke="#eceef2" strokeWidth="13"/>
      <circle cx="50" cy="50" r="42" fill="none" stroke="#c0c4cc" strokeWidth="13" strokeDasharray="163.61414539895642 100.27963750258621" strokeDashoffset="0" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#6c7a91" strokeWidth="13" strokeDasharray="47.50088092227767 216.39290197926496" strokeDashoffset="-163.61414539895642" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#ffb020" strokeWidth="13" strokeDasharray="36.94512960621597 226.94865329532666" strokeDashoffset="-211.1150263212341" strokeLinecap="butt"/><circle cx="50" cy="50" r="42" fill="none" stroke="#ff2525" strokeWidth="13" strokeDasharray="15.833626974092558 248.06015592745007" strokeDashoffset="-248.06015592745007" strokeLinecap="butt"/></svg>
      <div className="absolute inset-0 grid place-items-center text-center"><div><p className="donut-center">1.24L</p><p className="text-[11.5px] text-ink-400">Listings</p></div></div></div>
      <div className="chart-legend justify-center mt-4"><span><i style={{background: "#c0c4cc"}}></i>Free · 62%</span><span><i style={{background: "#6c7a91"}}></i>Silver · 18%</span><span><i style={{background: "#ffb020"}}></i>Gold · 14%</span><span><i style={{background: "#ff2525"}}></i>Platinum · 6%</span></div>
      <div className="flex-1"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Free listings</span><b className="text-right">76,880</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Silver</span><b className="text-right">22,320</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Gold</span><b className="text-right">17,360</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Platinum</span><b className="text-right">7,440</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Plan revenue (MRR)</span><b className="text-right">৳48,20,000</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Upgrade rate</span><b className="text-right">4.8%</b></div></div></div></div></div><div className="card "><div className="card-head"><h3>Verification & quality</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Phone verified</span><b className="text-right">92,480 (74.5%)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Address verified (field visit)</span><b className="text-right">38,420</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Trade licence uploaded</span><b className="text-right">48,620</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">With photos (5+)</span><b className="text-right">68,240</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">With business hours</span><b className="text-right">86,180</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">With price list / menu</span><b className="text-right">32,480</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Duplicate listings detected</span><b className="text-right">1,842</b></div></div>
      <div className="flex gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Verification queue</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M15 5.5A2.5 2.5 0 0 0 12.5 3H5.5A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15"/></svg>Merge duplicates</button></div></div></div></div>
      
      <div className="modal" id="m-service"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Service listing review — AC Repair &amp; Servicing</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Provider</span><span className="text-[12.5px] font-bold text-ink-800 text-right">CoolCare Services · #VND-2210</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Category</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Home services › AC repair</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Coverage</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Dhaka — Dhanmondi, Mohammadpur, Mirpur (+4)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Pricing</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Starting ৳700 · visit charge ৳300</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Team size</span><span className="text-[12.5px] font-bold text-ink-800 text-right">8 technicians</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Licence / trade doc</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Uploaded · verified</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Photos</span><span className="text-[12.5px] font-bold text-ink-800 text-right">12 (workshop + team)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Auto-checks</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-green">Phone verified</span> <span className="badge badge-green">Address geocoded</span> <span className="badge badge-amber">Duplicate name</span></span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Decision</label><select className="select"><option>Approve &amp; publish</option><option>Approve — needs photos</option><option>Request changes</option><option>Reject</option></select></div><div className=""><label className="label">Listing tier</label><select className="select"><option>Free</option><option>Verified</option><option>Sponsored (paid)</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Message to provider</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Listing decision saved">Submit decision</button></div></div></div>
    </>
  );
}
