export default function ServiceApprovalsPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">Service approvals</span></nav>
      <h1>Service Approvals & Claims</h1><p>Approve new listings, verification documents and business ownership claims.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Verification rules</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>Assign reviewer</button><button className="btn btn-sm btn-primary"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve selected</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span>
      </div>
      <p className="val">142</p><p className="lbl">Pending listings</p><p className="text-[11.5px] text-ink-400 mt-1.5">Avg. review time 4.2 hrs</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg></span>
      </div>
      <p className="val">86</p><p className="lbl">Document reviews</p><p className="text-[11.5px] text-ink-400 mt-1.5">Trade licence / NID</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg></span>
      </div>
      <p className="val">68</p><p className="lbl">Ownership claims</p><p className="text-[11.5px] text-ink-400 mt-1.5">Business claim requests</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">map</svg></span>
      </div>
      <p className="val">24</p><p className="lbl">Field visits scheduled</p><p className="text-[11.5px] text-ink-400 mt-1.5">Physical verification</p></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">New listings<span className="count">142</span></button><button className="tab " data-tab="t1">Documents<span className="count">86</span></button><button className="tab " data-tab="t2">Ownership claims<span className="count">68</span></button><button className="tab " data-tab="t3">Field visits<span className="count">24</span></button><button className="tab " data-tab="t4">Approved<span className="count">486</span></button><button className="tab " data-tab="t5">Rejected<span className="count">42</span></button></div><div className="card p-3 mb-4"><div className="filterbar">
      <div className="input-group flex-1 min-w-[200px]"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input className="input input-sm !min-h-[38px]" placeholder="Search…" /></div><select className="select input-sm !w-auto"><option>All categories</option><option>Restaurants</option><option>Home services</option><option>Health</option><option>Education</option></select><select className="select input-sm !w-auto"><option>All cities</option><option>Dhaka</option><option>Chittagong</option><option>Sylhet</option></select><select className="select input-sm !w-auto"><option>Priority: All</option><option>Paid plan first</option><option>Oldest first</option><option>Flagged</option></select><select className="select input-sm !w-auto"><option>Reviewer: Anyone</option><option>Assigned to me</option><option>Unassigned</option></select>
      <button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 5h18l-7 8v6l-4 2v-8z"/></svg>More filters</button>
      <button className="btn btn-sm btn-ghost"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Reset</button>
      <div className="ml-auto flex gap-2"><button className="btn btn-sm btn-outline"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Export</button></div></div></div><div className="card "><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Business</th><th>Type</th><th>Category</th><th>Location</th><th>Submitted by</th><th>Documents</th><th>Phone</th><th>Submitted</th><th>Reviewer</th><th className="text-right">Actions</th></tr></thead>
      <tbody><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-a w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Prime Coaching Centre</p><p className="text-[11.5px] text-ink-400">Free plan · 4 photos</p></div></div></td><td><span className="badge badge-blue">New listing</span></td><td>Education › Coaching</td><td>Uttara, Dhaka</td><td>Kamal Hossain<p className="text-[11px] text-ink-400">kamal@mail.com</p></td><td><span className="badge badge-green">Trade licence ✓</span> <span className="badge badge-green">NID ✓</span></td><td><span className="badge badge-green">Verified</span></td><td>2 hours ago</td><td>Unassigned</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request info</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>Schedule field visit</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-b w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">City Dental Care</p><p className="text-[11.5px] text-ink-400">Gold plan · paid</p></div></div></td><td><span className="badge badge-blue">New listing</span></td><td>Health › Dental</td><td>Mirpur, Dhaka</td><td>Dr. Nusrat Jahan</td><td><span className="badge badge-green">BMDC licence ✓</span> <span className="badge badge-amber">NID pending</span></td><td><span className="badge badge-green">Verified</span></td><td>5 hours ago</td><td>Nafisa K.</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Review</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Verify licence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-c w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Elite Wedding Planners</p><p className="text-[11.5px] text-ink-400">Existing listing (unclaimed)</p></div></div></td><td><span className="badge badge-amber">Ownership claim</span></td><td>Events › Wedding</td><td>Bashundhara, Dhaka</td><td>Rifat Chowdhury</td><td><span className="badge badge-green">NID ✓</span> <span className="badge badge-green">Utility bill ✓</span></td><td><span className="badge badge-green">Verified</span></td><td>3 days ago</td><td>Sabbir A.</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Review claim</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>Call claimant</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve claim</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject claim</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-d w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Bismillah Biryani House</p><p className="text-[11.5px] text-ink-400">Silver plan</p></div></div></td><td><span className="badge badge-blue">Document review</span></td><td>Restaurants › Biryani</td><td>Old Dhaka</td><td>Jashim Uddin</td><td><span className="badge badge-green">Trade licence ✓</span> <span className="badge badge-red">Food licence missing</span></td><td><span className="badge badge-green">Verified</span></td><td>1 day ago</td><td>Unassigned</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  data-modal-open="m-service"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Review docs</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request food licence</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve</a></div></div></td></tr><tr><td><div className="flex items-center gap-2.5 min-w-[220px]"><span className="ph ph-e w-10 h-10 rounded-lg shrink-0"><svg className="" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg></span>
      <div className="min-w-0"><p className="text-[13px] font-bold text-ink-900 clamp-1">Smart Home Electricians</p><p className="text-[11.5px] text-ink-400">Free plan</p></div></div></td><td><span className="badge badge-blue">New listing</span></td><td>Home services › Electrician</td><td>Chittagong</td><td>Rakib Islam</td><td><span className="badge badge-red">No documents</span></td><td><span className="badge badge-red">Unverified</span></td><td>2 days ago</td><td>Unassigned</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 3h3l2 5-2 1a11 11 0 0 0 5 5l1-2 5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z"/></svg>Send OTP</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Request documents</a><a className="dd-item is-danger"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</a></div></div></td></tr></tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-[#f0f1f5]">
      <p className="text-[12.5px] text-ink-500">Showing <b>1–5</b> of <b>142</b> entries</p>
      <div className="flex items-center gap-3"><select className="select input-sm !w-auto"><option>10 / page</option><option>25 / page</option><option>50 / page</option><option>100 / page</option></select>
      <div className="pager"><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 6-6 6 6 6"/></svg></a><span className="is-current">1</span><a>2</a><a>3</a><a>…</a><a>15</a><a><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg></a></div></div></div></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Verification checklist — Prime Coaching Centre</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Business name matches trade licence</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Owner NID verified & matches applicant</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Phone number OTP verified</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Address found on map (geo-code)</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox"  className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Photos are original (not stock)</span><span className="badge badge-amber">Needs check</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Category correctly selected</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">No duplicate listing exists</span><span className="badge badge-green">Passed</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox"  className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">Business hours provided</span><span className="badge badge-amber">Needs check</span></label><label className="flex items-start gap-2.5 py-2 border-b border-[#f0f1f5] last:border-0">
      <input type="checkbox" defaultChecked className="mt-0.5" /><span className="text-[12.5px] font-semibold flex-1">No prohibited service offered</span><span className="badge badge-green">Passed</span></label>
      <div className="p-5 grid grid-cols-1 gap-3.5"><div className=""><label className="label">Reviewer note</label><textarea className="textarea !min-h-[90px]" placeholder="Internal note about this verification"></textarea></div><div className=""><label className="label">Verification level</label><select className="select"><option>Basic (phone only)</option><option>Standard (documents)</option><option>Premium (field visit)</option></select></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-primary" data-toast="Listing approved & published"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve & publish</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Approve without verified badge</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>Schedule field visit</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg>Reject</button></div></div></div><div className="card "><div className="card-head"><h3>Claim & document rules</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="p-5"><div className="frow"><div className="min-w-0"><p className="ft">Require NID for ownership claims</p><p className="fs">Claimant must upload national ID matching business documents.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Require trade licence for paid plans</p><p className="fs">Silver, Gold and Platinum listings must submit a licence.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Mandatory phone OTP</p><p className="fs">All listings must verify a business phone number.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Auto-notify existing owner on claim</p><p className="fs">Give the current owner 7 days to dispute a claim.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Field visit for Platinum</p><p className="fs">Physical verification for the highest tier.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div><div className="frow"><div className="min-w-0"><p className="ft">Special licence categories</p><p className="fs">Health, education, food and finance require regulator licence.</p></div>
      <div className="shrink-0"><label className="switch "><input type="checkbox" defaultChecked /><span className="track"></span></label></div></div></div><div className="p-4 pt-0"><div className="sb-note bg-blue-50 text-blue-700 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg><span>42 categories are marked as regulated. Listings in these categories cannot be published without a valid licence number.</span></div></div></div></div></div>
      
      <div className="modal" id="m-service"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel modal-lg">
      <div className="card-head"><h3>Service listing review — AC Repair &amp; Servicing</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
      <div className="p-5"><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Provider</span><span className="text-[12.5px] font-bold text-ink-800 text-right">CoolCare Services · #VND-2210</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Category</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Home services › AC repair</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Coverage</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Dhaka — Dhanmondi, Mohammadpur, Mirpur (+4)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Pricing</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Starting ৳700 · visit charge ৳300</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Team size</span><span className="text-[12.5px] font-bold text-ink-800 text-right">8 technicians</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Licence / trade doc</span><span className="text-[12.5px] font-bold text-ink-800 text-right">Uploaded · verified</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Photos</span><span className="text-[12.5px] font-bold text-ink-800 text-right">12 (workshop + team)</span></div><div className="flex justify-between gap-4 py-2 border-b border-[#f4f5f8] last:border-0"><span className="text-[12.5px] text-ink-500">Auto-checks</span><span className="text-[12.5px] font-bold text-ink-800 text-right"><span className="badge badge-green">Phone verified</span> <span className="badge badge-green">Address geocoded</span> <span className="badge badge-amber">Duplicate name</span></span></div></div>
      <div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Decision</label><select className="select"><option>Approve &amp; publish</option><option>Approve — needs photos</option><option>Request changes</option><option>Reject</option></select></div><div className=""><label className="label">Listing tier</label><select className="select"><option>Free</option><option>Verified</option><option>Sponsored (paid)</option></select></div></div>
      <div className="px-5"><div className=""><label className="label">Message to provider</label>$1$2</div></div>
      <div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Listing decision saved">Submit decision</button></div></div></div>
    </>
  );
}
