export default function SystemHealthPage() {
  return (
    <>
      <div className="page-head"><div><nav className="crumb mb-1.5"><a href="/admin/dashboard">Admin Panel</a><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 6 6 6-6 6"/></svg><span className="is-current">System health</span></nav>
      <h1>System Health</h1><p>Uptime, performance, infrastructure, backups and incident status.</p></div>
      <div className="flex flex-wrap items-center gap-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>Status page</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Run diagnostics</button><button className="btn btn-sm btn-primary" data-modal-open="m-inc"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>Create incident</button></div></div>
      <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3.5 mb-4"><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-brand-50 text-brand-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="7" rx="2"/><rect x="3" y="13" width="18" height="7" rx="2"/><path d="M7 7.5h.01M7 16.5h.01"/></svg></span>
      <span className="trend up"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>+0.02%</span></div>
      <p className="val">99.97%</p><p className="lbl">Uptime (30d)</p><p className="text-[11.5px] text-ink-400 mt-1.5">13 min downtime</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-service-50 text-service-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg></span>
      <span className="trend down"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v14M6 12l6 6 6-6"/></svg>24 ms</span></div>
      <p className="val">182 ms</p><p className="lbl">Avg. response time</p><p className="text-[11.5px] text-ink-400 mt-1.5">p95 640 ms</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-gold-50 text-gold-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg></span>
      <span className="trend down"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v14M6 12l6 6 6-6"/></svg>0.12%</span></div>
      <p className="val">0.41%</p><p className="lbl">Error rate</p><p className="text-[11.5px] text-ink-400 mt-1.5">Target below 0.5%</p></div><div className="stat">
      <div className="flex items-start justify-between mb-3"><span className="ico bg-ink-50 text-ink-600"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg></span>
      </div>
      <p className="val">1</p><p className="lbl">Active incidents</p><p className="text-[11.5px] text-ink-400 mt-1.5">Payment callback delays</p></div></div><div className="grid lg:grid-cols-3 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Service status</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18 15 15 0 0 1 0-18"/></svg>Public status page</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Service</th><th>Status</th><th>Latency</th><th>Uptime 30d</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Storefront (web)</b></td><td><span className="badge badge-green">Operational</span></td><td>164 ms</td><td>99.99%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Mobile API</b></td><td><span className="badge badge-green">Operational</span></td><td>142 ms</td><td>99.98%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Admin panel</b></td><td><span className="badge badge-green">Operational</span></td><td>210 ms</td><td>100%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Vendor panel</b></td><td><span className="badge badge-green">Operational</span></td><td>224 ms</td><td>99.96%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Checkout & payments</b></td><td><span className="badge badge-amber">Degraded</span></td><td>842 ms</td><td>99.82%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Incident</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Search service</b></td><td><span className="badge badge-green">Operational</span></td><td>86 ms</td><td>99.94%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Image CDN</b></td><td><span className="badge badge-green">Operational</span></td><td>42 ms</td><td>100%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Notification service</b></td><td><span className="badge badge-green">Operational</span></td><td>124 ms</td><td>99.92%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Metrics</a></div></div></td></tr><tr><td><b>Courier integrations</b></td><td><span className="badge badge-red">Partial outage</span></td><td>2.4 s</td><td>98.86%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 21V4h9l-1 3h7l-2 6 2 6H5"/></svg>Incident</a></div></div></td></tr><tr><td><b>Background workers</b></td><td><span className="badge badge-green">Operational</span></td><td>—</td><td>99.90%</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3 9 5-9 5-9-5z"/><path d="m3 13 9 5 9-5"/></svg>Queue depth</a></div></div></td></tr></tbody></table></div></div><div className="card "><div className="card-head"><h3>Infrastructure</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="hbar"><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Web servers — CPU</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "42%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">6 × 8 vCPU</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">App servers — CPU</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "58%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">12 × 16 vCPU</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Memory usage</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "64%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">384 GB total</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Database — CPU</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "72%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">Primary + 2 replicas</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Database — storage</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "48%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">2.4 TB of 5 TB</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Redis memory</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "38%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">64 GB</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Queue depth</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "22%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">4,862 jobs</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">CDN bandwidth</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "56%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">18.4 TB / month</span></div><div className="hbar-row"><span className="text-ink-600 font-semibold truncate">Object storage</span>
      <span className="hbar-track"><i className="hbar-fill" style={{width: "42%", background: "#ff2525"}}></i></span>
      <span className="num text-right font-bold text-ink-800">842 GB of 2 TB</span></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20V6M6 12l6-6 6 6"/></svg>Scale up</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>Capacity plan</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="2.6"/></svg>Cost report</button></div></div></div><div className="card "><div className="card-head"><h3>Backups & recovery</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Backup</th><th>Last run</th><th>Size</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>Database — full</b></td><td>Today 4:00 AM</td><td>486 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Restore</a></div></div></td></tr><tr><td><b>Database — incremental</b></td><td>30 min ago</td><td>4.2 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Restore</a></div></div></td></tr><tr><td><b>Media / object storage</b></td><td>Today 5:00 AM</td><td>842 GB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M21 3v5h-5M21 12a9 9 0 0 1-15 6.7L3 16"/><path d="M3 21v-5h5"/></svg>Restore</a></div></div></td></tr><tr><td><b>Configuration snapshot</b></td><td>Today 4:30 AM</td><td>18 MB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12M7 11l5 5 5-5M4 21h16"/></svg>Download</a></div></div></td></tr><tr><td><b>Off-site replica (Singapore)</b></td><td>1 hr ago</td><td>1.3 TB</td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Verify</a></div></div></td></tr></tbody></table></div>
      <div className="p-3"><div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Backup retention</span><b className="text-right">90 days daily + 12 monthly</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">RPO</span><b className="text-right">30 minutes</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">RTO</span><b className="text-right">2 hours</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Last restore test</span><b className="text-right">10 Aug 2026 — passed</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Encryption</span><b className="text-right">AES-256 at rest</b></div></div>
      <div className="flex gap-2 mt-2"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Run backup now</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 4.5 13.5H11l-1 8.5L19.5 10H13z"/></svg>Test restore</button></div></div></div></div></div><div className="tabs  mb-4" data-tabs><button className="tab is-active" data-tab="t0">Overview</button><button className="tab " data-tab="t1">Services<span className="count">12</span></button><button className="tab " data-tab="t2">Infrastructure<span className="count">8</span></button><button className="tab " data-tab="t3">Database<span className="count">4</span></button><button className="tab " data-tab="t4">Cache & queue<span className="count">3</span></button><button className="tab " data-tab="t5">Backups<span className="count">90</span></button><button className="tab " data-tab="t6">Incidents<span className="count">18</span></button><button className="tab " data-tab="t7">Scheduled maintenance<span className="count">2</span></button><button className="tab " data-tab="t8">Capacity</button></div><div className="grid lg:grid-cols-2 gap-4 mb-4"><div className="card "><div className="card-head"><h3>Incidents & maintenance</h3><div className="flex items-center gap-2"><button className="btn btn-sm btn-ghost"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12c0 1.7 3.6 3 8 3s8-1.3 8-3V6"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>Incident history</button></div></div><div className="tbl-wrap"><table className="tbl ">
      <thead><tr><th>Incident</th><th>Impact</th><th>Started</th><th>Duration</th><th>Status</th><th className="text-right"></th></tr></thead>
      <tbody><tr><td><b>#INC-042 — bKash callback delays</b></td><td>Some orders not marked paid</td><td>23 Aug, 3:48 PM</td><td>Ongoing 14 min</td><td><span className="badge badge-amber">Investigating</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open incident</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Post update</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 6 9 17l-5-5"/></svg>Resolve</a></div></div></td></tr><tr><td><b>#INC-041 — RedX API 500 errors</b></td><td>86 shipments delayed</td><td>23 Aug, 3:12 PM</td><td>Ongoing 50 min</td><td><span className="badge badge-amber">Identified</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6-10-6-10-6z"/><circle cx="12" cy="12" r="2.6"/></svg>Open incident</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a8 8 0 1 1-3.2-6.4"/><path d="M8 12h8M8 9h5"/></svg>Post update</a></div></div></td></tr><tr><td><b>#INC-040 — Redis outage</b></td><td>Slow pages for 4 min</td><td>23 Aug, 9:04 AM</td><td>4 min</td><td><span className="badge badge-green">Resolved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Post-mortem</a></div></div></td></tr><tr><td><b>#INC-039 — Search index lag</b></td><td>New products not searchable 22 min</td><td>21 Aug, 11:20 PM</td><td>22 min</td><td><span className="badge badge-green">Resolved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Post-mortem</a></div></div></td></tr><tr><td><b>#INC-038 — SMS gateway balance</b></td><td>OTP delivery failed for 842 users</td><td>18 Aug, 6:40 PM</td><td>38 min</td><td><span className="badge badge-green">Resolved</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Post-mortem</a></div></div></td></tr><tr><td><b>Scheduled — DB upgrade</b></td><td>Read-only mode 30 min</td><td>28 Aug, 3:00 AM</td><td>Planned</td><td><span className="badge badge-blue">Scheduled</span></td><td><div data-dropdown className="inline-block"><button data-dropdown-toggle className="btn btn-xs btn-outline"><svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3.5 6h.01M3.5 12h.01M3.5 18h.01"/></svg></button>
      <div data-dropdown-menu className="right-0 !min-w-[180px]"><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 20h4L20 8l-4-4L4 16z"/></svg>Edit window</a><a className="dd-item "  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9a6 6 0 1 1 12 0c0 5 2 6 2 6H4s2-1 2-6"/><path d="M10 19a2 2 0 0 0 4 0"/></svg>Notify users</a></div></div></td></tr></tbody></table></div></div><div className="card "><div className="card-head"><h3>Performance & capacity</h3><div className="flex items-center gap-2"></div></div><div className="p-4"><svg viewBox="0 0 640 180" className="w-full" style={{height: "180px"}} preserveAspectRatio="none">
      <defs><linearGradient id="gesponse time (ms) — last 7 days" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="Response time (ms) — last 7 days" stopOpacity=".24"/><stop offset="100%" stopColor="Response time (ms) — last 7 days" stopOpacity="0"/></linearGradient></defs>
      <line x1="0" y1="8" x2="640" y2="8" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="53" x2="640" y2="53" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="98" x2="640" y2="98" stroke="#eceef2" strokeWidth="1"/><line x1="0" y1="143" x2="640" y2="143" stroke="#eceef2" strokeWidth="1"/>
      <polygon points="0,180 0,141.61520190023754 106.66666666666667,140.13301662707838 213.33333333333334,137.53919239904988 320,133.09263657957246 426.6666666666667,16 533.3333333333334,94.1852731591449 640,138.28028503562945 640,180" fill="url(#gesponse time (ms) — last 7 days)"/>
      <polyline points="0,141.61520190023754 106.66666666666667,140.13301662707838 213.33333333333334,137.53919239904988 320,133.09263657957246 426.6666666666667,16 533.3333333333334,94.1852731591449 640,138.28028503562945" fill="none" stroke="Response time (ms) — last 7 days" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>
      <circle cx="0" cy="141.61520190023754" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="106.66666666666667" cy="140.13301662707838" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="213.33333333333334" cy="137.53919239904988" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="320" cy="133.09263657957246" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="426.6666666666667" cy="16" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="533.3333333333334" cy="94.1852731591449" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/><circle cx="640" cy="138.28028503562945" r="3" fill="#fff" stroke="Response time (ms) — last 7 days" strokeWidth="2"/></svg>
      <div className="space-y-2 text-[12.5px] "><div className="flex justify-between gap-3"><span className="text-ink-500">Peak concurrent users</span><b className="text-right">48,620 (Eid sale)</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Current concurrent users</span><b className="text-right">8,420</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Requests per second (peak)</span><b className="text-right">4,862</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Orders per minute (peak)</span><b className="text-right">186</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Database connections</span><b className="text-right">482 of 1,000</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Cache hit rate</span><b className="text-right">94.2%</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Slow queries (24h)</span><b className="text-right">124</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Auto-scaling</span><b className="text-right">Enabled — up to 24 app servers</b></div><div className="flex justify-between gap-3"><span className="text-ink-500">Next capacity review</span><b className="text-right">01 Sep 2026</b></div></div>
      <div className="mt-3"><div className="sb-note bg-gold-50 text-gold-800 flex gap-2"><svg className="w-4 h-4 shrink-0 mt-0.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3 2.5 20h19z"/><path d="M12 9v5M12 17h.01"/></svg><span>Traffic is projected to triple during the Eid campaign. Reserve extra capacity by 15 Sep.</span></div></div>
      <div className="flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4"/></svg>Load test report</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3.2"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>Scaling rules</button><button className="btn btn-sm btn-outline"  ><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.6-7 9-4-1.4-7-4.5-7-9V6z"/><path d="m9 12 2 2 4-4"/></svg>Uptime SLA report</button></div></div></div></div><div className="modal" id="m-inc"><div className="modal-backdrop" data-modal-close></div><div className="modal-panel ">
      <div className="card-head"><h3>Create incident</h3><button data-modal-close className="icon-btn"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div><div className="p-5 grid sm:grid-cols-2 gap-3.5"><div className=""><label className="label">Incident title *</label><input type="text" className="input" placeholder="e.g. Checkout failing on bKash payments" /></div><div className=""><label className="label">Affected service *</label><select className="select"><option>Storefront (web)</option><option>Mobile API</option><option>Checkout & payments</option><option>Search service</option><option>Courier integrations</option><option>Notification service</option><option>Admin panel</option><option>Vendor panel</option></select></div><div className=""><label className="label">Severity *</label><select className="select"><option>SEV1 — full outage</option><option>SEV2 — major degradation</option><option>SEV3 — minor issue</option><option>SEV4 — cosmetic</option></select></div><div className=""><label className="label">Status</label><select className="select"><option>Investigating</option><option>Identified</option><option>Monitoring</option><option>Resolved</option></select></div><div className=""><label className="label">Started at</label><input type="text" className="input" placeholder="23 Aug 2026, 3:48 PM" /></div><div className=""><label className="label">Incident commander</label><select className="select"><option>Engineering on-call</option><option>Aminul Islam</option><option>Platform team</option></select></div><div className="sm:col-span-2"><label className="label">Customer impact</label><textarea className="textarea !min-h-[90px]" placeholder="Some customers cannot complete bKash payments. Orders may show as unpaid."></textarea></div><div className="sm:col-span-2"><label className="label">Public status message</label><textarea className="textarea !min-h-[90px]" placeholder="We are investigating an issue affecting bKash payments. Your money is safe and orders will be updated automatically."></textarea></div><div className="sm:col-span-2 flex flex-wrap gap-4"><label className="check"><input type="checkbox" defaultChecked />Publish to public status page</label><label className="check"><input type="checkbox"   />Notify affected customers by SMS</label><label className="check"><input type="checkbox" defaultChecked />Notify vendors</label><label className="check"><input type="checkbox" defaultChecked />Show banner on storefront</label><label className="check"><input type="checkbox" defaultChecked />Page on-call engineer</label></div></div><div className="flex gap-2 p-5 pt-0"><button className="btn btn-outline flex-1" data-modal-close>Cancel</button><button className="btn btn-primary flex-1" data-modal-close data-toast="Incident created">Create incident</button></div></div></div>
    </>
  );
}
